#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Thu Feb 12 18:18:15 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package Win98HelpFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: Win98HelpFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(860, 560));
    $self->SetTitle("Windows Help");
    
    $self->{panel_main} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{panel_toolbar} = Wx::Panel->new($self->{panel_main}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxTAB_TRAVERSAL);
    $self->{sizer_root}->Add($self->{panel_toolbar}, 0, wxALL|wxEXPAND, 4);
    
    $self->{sizer_toolbar} = Wx::BoxSizer->new(wxHORIZONTAL);
    
    $self->{btn_hide} = Wx::Button->new($self->{panel_toolbar}, wxID_ANY, "Hide");
    $self->{btn_hide}->SetMinSize(Wx::Size->new(64, 24));
    $self->{sizer_toolbar}->Add($self->{btn_hide}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 4);
    
    my $line_tb1 = Wx::StaticLine->new($self->{panel_toolbar}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_VERTICAL);
    $line_tb1->SetMinSize(Wx::Size->new(2, 24));
    $self->{sizer_toolbar}->Add($line_tb1, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxTOP, 2);
    
    $self->{btn_back} = Wx::Button->new($self->{panel_toolbar}, wxID_ANY, "< Back");
    $self->{btn_back}->SetMinSize(Wx::Size->new(74, 24));
    $self->{sizer_toolbar}->Add($self->{btn_back}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 4);
    
    $self->{btn_forward} = Wx::Button->new($self->{panel_toolbar}, wxID_ANY, "Forward >");
    $self->{btn_forward}->SetMinSize(Wx::Size->new(82, 24));
    $self->{sizer_toolbar}->Add($self->{btn_forward}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 4);
    
    my $line_tb2 = Wx::StaticLine->new($self->{panel_toolbar}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_VERTICAL);
    $line_tb2->SetMinSize(Wx::Size->new(2, 24));
    $self->{sizer_toolbar}->Add($line_tb2, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxTOP, 2);
    
    $self->{btn_options} = Wx::Button->new($self->{panel_toolbar}, wxID_ANY, "Options");
    $self->{btn_options}->SetMinSize(Wx::Size->new(72, 24));
    $self->{sizer_toolbar}->Add($self->{btn_options}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 4);
    
    $self->{btn_webhelp} = Wx::Button->new($self->{panel_toolbar}, wxID_ANY, "Web Help");
    $self->{btn_webhelp}->SetMinSize(Wx::Size->new(78, 24));
    $self->{sizer_toolbar}->Add($self->{btn_webhelp}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 4);
    
    $self->{sizer_toolbar}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{splitter_main} = Wx::SplitterWindow->new($self->{panel_main}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{splitter_main}->SetMinimumPaneSize(20);
    $self->{sizer_root}->Add($self->{splitter_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{panel_left} = Wx::Panel->new($self->{splitter_main}, wxID_ANY);
    
    $self->{sizer_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_left} = Wx::Notebook->new($self->{panel_left}, wxID_ANY);
    $self->{sizer_left}->Add($self->{nb_left}, 1, wxEXPAND, 0);
    
    $self->{page_contents} = Wx::Panel->new($self->{nb_left}, wxID_ANY);
    $self->{nb_left}->AddPage($self->{page_contents}, "Contents");
    
    $self->{sizer_contents} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{tree_contents} = Wx::TreeCtrl->new($self->{page_contents}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT);
    $self->{sizer_contents}->Add($self->{tree_contents}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_index} = Wx::Panel->new($self->{nb_left}, wxID_ANY);
    $self->{nb_left}->AddPage($self->{page_index}, "Search");
    
    $self->{sizer_index} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_index_find} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_index}->Add($self->{sizer_index_find}, 0, wxALL|wxEXPAND, 6);
    
    $self->{txt_index} = Wx::TextCtrl->new($self->{page_index}, wxID_ANY, "");
    $self->{sizer_index_find}->Add($self->{txt_index}, 1, wxEXPAND, 0);
    
    $self->{btn_index_find} = Wx::Button->new($self->{page_index}, wxID_ANY, "Find");
    $self->{btn_index_find}->SetMinSize(Wx::Size->new(64, 24));
    $self->{sizer_index_find}->Add($self->{btn_index_find}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{list_index} = Wx::ListBox->new($self->{page_index}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Accessories", "Control Panel", "Desktop", "Internet", "Networking", "Printing", "Troubleshooting"], 0);
    $self->{sizer_index}->Add($self->{list_index}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{nb_left_Page4} = Wx::Panel->new($self->{nb_left}, wxID_ANY);
    $self->{nb_left}->AddPage($self->{nb_left_Page4}, "Index");
    
    $self->{panel_right} = Wx::Panel->new($self->{splitter_main}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxTAB_TRAVERSAL);
    
    $self->{sizer_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_view} = Wx::TextCtrl->new($self->{panel_right}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY|wxTE_RICH2);
    $self->{sizer_right}->Add($self->{txt_view}, 1, wxALL|wxEXPAND, 8);
    
    $self->{panel_right}->SetSizer($self->{sizer_right});
    
    $self->{page_index}->SetSizer($self->{sizer_index});
    
    $self->{page_contents}->SetSizer($self->{sizer_contents});
    
    $self->{panel_left}->SetSizer($self->{sizer_left});
    
    $self->{splitter_main}->SplitVertically($self->{panel_left}, $self->{panel_right}, );
    
    $self->{panel_toolbar}->SetSizer($self->{sizer_toolbar});
    
    $self->{panel_main}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade

    $self->{splitter_main}->SetMinimumPaneSize(160);
    $self->{splitter_main}->SetSashPosition(280, 1);

    return $self;

}


# end of class Win98HelpFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_help = Win98HelpFrame->new();

    $self->SetTopWindow($frame_help);
    $frame_help->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
