#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Thu Feb  5 00:51:48 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package BrowserFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: BrowserFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(980, 680));
    $self->SetTitle("Netscape 2.0-ish Browser (Layout Only)");
    
    

    # Menu Bar

    $self->{frame_browser_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "File");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "Edit");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "View");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "Go");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "Bookmarks");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "Options");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "Directory");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "Window");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{frame_browser_menubar}->Append($wxglade_tmp_menu, "Help");
    $self->SetMenuBar($self->{frame_browser_menubar});
    
    # Menu Bar end

    
    $self->{panel_main} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_toolbar} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_toolbar}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_back} = Wx::Button->new($self->{panel_main}, wxID_ANY, "\N{U+25c0}");
    $self->{btn_back}->SetMinSize(Wx::Size->new(36, 36));
    $self->{btn_back}->SetToolTip("Back");
    $self->{sizer_toolbar}->Add($self->{btn_back}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_forward} = Wx::Button->new($self->{panel_main}, wxID_ANY, "\N{U+25b6}");
    $self->{btn_forward}->SetMinSize(Wx::Size->new(36, 36));
    $self->{btn_forward}->SetToolTip("Forward");
    $self->{sizer_toolbar}->Add($self->{btn_forward}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_home} = Wx::Button->new($self->{panel_main}, wxID_ANY, "\N{U+2302}");
    $self->{btn_home}->SetMinSize(Wx::Size->new(36, 36));
    $self->{btn_home}->SetToolTip("Home");
    $self->{sizer_toolbar}->Add($self->{btn_home}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_reload} = Wx::Button->new($self->{panel_main}, wxID_ANY, "\N{U+27f3}");
    $self->{btn_reload}->SetMinSize(Wx::Size->new(36, 36));
    $self->{btn_reload}->SetToolTip("Reload");
    $self->{sizer_toolbar}->Add($self->{btn_reload}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_stop} = Wx::Button->new($self->{panel_main}, wxID_ANY, "\N{U+2715}");
    $self->{btn_stop}->SetMinSize(Wx::Size->new(36, 36));
    $self->{btn_stop}->SetToolTip("Stop");
    $self->{sizer_toolbar}->Add($self->{btn_stop}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_toolbar}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_bookmarks} = Wx::Button->new($self->{panel_main}, wxID_ANY, "\N{U+2606}");
    $self->{btn_bookmarks}->SetMinSize(Wx::Size->new(36, 36));
    $self->{btn_bookmarks}->SetToolTip("Bookmarks");
    $self->{sizer_toolbar}->Add($self->{btn_bookmarks}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_location} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_location}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_location = Wx::StaticText->new($self->{panel_main}, wxID_ANY, "Location:");
    $self->{sizer_location}->Add($lbl_location, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_url} = Wx::TextCtrl->new($self->{panel_main}, wxID_ANY, "http://");
    $self->{sizer_location}->Add($self->{txt_url}, 1, wxEXPAND|wxLEFT, 6);
    
    $self->{btn_go} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Go");
    $self->{sizer_location}->Add($self->{btn_go}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{panel_view} = Wx::Panel->new($self->{panel_main}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxTAB_TRAVERSAL);
    $self->{sizer_root}->Add($self->{panel_view}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{sizer_view} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_view_placeholder = Wx::StaticText->new($self->{panel_view}, wxID_ANY, "[ HTML rendering view goes here ]");
    $self->{sizer_view}->Add($lbl_view_placeholder, 1, wxALL|wxEXPAND, 10);
    
    my $lbl_status = Wx::StaticText->new($self->{panel_main}, wxID_ANY, "Done.");
    $self->{sizer_root}->Add($lbl_status, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{panel_view}->SetSizer($self->{sizer_view});
    
    $self->{panel_main}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class BrowserFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_browser = BrowserFrame->new();

    $self->SetTopWindow($frame_browser);
    $frame_browser->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
