#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Fri Feb  6 01:29:21 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package PuttySessionFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: PuttySessionFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(812, 520));
    $self->SetTitle("PuTTY Configuration");
    
    $self->{panel_main} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{splitter_main} = Wx::SplitterWindow->new($self->{panel_main}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{splitter_main}->SetMinimumPaneSize(120);
    $self->{sizer_root}->Add($self->{splitter_main}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_left} = Wx::Panel->new($self->{splitter_main}, wxID_ANY);
    
    $self->{sizer_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_category = Wx::StaticText->new($self->{panel_left}, wxID_ANY, "Category:");
    $self->{sizer_left}->Add($lbl_category, 0, wxALL, 4);
    
    $self->{tree_category} = Wx::TreeCtrl->new($self->{panel_left}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT);
    $self->{sizer_left}->Add($self->{tree_category}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{panel_right} = Wx::Panel->new($self->{splitter_main}, wxID_ANY);
    
    $self->{sizer_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_basic} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_right}, wxID_ANY, "Basic options for your PuTTY session"), wxVERTICAL);
    $self->{sizer_right}->Add($self->{box_basic}, 0, wxALL|wxEXPAND, 4);
    
    my $lbl_dest = Wx::StaticText->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "Specify the destination you want to connect to");
    $self->{box_basic}->Add($lbl_dest, 0, wxALL, 6);
    
    $self->{grid_hostport} = Wx::FlexGridSizer->new(0, 3, 4, 6);
    $self->{box_basic}->Add($self->{grid_hostport}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_host = Wx::StaticText->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "Host Name (or IP address)");
    $self->{grid_hostport}->Add($lbl_host, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_host} = Wx::TextCtrl->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_hostport}->Add($self->{txt_host}, 1, wxEXPAND, 0);
    
    $self->{sizer_port} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{grid_hostport}->Add($self->{sizer_port}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_port = Wx::StaticText->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "Port");
    $self->{sizer_port}->Add($lbl_port, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_port} = Wx::TextCtrl->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_port}->SetMinSize(Wx::Size->new(60,-1));
    $self->{sizer_port}->Add($self->{txt_port}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 4);
    
    $self->{sizer_conn} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_basic}->Add($self->{sizer_conn}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_conn = Wx::StaticText->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "Connection type:");
    $self->{sizer_conn}->Add($lbl_conn, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{rb_ssh} = Wx::RadioButton->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "SSH", wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    $self->{sizer_conn}->Add($self->{rb_ssh}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{rb_serial} = Wx::RadioButton->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "Serial");
    $self->{sizer_conn}->Add($self->{rb_serial}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{rb_other} = Wx::RadioButton->new($self->{box_basic}->GetStaticBox(), wxID_ANY, "Other:");
    $self->{sizer_conn}->Add($self->{rb_other}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{choice_other} = Wx::Choice->new($self->{box_basic}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Telnet", "Rlogin", "Raw"], );
    $self->{choice_other}->SetSelection(0);
    $self->{sizer_conn}->Add($self->{choice_other}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_conn}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{box_saved} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_right}, wxID_ANY, "Load, save or delete a stored session"), wxVERTICAL);
    $self->{sizer_right}->Add($self->{box_saved}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{grid_saved} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{box_saved}->Add($self->{grid_saved}, 0, wxALL|wxEXPAND, 6);
    
    $self->{sizer_saved_left} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{grid_saved}->Add($self->{sizer_saved_left}, 1, wxEXPAND, 0);
    
    my $lbl_saved_sessions = Wx::StaticText->new($self->{box_saved}->GetStaticBox(), wxID_ANY, "Saved Sessions");
    $self->{sizer_saved_left}->Add($lbl_saved_sessions, 0, wxEXPAND, 0);
    
    $self->{list_sessions} = Wx::ListBox->new($self->{box_saved}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Default Settings", "carpenter", "gold", "mike"], 0);
    $self->{sizer_saved_left}->Add($self->{list_sessions}, 1, wxEXPAND|wxTOP, 4);
    
    $self->{sizer_saved_btns} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{grid_saved}->Add($self->{sizer_saved_btns}, 0, wxEXPAND, 0);
    
    $self->{btn_load} = Wx::Button->new($self->{box_saved}->GetStaticBox(), wxID_ANY, "Load");
    $self->{btn_load}->SetMinSize(Wx::Size->new(88,-1));
    $self->{sizer_saved_btns}->Add($self->{btn_load}, 0, wxEXPAND, 0);
    
    $self->{btn_save} = Wx::Button->new($self->{box_saved}->GetStaticBox(), wxID_ANY, "Save");
    $self->{btn_save}->SetMinSize(Wx::Size->new(88,-1));
    $self->{sizer_saved_btns}->Add($self->{btn_save}, 0, wxEXPAND|wxTOP, 6);
    
    $self->{btn_delete} = Wx::Button->new($self->{box_saved}->GetStaticBox(), wxID_ANY, "Delete");
    $self->{btn_delete}->SetMinSize(Wx::Size->new(88,-1));
    $self->{sizer_saved_btns}->Add($self->{btn_delete}, 0, wxEXPAND|wxTOP, 6);
    
    $self->{sizer_saved_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{box_close} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{box_saved}->GetStaticBox(), wxID_ANY, "Close window on exit:"), wxHORIZONTAL);
    $self->{box_saved}->Add($self->{box_close}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{rb_close_always} = Wx::RadioButton->new($self->{box_close}->GetStaticBox(), wxID_ANY, "Always", wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    $self->{box_close}->Add($self->{rb_close_always}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 8);
    
    $self->{rb_close_never} = Wx::RadioButton->new($self->{box_close}->GetStaticBox(), wxID_ANY, "Never");
    $self->{box_close}->Add($self->{rb_close_never}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 8);
    
    $self->{rb_close_clean} = Wx::RadioButton->new($self->{box_close}->GetStaticBox(), wxID_ANY, "Only on clean exit");
    $self->{box_close}->Add($self->{rb_close_clean}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 8);
    
    $self->{sizer_bottom} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_bottom}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_about} = Wx::Button->new($self->{panel_main}, wxID_ANY, "About");
    $self->{btn_about}->SetMinSize(Wx::Size->new(88,-1));
    $self->{sizer_bottom}->Add($self->{btn_about}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_help} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Help");
    $self->{btn_help}->SetMinSize(Wx::Size->new(88,-1));
    $self->{sizer_bottom}->Add($self->{btn_help}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_bottom}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_open} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Open");
    $self->{btn_open}->SetMinSize(Wx::Size->new(88,-1));
    $self->{sizer_bottom}->Add($self->{btn_open}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_cancel} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Cancel");
    $self->{btn_cancel}->SetMinSize(Wx::Size->new(88,-1));
    $self->{sizer_bottom}->Add($self->{btn_cancel}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{grid_saved}->AddGrowableCol(0);
    
    $self->{grid_hostport}->AddGrowableCol(1);
    
    $self->{panel_right}->SetSizer($self->{sizer_right});
    
    $self->{panel_left}->SetSizer($self->{sizer_left});
    
    $self->{splitter_main}->SplitVertically($self->{panel_left}, $self->{panel_right}, );
    
    $self->{panel_main}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade

    $self->{splitter_main}->SetSashPosition(160, 1);

    $self->init_tree;

    return $self;
}

# initialize tree view of menu items
sub init_tree {
    my ($self) = @_;

    my $tree = $self->{tree_category};

    my $root = $tree->AddRoot('Session');

    my $logging = $tree->AppendItem($root, 'Logging');

    my $terminal = $tree->AppendItem($root, 'Terminal');
    $tree->AppendItem($terminal, 'Keyboard');
    $tree->AppendItem($terminal, 'Bell');
    $tree->AppendItem($terminal, 'Features');

    my $window = $tree->AppendItem($root, 'Window');
    $tree->AppendItem($window, 'Appearance');
    $tree->AppendItem($window, 'Behaviour');
    $tree->AppendItem($window, 'Translation');
    $tree->AppendItem($window, 'Selection');
    $tree->AppendItem($window, 'Colours');

    my $connection = $tree->AppendItem($root, 'Connection');
    $tree->AppendItem($connection, 'Data');
    $tree->AppendItem($connection, 'Proxy');
    $tree->AppendItem($connection, 'SSH');
    $tree->AppendItem($connection, 'Serial');
    $tree->AppendItem($connection, 'Telnet');
    $tree->AppendItem($connection, 'Rlogin');
    $tree->AppendItem($connection, 'SUPDUP');

    $tree->ExpandAll;
    $tree->SelectItem($root);
}

# end of class PuttySessionFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_putty = PuttySessionFrame->new();

    $self->SetTopWindow($frame_putty);
    $frame_putty->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
