#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Fri Feb  6 00:39:33 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package WSFTPFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: WSFTPFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(945, 620));
    $self->SetTitle("WS_FTP LE - wsftp clone");
    
    $self->{panel_main} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_top} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_top}, 1, wxALL|wxEXPAND, 8);
    
    $self->{sizer_local_box} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_main}, wxID_ANY, "Local System"), wxVERTICAL);
    $self->{sizer_top}->Add($self->{sizer_local_box}, 1, wxEXPAND, 0);
    
    $self->{combo_local_path} = Wx::ComboBox->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, ["C:\\Documents and Settings\\...", "C:\\", "C:\\Users\\", "C:\\Temp\\"], wxCB_DROPDOWN);
    $self->{combo_local_path}->SetSelection(0);
    $self->{sizer_local_box}->Add($self->{combo_local_path}, 0, wxALL|wxEXPAND, 6);
    
    $self->{sizer_local_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_local_box}->Add($self->{sizer_local_row}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{list_local} = Wx::ListCtrl->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_local_row}->Add($self->{list_local}, 1, wxEXPAND, 0);
    
    $self->{sizer_local_btns} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_local_row}->Add($self->{sizer_local_btns}, 0, wxEXPAND|wxLEFT, 8);
    
    $self->{btn_local_chgdir} = Wx::Button->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "ChgDir");
    $self->{btn_local_chgdir}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_local_btns}->Add($self->{btn_local_chgdir}, 0, wxEXPAND, 0);
    
    $self->{btn_local_mkdir} = Wx::Button->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "MkDir");
    $self->{btn_local_mkdir}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_local_btns}->Add($self->{btn_local_mkdir}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_local_view} = Wx::Button->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "View");
    $self->{btn_local_view}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_local_btns}->Add($self->{btn_local_view}, 0, wxEXPAND|wxTOP, 10);
    
    $self->{btn_local_exec} = Wx::Button->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "Exec");
    $self->{btn_local_exec}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_local_btns}->Add($self->{btn_local_exec}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_local_rename} = Wx::Button->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "Rename");
    $self->{btn_local_rename}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_local_btns}->Add($self->{btn_local_rename}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_local_delete} = Wx::Button->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "Delete");
    $self->{btn_local_delete}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_local_btns}->Add($self->{btn_local_delete}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_local_refresh} = Wx::Button->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "Refresh");
    $self->{btn_local_refresh}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_local_btns}->Add($self->{btn_local_refresh}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_local_dirinfo} = Wx::Button->new($self->{sizer_local_box}->GetStaticBox(), wxID_ANY, "DirInfo");
    $self->{btn_local_dirinfo}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_local_btns}->Add($self->{btn_local_dirinfo}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{sizer_local_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{sizer_center} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_top}->Add($self->{sizer_center}, 0, wxEXPAND|wxLEFT|wxRIGHT, 10);
    
    $self->{sizer_center}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_to_remote} = Wx::Button->new($self->{panel_main}, wxID_ANY, "-->");
    $self->{btn_to_remote}->SetMinSize(Wx::Size->new(54, 30));
    $self->{sizer_center}->Add($self->{btn_to_remote}, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    
    $self->{btn_to_local} = Wx::Button->new($self->{panel_main}, wxID_ANY, "<--");
    $self->{btn_to_local}->SetMinSize(Wx::Size->new(54, 30));
    $self->{sizer_center}->Add($self->{btn_to_local}, 0, wxALIGN_CENTER_HORIZONTAL|wxTOP, 6);
    
    $self->{sizer_center}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{sizer_remote_box} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_main}, wxID_ANY, "Remote Site"), wxVERTICAL);
    $self->{sizer_top}->Add($self->{sizer_remote_box}, 1, wxEXPAND, 0);
    
    $self->{combo_remote_path} = Wx::ComboBox->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, ["/apps/u/home/inst/j/q/jqjacobs", "/", "/home", "/apps"], wxCB_DROPDOWN);
    $self->{combo_remote_path}->SetSelection(0);
    $self->{sizer_remote_box}->Add($self->{combo_remote_path}, 0, wxALL|wxEXPAND, 6);
    
    $self->{sizer_remote_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_remote_box}->Add($self->{sizer_remote_row}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{list_remote} = Wx::ListCtrl->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_remote_row}->Add($self->{list_remote}, 1, wxEXPAND, 0);
    
    $self->{sizer_remote_btns} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_remote_row}->Add($self->{sizer_remote_btns}, 0, wxEXPAND|wxLEFT, 8);
    
    $self->{btn_remote_chgdir} = Wx::Button->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "ChgDir");
    $self->{btn_remote_chgdir}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_remote_btns}->Add($self->{btn_remote_chgdir}, 0, wxEXPAND, 0);
    
    $self->{btn_remote_mkdir} = Wx::Button->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "MkDir");
    $self->{btn_remote_mkdir}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_remote_btns}->Add($self->{btn_remote_mkdir}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_remote_view} = Wx::Button->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "View");
    $self->{btn_remote_view}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_remote_btns}->Add($self->{btn_remote_view}, 0, wxEXPAND|wxTOP, 10);
    
    $self->{btn_remote_exec} = Wx::Button->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "Exec");
    $self->{btn_remote_exec}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_remote_btns}->Add($self->{btn_remote_exec}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_remote_rename} = Wx::Button->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "Rename");
    $self->{btn_remote_rename}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_remote_btns}->Add($self->{btn_remote_rename}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_remote_delete} = Wx::Button->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "Delete");
    $self->{btn_remote_delete}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_remote_btns}->Add($self->{btn_remote_delete}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_remote_refresh} = Wx::Button->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "Refresh");
    $self->{btn_remote_refresh}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_remote_btns}->Add($self->{btn_remote_refresh}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{btn_remote_dirinfo} = Wx::Button->new($self->{sizer_remote_box}->GetStaticBox(), wxID_ANY, "DirInfo");
    $self->{btn_remote_dirinfo}->SetMinSize(Wx::Size->new(72, 26));
    $self->{sizer_remote_btns}->Add($self->{btn_remote_dirinfo}, 0, wxEXPAND|wxTOP, 4);
    
    $self->{sizer_remote_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{sizer_mode} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_mode}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{rb_ascii} = Wx::RadioButton->new($self->{panel_main}, wxID_ANY, "ASCII", wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    $self->{sizer_mode}->Add($self->{rb_ascii}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{rb_binary} = Wx::RadioButton->new($self->{panel_main}, wxID_ANY, "Binary");
    $self->{sizer_mode}->Add($self->{rb_binary}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 16);
    
    $self->{cb_auto} = Wx::CheckBox->new($self->{panel_main}, wxID_ANY, "Auto");
    $self->{cb_auto}->SetValue(1);
    $self->{sizer_mode}->Add($self->{cb_auto}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 22);
    
    $self->{sizer_mode}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{txt_log} = Wx::TextCtrl->new($self->{panel_main}, wxID_ANY, "150 Opening ASCII mode data connection for /bin/ls.\nReceived 196 bytes in 0.1 secs, transfer succeeded\n226 Transfer complete.", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY|wxTE_RICH2);
    $self->{txt_log}->SetMinSize(Wx::Size->new(-1, 110));
    $self->{sizer_root}->Add($self->{txt_log}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{sizer_bottom} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_bottom}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{btn_close} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Close");
    $self->{btn_close}->SetMinSize(Wx::Size->new(88, 28));
    $self->{sizer_bottom}->Add($self->{btn_close}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_cancel} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Cancel");
    $self->{btn_cancel}->SetMinSize(Wx::Size->new(88, 28));
    $self->{sizer_bottom}->Add($self->{btn_cancel}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_bottom}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_logwnd} = Wx::Button->new($self->{panel_main}, wxID_ANY, "LogWnd");
    $self->{btn_logwnd}->SetMinSize(Wx::Size->new(88, 28));
    $self->{sizer_bottom}->Add($self->{btn_logwnd}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_help} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Help");
    $self->{btn_help}->SetMinSize(Wx::Size->new(88, 28));
    $self->{sizer_bottom}->Add($self->{btn_help}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_options} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Options");
    $self->{btn_options}->SetMinSize(Wx::Size->new(88, 28));
    $self->{sizer_bottom}->Add($self->{btn_options}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_about} = Wx::Button->new($self->{panel_main}, wxID_ANY, "About");
    $self->{btn_about}->SetMinSize(Wx::Size->new(88, 28));
    $self->{sizer_bottom}->Add($self->{btn_about}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_exit} = Wx::Button->new($self->{panel_main}, wxID_ANY, "Exit");
    $self->{btn_exit}->SetMinSize(Wx::Size->new(88, 28));
    $self->{sizer_bottom}->Add($self->{btn_exit}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{panel_main}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class WSFTPFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_wsftp = WSFTPFrame->new();

    $self->SetTopWindow($frame_wsftp);
    $frame_wsftp->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
