#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Fri Feb 13 00:22:37 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package LimeFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: LimeFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1100, 750));
    $self->SetTitle("LimeWire");
    
    

    # Menu Bar

    $self->{menubar_main} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $self->{menu_file} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_file}, "File");
    $self->{menu_view} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_view}, "View");
    $self->{menu_nav} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_nav}, "Navigation");
    $self->{menu_resources} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_resources}, "Resources");
    $self->{menu_tools} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_tools}, "Tools");
    $self->{menu_filters} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_filters}, "Filters");
    $self->{menu_help} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_help}, "Help");
    $self->SetMenuBar($self->{menubar_main});
    
    # Menu Bar end

    
    $self->{panel_main} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_top} = Wx::Notebook->new($self->{panel_main}, wxID_ANY);
    $self->{sizer_root}->Add($self->{nb_top}, 1, wxALL|wxEXPAND, 4);
    
    $self->{page_search} = Wx::Panel->new($self->{nb_top}, wxID_ANY);
    $self->{nb_top}->AddPage($self->{page_search}, "Search");
    
    $self->{sizer_search_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_search_header} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_search}, wxID_ANY, "Search"), wxHORIZONTAL);
    $self->{sizer_search_root}->Add($self->{box_search_header}, 0, wxALL|wxEXPAND, 6);
    
    $self->{txt_search_query} = Wx::TextCtrl->new($self->{box_search_header}->GetStaticBox(), wxID_ANY, "");
    $self->{box_search_header}->Add($self->{txt_search_query}, 1, wxALL|wxEXPAND, 6);
    
    $self->{btn_search_go} = Wx::Button->new($self->{box_search_header}->GetStaticBox(), wxID_ANY, "Search");
    $self->{box_search_header}->Add($self->{btn_search_go}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{splitter_search} = Wx::SplitterWindow->new($self->{page_search}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{splitter_search}->SetMinimumPaneSize(20);
    $self->{sizer_search_root}->Add($self->{splitter_search}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{panel_search_left} = Wx::Panel->new($self->{splitter_search}, wxID_ANY);
    
    $self->{sizer_search_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_filter_results = Wx::StaticText->new($self->{panel_search_left}, wxID_ANY, "Filter Results:");
    $self->{sizer_search_left}->Add($lbl_filter_results, 0, wxALL, 4);
    
    $self->{box_media} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_search_left}, wxID_ANY, "Media"), wxVERTICAL);
    $self->{sizer_search_left}->Add($self->{box_media}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{list_media} = Wx::ListBox->new($self->{box_media}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["All", "Audio", "Programs", "Video"], 0);
    $self->{box_media}->Add($self->{list_media}, 1, wxALL|wxEXPAND, 4);
    
    $self->{box_artist} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_search_left}, wxID_ANY, "Artist"), wxVERTICAL);
    $self->{sizer_search_left}->Add($self->{box_artist}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{list_artist} = Wx::ListBox->new($self->{box_artist}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, [], 0);
    $self->{box_artist}->Add($self->{list_artist}, 1, wxALL|wxEXPAND, 4);
    
    $self->{box_album} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_search_left}, wxID_ANY, "Album"), wxVERTICAL);
    $self->{sizer_search_left}->Add($self->{box_album}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{list_album} = Wx::ListBox->new($self->{box_album}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, [], 0);
    $self->{box_album}->Add($self->{list_album}, 1, wxALL|wxEXPAND, 4);
    
    $self->{panel_search_right} = Wx::Panel->new($self->{splitter_search}, wxID_ANY);
    
    $self->{sizer_search_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_results_title = Wx::StaticText->new($self->{panel_search_right}, wxID_ANY, "Search Results");
    $self->{sizer_search_right}->Add($lbl_results_title, 0, wxALL|wxEXPAND, 4);
    
    $self->{list_results} = Wx::ListCtrl->new($self->{panel_search_right}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_search_right}->Add($self->{list_results}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{sizer_search_actions} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_search_right}->Add($self->{sizer_search_actions}, 0, wxALIGN_CENTER_HORIZONTAL|wxBOTTOM|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_download} = Wx::Button->new($self->{panel_search_right}, wxID_ANY, "Download");
    $self->{sizer_search_actions}->Add($self->{btn_download}, 0, wxALL, 6);
    
    $self->{btn_browse_host} = Wx::Button->new($self->{panel_search_right}, wxID_ANY, "Browse Host");
    $self->{sizer_search_actions}->Add($self->{btn_browse_host}, 0, wxALL, 6);
    
    $self->{btn_stop_search} = Wx::Button->new($self->{panel_search_right}, wxID_ANY, "Stop Search");
    $self->{sizer_search_actions}->Add($self->{btn_stop_search}, 0, wxALL, 6);
    
    $self->{btn_junk} = Wx::Button->new($self->{panel_search_right}, wxID_ANY, "Junk");
    $self->{sizer_search_actions}->Add($self->{btn_junk}, 0, wxALL, 6);
    
    $self->{box_downloads} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_search}, wxID_ANY, "Downloads"), wxVERTICAL);
    $self->{sizer_search_root}->Add($self->{box_downloads}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{list_downloads} = Wx::ListCtrl->new($self->{box_downloads}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT);
    $self->{box_downloads}->Add($self->{list_downloads}, 0, wxALL|wxEXPAND, 4);
    
    $self->{gauge_progress} = Wx::Gauge->new($self->{box_downloads}->GetStaticBox(), wxID_ANY, 100, wxDefaultPosition, wxDefaultSize, 0);
    $self->{box_downloads}->Add($self->{gauge_progress}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{page_monitor} = Wx::Panel->new($self->{nb_top}, wxID_ANY);
    $self->{nb_top}->AddPage($self->{page_monitor}, "Monitor");
    
    $self->{sizer_monitor_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_monitor_summary} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_monitor}, wxID_ANY, "Activity Summary"), wxHORIZONTAL);
    $self->{sizer_monitor_root}->Add($self->{box_monitor_summary}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_monitor_left = Wx::StaticText->new($self->{box_monitor_summary}->GetStaticBox(), wxID_ANY, "Downloads: 0 active, 0 queued");
    $self->{box_monitor_summary}->Add($lbl_monitor_left, 1, wxALL|wxEXPAND, 6);
    
    my $lbl_monitor_right = Wx::StaticText->new($self->{box_monitor_summary}->GetStaticBox(), wxID_ANY, "Uploads: 0 active, 0 queued");
    $self->{box_monitor_summary}->Add($lbl_monitor_right, 1, wxALL|wxEXPAND, 6);
    
    $self->{splitter_monitor} = Wx::SplitterWindow->new($self->{page_monitor}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{splitter_monitor}->SetMinimumPaneSize(20);
    $self->{sizer_monitor_root}->Add($self->{splitter_monitor}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 4);
    
    $self->{panel_monitor_left} = Wx::Panel->new($self->{splitter_monitor}, wxID_ANY);
    
    $self->{sizer_monitor_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_monitor_downloads} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_monitor_left}, wxID_ANY, "Downloads"), wxVERTICAL);
    $self->{sizer_monitor_left}->Add($self->{box_monitor_downloads}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_monitor_downloads} = Wx::ListCtrl->new($self->{box_monitor_downloads}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT);
    $self->{box_monitor_downloads}->Add($self->{list_monitor_downloads}, 1, wxALL|wxEXPAND, 4);
    
    $self->{panel_monitor_right} = Wx::Panel->new($self->{splitter_monitor}, wxID_ANY);
    
    $self->{sizer_monitor_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_monitor_uploads} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_monitor_right}, wxID_ANY, "Uploads"), wxVERTICAL);
    $self->{sizer_monitor_right}->Add($self->{box_monitor_uploads}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_monitor_uploads} = Wx::ListCtrl->new($self->{box_monitor_uploads}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT);
    $self->{box_monitor_uploads}->Add($self->{list_monitor_uploads}, 1, wxALL|wxEXPAND, 4);
    
    $self->{box_monitor_log} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_monitor}, wxID_ANY, "Status / Details"), wxVERTICAL);
    $self->{sizer_monitor_root}->Add($self->{box_monitor_log}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{txt_monitor_status} = Wx::TextCtrl->new($self->{box_monitor_log}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{txt_monitor_status}->SetMinSize(Wx::Size->new(-1,90));
    $self->{box_monitor_log}->Add($self->{txt_monitor_status}, 0, wxALL|wxEXPAND, 4);
    
    $self->{page_connections} = Wx::Panel->new($self->{nb_top}, wxID_ANY);
    $self->{nb_top}->AddPage($self->{page_connections}, "Connections");
    
    $self->{sizer_connections_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_conn_header} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_connections}, wxID_ANY, "Connection"), wxHORIZONTAL);
    $self->{sizer_connections_root}->Add($self->{box_conn_header}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_conn_status = Wx::StaticText->new($self->{box_conn_header}->GetStaticBox(), wxID_ANY, "Status: Disconnected (placeholder)");
    $self->{box_conn_header}->Add($lbl_conn_status, 1, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_conn_connect} = Wx::Button->new($self->{box_conn_header}->GetStaticBox(), wxID_ANY, "Connect");
    $self->{box_conn_header}->Add($self->{btn_conn_connect}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_conn_disconnect} = Wx::Button->new($self->{box_conn_header}->GetStaticBox(), wxID_ANY, "Disconnect");
    $self->{box_conn_header}->Add($self->{btn_conn_disconnect}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_peers} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_connections}, wxID_ANY, "Peers"), wxVERTICAL);
    $self->{sizer_connections_root}->Add($self->{box_peers}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{list_peers} = Wx::ListCtrl->new($self->{box_peers}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT);
    $self->{box_peers}->Add($self->{list_peers}, 1, wxALL|wxEXPAND, 4);
    
    $self->{box_conn_messages} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_connections}, wxID_ANY, "Messages"), wxVERTICAL);
    $self->{sizer_connections_root}->Add($self->{box_conn_messages}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{txt_conn_messages} = Wx::TextCtrl->new($self->{box_conn_messages}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{txt_conn_messages}->SetMinSize(Wx::Size->new(-1,90));
    $self->{box_conn_messages}->Add($self->{txt_conn_messages}, 0, wxALL|wxEXPAND, 4);
    
    $self->{page_library} = Wx::Panel->new($self->{nb_top}, wxID_ANY);
    $self->{nb_top}->AddPage($self->{page_library}, "Library");
    
    $self->{sizer_library_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{splitter_library} = Wx::SplitterWindow->new($self->{page_library}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{splitter_library}->SetMinimumPaneSize(20);
    $self->{sizer_library_root}->Add($self->{splitter_library}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_library_left} = Wx::Panel->new($self->{splitter_library}, wxID_ANY);
    
    $self->{sizer_library_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_library_categories} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_library_left}, wxID_ANY, "Categories"), wxVERTICAL);
    $self->{sizer_library_left}->Add($self->{box_library_categories}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_library_categories} = Wx::ListBox->new($self->{box_library_categories}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["All", "Audio", "Video", "Images", "Documents", "Programs"], 0);
    $self->{box_library_categories}->Add($self->{list_library_categories}, 1, wxALL|wxEXPAND, 4);
    
    $self->{panel_library_right} = Wx::Panel->new($self->{splitter_library}, wxID_ANY);
    
    $self->{sizer_library_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_library_files} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_library_right}, wxID_ANY, "Library Files"), wxVERTICAL);
    $self->{sizer_library_right}->Add($self->{box_library_files}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_library_files} = Wx::ListCtrl->new($self->{box_library_files}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT);
    $self->{box_library_files}->Add($self->{list_library_files}, 1, wxALL|wxEXPAND, 4);
    
    $self->{box_library_controls} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_library}, wxID_ANY, "Sharing / Maintenance"), wxHORIZONTAL);
    $self->{sizer_library_root}->Add($self->{box_library_controls}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_library_hint = Wx::StaticText->new($self->{box_library_controls}->GetStaticBox(), wxID_ANY, "Placeholder controls (rescan, share, etc.)");
    $self->{box_library_controls}->Add($lbl_library_hint, 1, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_library_rescan} = Wx::Button->new($self->{box_library_controls}->GetStaticBox(), wxID_ANY, "Rescan");
    $self->{box_library_controls}->Add($self->{btn_library_rescan}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_library_open_folder} = Wx::Button->new($self->{box_library_controls}->GetStaticBox(), wxID_ANY, "Open Folder");
    $self->{box_library_controls}->Add($self->{btn_library_open_folder}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{page_console} = Wx::Panel->new($self->{nb_top}, wxID_ANY);
    $self->{nb_top}->AddPage($self->{page_console}, "Console");
    
    $self->{sizer_console_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_console} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_console}, wxID_ANY, "Console Output"), wxVERTICAL);
    $self->{sizer_console_root}->Add($self->{box_console}, 1, wxALL|wxEXPAND, 6);
    
    $self->{txt_console_out} = Wx::TextCtrl->new($self->{box_console}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{box_console}->Add($self->{txt_console_out}, 1, wxALL|wxEXPAND, 4);
    
    $self->{box_console_in} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_console}, wxID_ANY, "Command"), wxHORIZONTAL);
    $self->{sizer_console_root}->Add($self->{box_console_in}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{txt_console_in} = Wx::TextCtrl->new($self->{box_console_in}->GetStaticBox(), wxID_ANY, "");
    $self->{box_console_in}->Add($self->{txt_console_in}, 1, wxALL|wxEXPAND, 6);
    
    $self->{btn_console_send} = Wx::Button->new($self->{box_console_in}->GetStaticBox(), wxID_ANY, "Send");
    $self->{box_console_in}->Add($self->{btn_console_send}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{page_logging} = Wx::Panel->new($self->{nb_top}, wxID_ANY);
    $self->{nb_top}->AddPage($self->{page_logging}, "Logging");
    
    $self->{sizer_logging_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{splitter_logging} = Wx::SplitterWindow->new($self->{page_logging}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{splitter_logging}->SetMinimumPaneSize(20);
    $self->{sizer_logging_root}->Add($self->{splitter_logging}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_logging_left} = Wx::Panel->new($self->{splitter_logging}, wxID_ANY);
    
    $self->{sizer_logging_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_log_channels} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_logging_left}, wxID_ANY, "Channels"), wxVERTICAL);
    $self->{sizer_logging_left}->Add($self->{box_log_channels}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_log_channels} = Wx::ListBox->new($self->{box_log_channels}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Info", "Warning", "Error", "Network", "Search"], 0);
    $self->{box_log_channels}->Add($self->{list_log_channels}, 1, wxALL|wxEXPAND, 4);
    
    $self->{panel_logging_right} = Wx::Panel->new($self->{splitter_logging}, wxID_ANY);
    
    $self->{sizer_logging_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_log_view} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_logging_right}, wxID_ANY, "Log View"), wxVERTICAL);
    $self->{sizer_logging_right}->Add($self->{box_log_view}, 1, wxALL|wxEXPAND, 6);
    
    $self->{txt_log_view} = Wx::TextCtrl->new($self->{box_log_view}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{box_log_view}->Add($self->{txt_log_view}, 1, wxALL|wxEXPAND, 4);
    
    $self->{sizer_logging_buttons} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_logging_root}->Add($self->{sizer_logging_buttons}, 0, wxALIGN_RIGHT|wxBOTTOM|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_log_save} = Wx::Button->new($self->{page_logging}, wxID_ANY, "Save...");
    $self->{sizer_logging_buttons}->Add($self->{btn_log_save}, 0, wxALL, 6);
    
    $self->{btn_log_clear} = Wx::Button->new($self->{page_logging}, wxID_ANY, "Clear");
    $self->{sizer_logging_buttons}->Add($self->{btn_log_clear}, 0, wxALL, 6);
    
    $self->{page_new} = Wx::Panel->new($self->{nb_top}, wxID_ANY);
    $self->{nb_top}->AddPage($self->{page_new}, "New \@ Lime");
    
    $self->{sizer_new_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_new_banner} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_new}, wxID_ANY, "New \@ Lime"), wxHORIZONTAL);
    $self->{sizer_new_root}->Add($self->{box_new_banner}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_new_banner = Wx::StaticText->new($self->{box_new_banner}->GetStaticBox(), wxID_ANY, "Announcements, tips, and updates (placeholder)");
    $self->{box_new_banner}->Add($lbl_new_banner, 1, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_new_refresh} = Wx::Button->new($self->{box_new_banner}->GetStaticBox(), wxID_ANY, "Refresh");
    $self->{box_new_banner}->Add($self->{btn_new_refresh}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{splitter_new} = Wx::SplitterWindow->new($self->{page_new}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{splitter_new}->SetMinimumPaneSize(20);
    $self->{sizer_new_root}->Add($self->{splitter_new}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{panel_new_left} = Wx::Panel->new($self->{splitter_new}, wxID_ANY);
    
    $self->{sizer_new_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_new_list} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_new_left}, wxID_ANY, "Items"), wxVERTICAL);
    $self->{sizer_new_left}->Add($self->{box_new_list}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_new_items} = Wx::ListCtrl->new($self->{box_new_list}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT);
    $self->{box_new_list}->Add($self->{list_new_items}, 1, wxALL|wxEXPAND, 4);
    
    $self->{panel_new_right} = Wx::Panel->new($self->{splitter_new}, wxID_ANY);
    
    $self->{sizer_new_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_new_details} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_new_right}, wxID_ANY, "Details"), wxVERTICAL);
    $self->{sizer_new_right}->Add($self->{box_new_details}, 1, wxALL|wxEXPAND, 6);
    
    $self->{txt_new_details} = Wx::TextCtrl->new($self->{box_new_details}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{box_new_details}->Add($self->{txt_new_details}, 1, wxALL|wxEXPAND, 4);
    
    $self->{panel_new_right}->SetSizer($self->{sizer_new_right});
    
    $self->{panel_new_left}->SetSizer($self->{sizer_new_left});
    
    $self->{splitter_new}->SplitVertically($self->{panel_new_left}, $self->{panel_new_right}, );
    
    $self->{page_new}->SetSizer($self->{sizer_new_root});
    
    $self->{panel_logging_right}->SetSizer($self->{sizer_logging_right});
    
    $self->{panel_logging_left}->SetSizer($self->{sizer_logging_left});
    
    $self->{splitter_logging}->SplitVertically($self->{panel_logging_left}, $self->{panel_logging_right}, );
    
    $self->{page_logging}->SetSizer($self->{sizer_logging_root});
    
    $self->{page_console}->SetSizer($self->{sizer_console_root});
    
    $self->{panel_library_right}->SetSizer($self->{sizer_library_right});
    
    $self->{panel_library_left}->SetSizer($self->{sizer_library_left});
    
    $self->{splitter_library}->SplitVertically($self->{panel_library_left}, $self->{panel_library_right}, );
    
    $self->{page_library}->SetSizer($self->{sizer_library_root});
    
    $self->{page_connections}->SetSizer($self->{sizer_connections_root});
    
    $self->{panel_monitor_right}->SetSizer($self->{sizer_monitor_right});
    
    $self->{panel_monitor_left}->SetSizer($self->{sizer_monitor_left});
    
    $self->{splitter_monitor}->SplitVertically($self->{panel_monitor_left}, $self->{panel_monitor_right}, );
    
    $self->{page_monitor}->SetSizer($self->{sizer_monitor_root});
    
    $self->{panel_search_right}->SetSizer($self->{sizer_search_right});
    
    $self->{panel_search_left}->SetSizer($self->{sizer_search_left});
    
    $self->{splitter_search}->SplitVertically($self->{panel_search_left}, $self->{panel_search_right}, );
    
    $self->{page_search}->SetSizer($self->{sizer_search_root});
    
    $self->{panel_main}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade

    # in LimeFrame->new(), after SplitVertically calls:
    $self->{splitter_search}->SetSashPosition(240, 1);
    $self->{splitter_monitor}->SetSashPosition(520, 1);
    $self->{splitter_library}->SetSashPosition(220, 1);
    $self->{splitter_logging}->SetSashPosition(220, 1);
    $self->{splitter_new}->SetSashPosition(360, 1);

    return $self;
}


# end of class LimeFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_lime = LimeFrame->new();

    $self->SetTopWindow($frame_lime);
    $frame_lime->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
