#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Tue Feb  3 21:30:25 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package NetCDFExplorerFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: NetCDFExplorerFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(980, 640));
    $self->SetTitle("NetCDF Explorer (Local)");
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_top} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_top}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_open_netcdf} = Wx::Button->new($self, wxID_ANY, "Open NetCDF\N{U+2026}");
    $self->{sizer_top}->Add($self->{btn_open_netcdf}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_path} = Wx::TextCtrl->new($self, wxID_ANY, "(no file selected)", wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    $self->{sizer_top}->Add($self->{txt_path}, 1, wxEXPAND|wxLEFT, 8);
    
    $self->{splitter_main} = Wx::SplitterWindow->new($self, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxCLIP_CHILDREN|wxSP_LIVE_UPDATE);
    $self->{splitter_main}->SetMinimumPaneSize(20);
    $self->{sizer_root}->Add($self->{splitter_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{panel_left} = Wx::Panel->new($self->{splitter_main}, wxID_ANY);
    
    $self->{sizer_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_files = Wx::StaticText->new($self->{panel_left}, wxID_ANY, "Local files");
    $self->{sizer_left}->Add($lbl_files, 0, wxALL|wxEXPAND, 6);
    
    $self->{list_files} = Wx::ListBox->new($self->{panel_left}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["example1.nc", "example2.nc", "example3.nc"], wxLB_NEEDED_SB|wxLB_SINGLE);
    $self->{list_files}->SetSelection(0);
    $self->{sizer_left}->Add($self->{list_files}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_refresh} = Wx::Button->new($self->{panel_left}, wxID_ANY, "Refresh list");
    $self->{sizer_left}->Add($self->{btn_refresh}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{notebook_main} = Wx::Notebook->new($self->{splitter_main}, wxID_ANY);
    
    $self->{tab_summary} = Wx::Panel->new($self->{notebook_main}, wxID_ANY);
    $self->{notebook_main}->AddPage($self->{tab_summary}, "Summary");
    
    $self->{sizer_summary} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_summary_hint = Wx::StaticText->new($self->{tab_summary}, wxID_ANY, "Summary view (placeholder)");
    $self->{sizer_summary}->Add($lbl_summary_hint, 0, wxALL, 10);
    
    $self->{txt_summary} = Wx::TextCtrl->new($self->{tab_summary}, wxID_ANY, "Select a NetCDF file to populate metadata here.", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_summary}->Add($self->{txt_summary}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 10);
    
    $self->{tab_dimensions} = Wx::Panel->new($self->{notebook_main}, wxID_ANY);
    $self->{notebook_main}->AddPage($self->{tab_dimensions}, "Dimensions");
    
    $self->{sizer_dims} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_dims_hint = Wx::StaticText->new($self->{tab_dimensions}, wxID_ANY, "Dimensions (placeholder)");
    $self->{sizer_dims}->Add($lbl_dims_hint, 0, wxALL, 10);
    
    $self->{txt_dims} = Wx::TextCtrl->new($self->{tab_dimensions}, wxID_ANY, "Will list dimensions and sizes here.", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_dims}->Add($self->{txt_dims}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 10);
    
    $self->{tab_variables} = Wx::Panel->new($self->{notebook_main}, wxID_ANY);
    $self->{notebook_main}->AddPage($self->{tab_variables}, "Variables");
    
    $self->{sizer_vars} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_vars_hint = Wx::StaticText->new($self->{tab_variables}, wxID_ANY, "Variables (placeholder)");
    $self->{sizer_vars}->Add($lbl_vars_hint, 0, wxALL, 10);
    
    $self->{txt_vars} = Wx::TextCtrl->new($self->{tab_variables}, wxID_ANY, "Will list variables/attributes here.", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_vars}->Add($self->{txt_vars}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 10);
    
    my $lbl_status = Wx::StaticText->new($self, wxID_ANY, "Ready. Open a local NetCDF file to begin.");
    $self->{sizer_root}->Add($lbl_status, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{tab_variables}->SetSizer($self->{sizer_vars});
    
    $self->{tab_dimensions}->SetSizer($self->{sizer_dims});
    
    $self->{tab_summary}->SetSizer($self->{sizer_summary});
    
    $self->{panel_left}->SetSizer($self->{sizer_left});
    
    $self->{splitter_main}->SplitVertically($self->{panel_left}, $self->{notebook_main}, );
    
    $self->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class NetCDFExplorerFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_1 = NetCDFExplorerFrame->new();

    $self->SetTopWindow($frame_1);
    $frame_1->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
