#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Sat Feb 14 01:30:33 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package AVImarkDenseFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: AVImarkDenseFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1320, 860));
    $self->SetTitle("AVImark Dense Sample (wxGlade/wxPerl) - 3 Tables");
    
    

    # Menu Bar

    $self->{menubar_main} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $self->{mnu_file} = Wx::Menu->new();
    $self->{mnu_file_open} = $self->{mnu_file}->Append(wxID_ANY, "Open...", "");
    $self->{mnu_file_print} = $self->{mnu_file}->Append(wxID_ANY, "Print...", "");
    $self->{mnu_file_sep1} = $self->{mnu_file}->Append(wxID_ANY, "---", "");
    $self->{mnu_file_exit} = $self->{mnu_file}->Append(wxID_ANY, "Exit", "");
    $self->{menubar_main}->Append($self->{mnu_file}, "File");
    $self->{mnu_patients} = Wx::Menu->new();
    $self->{mnu_pat_new_client} = $self->{mnu_patients}->Append(wxID_ANY, "New Client", "");
    $self->{mnu_pat_new_patient} = $self->{mnu_patients}->Append(wxID_ANY, "New Patient", "");
    $self->{mnu_pat_merge} = $self->{mnu_patients}->Append(wxID_ANY, "Merge...", "");
    $self->{menubar_main}->Append($self->{mnu_patients}, "Patients");
    $self->{mnu_schedule} = Wx::Menu->new();
    $self->{mnu_sch_new_appt} = $self->{mnu_schedule}->Append(wxID_ANY, "New Appointment", "");
    $self->{mnu_sch_checkin} = $self->{mnu_schedule}->Append(wxID_ANY, "Check-in", "");
    $self->{mnu_sch_whiteboard} = $self->{mnu_schedule}->Append(wxID_ANY, "Whiteboard", "");
    $self->{menubar_main}->Append($self->{mnu_schedule}, "Schedule");
    $self->{mnu_billing} = Wx::Menu->new();
    $self->{mnu_bill_new_invoice} = $self->{mnu_billing}->Append(wxID_ANY, "New Invoice", "");
    $self->{mnu_bill_payment} = $self->{mnu_billing}->Append(wxID_ANY, "Payment", "");
    $self->{mnu_bill_refund} = $self->{mnu_billing}->Append(wxID_ANY, "Refund", "");
    $self->{menubar_main}->Append($self->{mnu_billing}, "Billing");
    $self->{mnu_tools} = Wx::Menu->new();
    $self->{mnu_tools_options} = $self->{mnu_tools}->Append(wxID_ANY, "Options...", "");
    $self->{mnu_tools_reminders} = $self->{mnu_tools}->Append(wxID_ANY, "Reminders", "");
    $self->{mnu_tools_reports} = $self->{mnu_tools}->Append(wxID_ANY, "Reports", "");
    $self->{menubar_main}->Append($self->{mnu_tools}, "Tools");
    $self->SetMenuBar($self->{menubar_main});
    
    # Menu Bar end

    
    $self->{panel_root} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_top_strip} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_top_strip}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_clinic = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "Clinic:");
    $self->{sizer_top_strip}->Add($lbl_clinic, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_clinic} = Wx::Choice->new($self->{panel_root}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Main", "Satellite", "Mobile"], );
    $self->{choice_clinic}->SetSelection(0);
    $self->{sizer_top_strip}->Add($self->{choice_clinic}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    my $lbl_user = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "User:");
    $self->{sizer_top_strip}->Add($lbl_user, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    my $txt_user = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "doctor1");
    $self->{sizer_top_strip}->Add($txt_user, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_top_strip}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_offline} = Wx::CheckBox->new($self->{panel_root}, wxID_ANY, "Offline mode");
    $self->{sizer_top_strip}->Add($self->{chk_offline}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{gauge_bg} = Wx::Gauge->new($self->{panel_root}, wxID_ANY, 100, wxDefaultPosition, wxDefaultSize, 0);
    $self->{gauge_bg}->SetMinSize(Wx::Size->new(140,16));
    $self->{sizer_top_strip}->Add($self->{gauge_bg}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{split_main} = Wx::SplitterWindow->new($self->{panel_root}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_main}->SetMinimumPaneSize(20);
    $self->{sizer_root}->Add($self->{split_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{panel_left} = Wx::Panel->new($self->{split_main}, wxID_ANY);
    
    $self->{sizer_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_find} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_left}, wxID_ANY, "Find Client / Patient"), wxVERTICAL);
    $self->{sizer_left}->Add($self->{box_find}, 0, wxALL|wxEXPAND, 6);
    
    $self->{txt_find} = Wx::TextCtrl->new($self->{box_find}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_find}->SetMinSize(Wx::Size->new(-1,28));
    $self->{box_find}->Add($self->{txt_find}, 0, wxALL|wxEXPAND, 6);
    
    $self->{sizer_find_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_find}->Add($self->{sizer_find_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_find} = Wx::Button->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Find");
    $self->{sizer_find_btns}->Add($self->{btn_find}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_recent} = Wx::Button->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Recent");
    $self->{sizer_find_btns}->Add($self->{btn_recent}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_find_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_new} = Wx::Button->new($self->{box_find}->GetStaticBox(), wxID_ANY, "New...");
    $self->{sizer_find_btns}->Add($self->{btn_new}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_quick_filters} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_find}->Add($self->{sizer_quick_filters}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{chk_active} = Wx::CheckBox->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Active");
    $self->{sizer_quick_filters}->Add($self->{chk_active}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_balance} = Wx::CheckBox->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Has balance");
    $self->{sizer_quick_filters}->Add($self->{chk_balance}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{chk_alerts} = Wx::CheckBox->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Alerts");
    $self->{sizer_quick_filters}->Add($self->{chk_alerts}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{box_nav} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_left}, wxID_ANY, "Navigation"), wxVERTICAL);
    $self->{sizer_left}->Add($self->{box_nav}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{tree_nav} = Wx::TreeCtrl->new($self->{box_nav}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT);
    $self->{box_nav}->Add($self->{tree_nav}, 1, wxALL|wxEXPAND, 6);
    
    $self->{box_patients} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_left}, wxID_ANY, "Clients / Patients"), wxVERTICAL);
    $self->{sizer_left}->Add($self->{box_patients}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{list_clients_patients} = Wx::ListCtrl->new($self->{box_patients}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_patients}->Add($self->{list_clients_patients}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_right} = Wx::Panel->new($self->{split_main}, wxID_ANY);
    
    $self->{sizer_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_header} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_right}, wxID_ANY, "Context"), wxHORIZONTAL);
    $self->{sizer_right}->Add($self->{box_header}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_ctx1 = Wx::StaticText->new($self->{box_header}->GetStaticBox(), wxID_ANY, "Client:");
    $self->{box_header}->Add($lbl_ctx1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{txt_client} = Wx::TextCtrl->new($self->{box_header}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_client}->SetMinSize(Wx::Size->new(-1,26));
    $self->{box_header}->Add($self->{txt_client}, 1, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_ctx2 = Wx::StaticText->new($self->{box_header}->GetStaticBox(), wxID_ANY, "Patient:");
    $self->{box_header}->Add($lbl_ctx2, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{txt_patient} = Wx::TextCtrl->new($self->{box_header}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_patient}->SetMinSize(Wx::Size->new(-1,26));
    $self->{box_header}->Add($self->{txt_patient}, 1, wxEXPAND|wxLEFT, 6);
    
    $self->{nb_bottom} = Wx::Notebook->new($self->{panel_right}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM);
    $self->{sizer_right}->Add($self->{nb_bottom}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{page_patients} = Wx::Panel->new($self->{nb_bottom}, wxID_ANY);
    $self->{nb_bottom}->AddPage($self->{page_patients}, "Patients");
    
    $self->{sizer_patients} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_patients_inner} = Wx::Notebook->new($self->{page_patients}, wxID_ANY);
    $self->{sizer_patients}->Add($self->{nb_patients_inner}, 1, wxALL|wxEXPAND, 6);
    
    $self->{pat_overview} = Wx::Panel->new($self->{nb_patients_inner}, wxID_ANY);
    $self->{nb_patients_inner}->AddPage($self->{pat_overview}, "Overview");
    
    $self->{sizer_pat_overview} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_overview} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{sizer_pat_overview}->Add($self->{grid_overview}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_species = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "Species");
    $self->{grid_overview}->Add($lbl_species, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_species} = Wx::Choice->new($self->{pat_overview}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Canine", "Feline", "Avian", "Exotic"], );
    $self->{choice_species}->SetSelection(0);
    $self->{grid_overview}->Add($self->{choice_species}, 1, wxEXPAND, 0);
    
    my $lbl_sex = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "Sex");
    $self->{grid_overview}->Add($lbl_sex, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_sex} = Wx::Choice->new($self->{pat_overview}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["M", "F", "Neutered", "Spayed"], );
    $self->{choice_sex}->SetSelection(0);
    $self->{grid_overview}->Add($self->{choice_sex}, 1, wxEXPAND, 0);
    
    my $lbl_dob = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "DOB");
    $self->{grid_overview}->Add($lbl_dob, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dob} = Wx::TextCtrl->new($self->{pat_overview}, wxID_ANY, "");
    $self->{grid_overview}->Add($self->{txt_dob}, 1, wxEXPAND, 0);
    
    my $lbl_weight = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "Weight");
    $self->{grid_overview}->Add($lbl_weight, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_weight} = Wx::TextCtrl->new($self->{pat_overview}, wxID_ANY, "");
    $self->{grid_overview}->Add($self->{txt_weight}, 1, wxEXPAND, 0);
    
    my $lbl_alert = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "Alerts");
    $self->{grid_overview}->Add($lbl_alert, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_aggressive} = Wx::CheckBox->new($self->{pat_overview}, wxID_ANY, "Aggressive");
    $self->{grid_overview}->Add($self->{chk_aggressive}, 1, wxEXPAND, 0);
    
    my $lbl_flags = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "Flags");
    $self->{grid_overview}->Add($lbl_flags, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_flags} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{grid_overview}->Add($self->{sizer_flags}, 1, wxEXPAND, 0);
    
    $self->{chk_microchip} = Wx::CheckBox->new($self->{pat_overview}, wxID_ANY, "Microchip");
    $self->{sizer_flags}->Add($self->{chk_microchip}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_vip} = Wx::CheckBox->new($self->{pat_overview}, wxID_ANY, "VIP");
    $self->{sizer_flags}->Add($self->{chk_vip}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{chk_deceased} = Wx::CheckBox->new($self->{pat_overview}, wxID_ANY, "Deceased");
    $self->{sizer_flags}->Add($self->{chk_deceased}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{box_notes} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{pat_overview}, wxID_ANY, "Client/Patient Notes"), wxVERTICAL);
    $self->{sizer_pat_overview}->Add($self->{box_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{txt_notes} = Wx::TextCtrl->new($self->{box_notes}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_notes}->Add($self->{txt_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{pat_medical} = Wx::Panel->new($self->{nb_patients_inner}, wxID_ANY);
    $self->{nb_patients_inner}->AddPage($self->{pat_medical}, "Medical");
    
    $self->{sizer_pat_med} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_med_flags} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{pat_medical}, wxID_ANY, "Medical Flags"), wxHORIZONTAL);
    $self->{sizer_pat_med}->Add($self->{box_med_flags}, 0, wxALL|wxEXPAND, 6);
    
    $self->{chk_allergy} = Wx::CheckBox->new($self->{box_med_flags}->GetStaticBox(), wxID_ANY, "Allergy");
    $self->{box_med_flags}->Add($self->{chk_allergy}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{chk_chronic} = Wx::CheckBox->new($self->{box_med_flags}->GetStaticBox(), wxID_ANY, "Chronic");
    $self->{box_med_flags}->Add($self->{chk_chronic}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{chk_anesthesia} = Wx::CheckBox->new($self->{box_med_flags}->GetStaticBox(), wxID_ANY, "Anesthesia risk");
    $self->{box_med_flags}->Add($self->{chk_anesthesia}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_med_flags}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_add_problem} = Wx::Button->new($self->{box_med_flags}->GetStaticBox(), wxID_ANY, "Add Problem...");
    $self->{box_med_flags}->Add($self->{btn_add_problem}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_med_history} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{pat_medical}, wxID_ANY, "History / SOAP (text)"), wxVERTICAL);
    $self->{sizer_pat_med}->Add($self->{box_med_history}, 1, wxALL|wxEXPAND, 6);
    
    $self->{txt_soap} = Wx::TextCtrl->new($self->{box_med_history}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_med_history}->Add($self->{txt_soap}, 1, wxALL|wxEXPAND, 6);
    
    $self->{pat_reminders} = Wx::Panel->new($self->{nb_patients_inner}, wxID_ANY);
    $self->{nb_patients_inner}->AddPage($self->{pat_reminders}, "Reminders");
    
    $self->{sizer_pat_rem} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_rem} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{pat_reminders}, wxID_ANY, "Reminders (dense controls)"), wxVERTICAL);
    $self->{sizer_pat_rem}->Add($self->{box_rem}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_rem} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_rem}->Add($self->{grid_rem}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_r1 = Wx::StaticText->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Rabies due");
    $self->{grid_rem}->Add($lbl_r1, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rabies} = Wx::TextCtrl->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rem}->Add($self->{txt_rabies}, 1, wxEXPAND, 0);
    
    my $lbl_r2 = Wx::StaticText->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Wellness due");
    $self->{grid_rem}->Add($lbl_r2, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_wellness} = Wx::TextCtrl->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rem}->Add($self->{txt_wellness}, 1, wxEXPAND, 0);
    
    $self->{sizer_rem_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_rem}->Add($self->{sizer_rem_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_gen_postcard} = Wx::Button->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Postcard");
    $self->{sizer_rem_btns}->Add($self->{btn_gen_postcard}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_gen_email} = Wx::Button->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Email");
    $self->{sizer_rem_btns}->Add($self->{btn_gen_email}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_gen_sms} = Wx::Button->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "SMS");
    $self->{sizer_rem_btns}->Add($self->{btn_gen_sms}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_rem_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_rem_save} = Wx::Button->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Save");
    $self->{sizer_rem_btns}->Add($self->{btn_rem_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rem_log} = Wx::TextCtrl->new($self->{pat_reminders}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_pat_rem}->Add($self->{txt_rem_log}, 1, wxALL|wxEXPAND, 6);
    
    $self->{pat_docs} = Wx::Panel->new($self->{nb_patients_inner}, wxID_ANY);
    $self->{nb_patients_inner}->AddPage($self->{pat_docs}, "Documents");
    
    $self->{sizer_pat_docs} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_docs_toolbar} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_pat_docs}->Add($self->{sizer_docs_toolbar}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_doc_add} = Wx::Button->new($self->{pat_docs}, wxID_ANY, "Add...");
    $self->{sizer_docs_toolbar}->Add($self->{btn_doc_add}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_doc_scan} = Wx::Button->new($self->{pat_docs}, wxID_ANY, "Scan");
    $self->{sizer_docs_toolbar}->Add($self->{btn_doc_scan}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_doc_print} = Wx::Button->new($self->{pat_docs}, wxID_ANY, "Print");
    $self->{sizer_docs_toolbar}->Add($self->{btn_doc_print}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_docs_toolbar}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_doc_private} = Wx::CheckBox->new($self->{pat_docs}, wxID_ANY, "Private");
    $self->{sizer_docs_toolbar}->Add($self->{chk_doc_private}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_doc_preview} = Wx::TextCtrl->new($self->{pat_docs}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_pat_docs}->Add($self->{txt_doc_preview}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_schedule} = Wx::Panel->new($self->{nb_bottom}, wxID_ANY);
    $self->{nb_bottom}->AddPage($self->{page_schedule}, "Schedule");
    
    $self->{sizer_schedule} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_sched_filters} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_schedule}, wxID_ANY, "Schedule Controls"), wxHORIZONTAL);
    $self->{sizer_schedule}->Add($self->{box_sched_filters}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_date = Wx::StaticText->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Date");
    $self->{box_sched_filters}->Add($lbl_date, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{txt_sched_date} = Wx::TextCtrl->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_sched_date}->SetMinSize(Wx::Size->new(110,26));
    $self->{box_sched_filters}->Add($self->{txt_sched_date}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_sched_pick} = Wx::Button->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "...");
    $self->{btn_sched_pick}->SetMinSize(Wx::Size->new(28,22));
    $self->{box_sched_filters}->Add($self->{btn_sched_pick}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{chk_sched_show_checkedin} = Wx::CheckBox->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Show checked-in");
    $self->{box_sched_filters}->Add($self->{chk_sched_show_checkedin}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{chk_sched_show_canceled} = Wx::CheckBox->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Show canceled");
    $self->{box_sched_filters}->Add($self->{chk_sched_show_canceled}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{box_sched_filters}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_sched_new} = Wx::Button->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "New Appt");
    $self->{box_sched_filters}->Add($self->{btn_sched_new}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_schedule} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_schedule}, wxID_ANY, "Appointments"), wxVERTICAL);
    $self->{sizer_schedule}->Add($self->{box_schedule}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_schedule} = Wx::ListCtrl->new($self->{box_schedule}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_schedule}->Add($self->{list_schedule}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sizer_sched_bottom} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_schedule}->Add($self->{sizer_sched_bottom}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_checkin} = Wx::Button->new($self->{page_schedule}, wxID_ANY, "Check-in");
    $self->{sizer_sched_bottom}->Add($self->{btn_checkin}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_checkout} = Wx::Button->new($self->{page_schedule}, wxID_ANY, "Checkout");
    $self->{sizer_sched_bottom}->Add($self->{btn_checkout}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_whiteboard} = Wx::Button->new($self->{page_schedule}, wxID_ANY, "Whiteboard");
    $self->{sizer_sched_bottom}->Add($self->{btn_whiteboard}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_sched_bottom}->Add(1, 1, 1, wxEXPAND, 0);
    
    my $lbl_sched_status = Wx::StaticText->new($self->{page_schedule}, wxID_ANY, "3 rooms \N{U+2022} 1 doctor \N{U+2022} 0 conflicts");
    $self->{sizer_sched_bottom}->Add($lbl_sched_status, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{page_billing} = Wx::Panel->new($self->{nb_bottom}, wxID_ANY);
    $self->{nb_bottom}->AddPage($self->{page_billing}, "Billing");
    
    $self->{sizer_billing} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_bill_controls} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_billing}, wxID_ANY, "Invoice / Posting"), wxVERTICAL);
    $self->{sizer_billing}->Add($self->{box_bill_controls}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_bill} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{box_bill_controls}->Add($self->{grid_bill}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_inv = Wx::StaticText->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Invoice #");
    $self->{grid_bill}->Add($lbl_inv, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_invoice} = Wx::TextCtrl->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_bill}->Add($self->{txt_invoice}, 1, wxEXPAND, 0);
    
    my $lbl_loc = Wx::StaticText->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Location");
    $self->{grid_bill}->Add($lbl_loc, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_bill_loc} = Wx::Choice->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Main", "Satellite"], );
    $self->{choice_bill_loc}->SetSelection(0);
    $self->{grid_bill}->Add($self->{choice_bill_loc}, 1, wxEXPAND, 0);
    
    my $lbl_code = Wx::StaticText->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Code");
    $self->{grid_bill}->Add($lbl_code, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_post_code} = Wx::TextCtrl->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_bill}->Add($self->{txt_post_code}, 1, wxEXPAND, 0);
    
    my $lbl_qty = Wx::StaticText->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Qty");
    $self->{grid_bill}->Add($lbl_qty, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_qty} = Wx::TextCtrl->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_bill}->Add($self->{txt_qty}, 1, wxEXPAND, 0);
    
    my $lbl_price = Wx::StaticText->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Price");
    $self->{grid_bill}->Add($lbl_price, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_price} = Wx::TextCtrl->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_bill}->Add($self->{txt_price}, 1, wxEXPAND, 0);
    
    my $lbl_tax = Wx::StaticText->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Tax");
    $self->{grid_bill}->Add($lbl_tax, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_tax} = Wx::CheckBox->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Taxable");
    $self->{grid_bill}->Add($self->{chk_tax}, 1, wxEXPAND, 0);
    
    $self->{sizer_bill_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_bill_controls}->Add($self->{sizer_bill_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_post} = Wx::Button->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Post");
    $self->{sizer_bill_btns}->Add($self->{btn_post}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_payment} = Wx::Button->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Payment");
    $self->{sizer_bill_btns}->Add($self->{btn_payment}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_refund} = Wx::Button->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Refund");
    $self->{sizer_bill_btns}->Add($self->{btn_refund}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_bill_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    my $lbl_total = Wx::StaticText->new($self->{box_bill_controls}->GetStaticBox(), wxID_ANY, "Total: \$0.00");
    $self->{sizer_bill_btns}->Add($lbl_total, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_ledger} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_billing}, wxID_ANY, "Ledger"), wxVERTICAL);
    $self->{sizer_billing}->Add($self->{box_ledger}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_ledger} = Wx::ListCtrl->new($self->{box_ledger}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_ledger}->Add($self->{list_ledger}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_config} = Wx::Panel->new($self->{nb_bottom}, wxID_ANY);
    $self->{nb_bottom}->AddPage($self->{page_config}, "Config");
    
    $self->{sizer_config} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_cfg} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_config}, wxID_ANY, "Options"), wxVERTICAL);
    $self->{sizer_config}->Add($self->{box_cfg}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_cfg} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{box_cfg}->Add($self->{grid_cfg}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_db = Wx::StaticText->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "Database");
    $self->{grid_cfg}->Add($lbl_db, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_db} = Wx::TextCtrl->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_cfg}->Add($self->{txt_db}, 1, wxEXPAND, 0);
    
    my $lbl_server = Wx::StaticText->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "Server");
    $self->{grid_cfg}->Add($lbl_server, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_server} = Wx::TextCtrl->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_cfg}->Add($self->{txt_server}, 1, wxEXPAND, 0);
    
    my $lbl_prn = Wx::StaticText->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "Default printer");
    $self->{grid_cfg}->Add($lbl_prn, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_prn} = Wx::Choice->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Front Desk", "Treatment", "Lab"], );
    $self->{choice_prn}->SetSelection(0);
    $self->{grid_cfg}->Add($self->{choice_prn}, 1, wxEXPAND, 0);
    
    $self->{box_cfg_flags} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "Behavior"), wxHORIZONTAL);
    $self->{box_cfg}->Add($self->{box_cfg_flags}, 0, wxALL|wxEXPAND, 6);
    
    $self->{chk_autosave} = Wx::CheckBox->new($self->{box_cfg_flags}->GetStaticBox(), wxID_ANY, "Autosave");
    $self->{box_cfg_flags}->Add($self->{chk_autosave}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{chk_confirm_posts} = Wx::CheckBox->new($self->{box_cfg_flags}->GetStaticBox(), wxID_ANY, "Confirm posts");
    $self->{box_cfg_flags}->Add($self->{chk_confirm_posts}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{chk_keyboard_mode} = Wx::CheckBox->new($self->{box_cfg_flags}->GetStaticBox(), wxID_ANY, "Keyboard mode");
    $self->{box_cfg_flags}->Add($self->{chk_keyboard_mode}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{sizer_cfg_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_cfg}->Add($self->{sizer_cfg_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_cfg_test} = Wx::Button->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "Test");
    $self->{sizer_cfg_btns}->Add($self->{btn_cfg_test}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_cfg_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_cfg_apply} = Wx::Button->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "Apply");
    $self->{sizer_cfg_btns}->Add($self->{btn_cfg_apply}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_cfg_ok} = Wx::Button->new($self->{box_cfg}->GetStaticBox(), wxID_ANY, "OK");
    $self->{sizer_cfg_btns}->Add($self->{btn_cfg_ok}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{txt_cfg_log} = Wx::TextCtrl->new($self->{page_config}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_config}->Add($self->{txt_cfg_log}, 1, wxALL|wxEXPAND, 6);
    
    my $lbl_status = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "F1 Help \N{U+2022} F2 Find \N{U+2022} F3 New \N{U+2022} F6 Schedule \N{U+2022} F9 Billing \N{U+2022} Esc Close");
    $self->{sizer_root}->Add($lbl_status, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{grid_cfg}->AddGrowableCol(1);
    
    $self->{page_config}->SetSizer($self->{sizer_config});
    
    $self->{grid_bill}->AddGrowableCol(3);
    
    $self->{page_billing}->SetSizer($self->{sizer_billing});
    
    $self->{page_schedule}->SetSizer($self->{sizer_schedule});
    
    $self->{pat_docs}->SetSizer($self->{sizer_pat_docs});
    
    $self->{grid_rem}->AddGrowableCol(1);
    
    $self->{pat_reminders}->SetSizer($self->{sizer_pat_rem});
    
    $self->{pat_medical}->SetSizer($self->{sizer_pat_med});
    
    $self->{grid_overview}->AddGrowableCol(3);
    
    $self->{pat_overview}->SetSizer($self->{sizer_pat_overview});
    
    $self->{page_patients}->SetSizer($self->{sizer_patients});
    
    $self->{panel_right}->SetSizer($self->{sizer_right});
    
    $self->{panel_left}->SetSizer($self->{sizer_left});
    
    $self->{split_main}->SplitVertically($self->{panel_left}, $self->{panel_right}, );
    
    $self->{panel_root}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class AVImarkDenseFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_avimark = AVImarkDenseFrame->new();

    $self->SetTopWindow($frame_avimark);
    $frame_avimark->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
