#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Sat Feb 14 01:58:25 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package VetCRMDenseFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: VetCRMDenseFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1400, 920));
    $self->SetTitle("Vet CRM Dense Centers Sample (wxGlade/wxPerl)");
    
    $self->{panel_root} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_global} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_root}, wxID_ANY, "Global"), wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{box_global}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_site = Wx::StaticText->new($self->{box_global}->GetStaticBox(), wxID_ANY, "Site");
    $self->{box_global}->Add($lbl_site, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{choice_site} = Wx::Choice->new($self->{box_global}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Main Hospital", "Satellite Clinic", "Mobile"], );
    $self->{choice_site}->SetSelection(0);
    $self->{box_global}->Add($self->{choice_site}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_user = Wx::StaticText->new($self->{box_global}->GetStaticBox(), wxID_ANY, "User");
    $self->{box_global}->Add($lbl_user, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    my $txt_user = Wx::StaticText->new($self->{box_global}->GetStaticBox(), wxID_ANY, "doctor1");
    $self->{box_global}->Add($txt_user, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{chk_offline} = Wx::CheckBox->new($self->{box_global}->GetStaticBox(), wxID_ANY, "Offline");
    $self->{box_global}->Add($self->{chk_offline}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{box_global}->Add(1, 1, 1, wxEXPAND, 0);
    
    my $lbl_bg = Wx::StaticText->new($self->{box_global}->GetStaticBox(), wxID_ANY, "Background");
    $self->{box_global}->Add($lbl_bg, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{gauge_bg} = Wx::Gauge->new($self->{box_global}->GetStaticBox(), wxID_ANY, 100, wxDefaultPosition, wxDefaultSize, 0);
    $self->{gauge_bg}->SetMinSize(Wx::Size->new(180,16));
    $self->{box_global}->Add($self->{gauge_bg}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{nb_centers} = Wx::Notebook->new($self->{panel_root}, wxID_ANY);
    $self->{sizer_root}->Add($self->{nb_centers}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{tab_main_screen} = Wx::Panel->new($self->{nb_centers}, wxID_ANY);
    $self->{nb_centers}->AddPage($self->{tab_main_screen}, "Main Screen");
    
    $self->{sizer_main_tab} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_main_header} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{tab_main_screen}, wxID_ANY, "Patient / Owner Context"), wxVERTICAL);
    $self->{sizer_main_tab}->Add($self->{box_main_header}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_main_header} = Wx::FlexGridSizer->new(0, 6, 6, 8);
    $self->{box_main_header}->Add($self->{grid_main_header}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_owner = Wx::StaticText->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Owner");
    $self->{grid_main_header}->Add($lbl_owner, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_owner} = Wx::TextCtrl->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_main_header}->Add($self->{txt_owner}, 1, wxEXPAND, 0);
    
    my $lbl_patient = Wx::StaticText->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Patient");
    $self->{grid_main_header}->Add($lbl_patient, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_patient} = Wx::TextCtrl->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_main_header}->Add($self->{txt_patient}, 1, wxEXPAND, 0);
    
    my $lbl_status = Wx::StaticText->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Status");
    $self->{grid_main_header}->Add($lbl_status, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_patient_status} = Wx::Choice->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Active", "Inactive", "Deceased", "Do Not Contact"], );
    $self->{choice_patient_status}->SetSelection(0);
    $self->{grid_main_header}->Add($self->{choice_patient_status}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_alerts = Wx::StaticText->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Alerts");
    $self->{grid_main_header}->Add($lbl_alerts, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_alerts} = Wx::TextCtrl->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_main_header}->Add($self->{txt_alerts}, 1, wxEXPAND, 0);
    
    $self->{chk_rabies_hold} = Wx::CheckBox->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Rabies Hold");
    $self->{grid_main_header}->Add($self->{chk_rabies_hold}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_aggressive} = Wx::CheckBox->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Aggressive");
    $self->{grid_main_header}->Add($self->{chk_aggressive}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_allergy} = Wx::CheckBox->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Allergy");
    $self->{grid_main_header}->Add($self->{chk_allergy}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_anesthesia_risk} = Wx::CheckBox->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Anesthesia Risk");
    $self->{grid_main_header}->Add($self->{chk_anesthesia_risk}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{row_main_header_buttons} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_main_header}->Add($self->{row_main_header_buttons}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_checkin} = Wx::Button->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Check-In");
    $self->{row_main_header_buttons}->Add($self->{btn_checkin}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_checkout} = Wx::Button->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Check-Out");
    $self->{row_main_header_buttons}->Add($self->{btn_checkout}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_new_appt} = Wx::Button->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "New Appt");
    $self->{row_main_header_buttons}->Add($self->{btn_new_appt}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_invoice} = Wx::Button->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Invoice");
    $self->{row_main_header_buttons}->Add($self->{btn_invoice}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{row_main_header_buttons}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{txt_global_find} = Wx::TextCtrl->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_global_find}->SetMinSize(Wx::Size->new(260,-1));
    $self->{row_main_header_buttons}->Add($self->{txt_global_find}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_find} = Wx::Button->new($self->{box_main_header}->GetStaticBox(), wxID_ANY, "Find");
    $self->{row_main_header_buttons}->Add($self->{btn_find}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{split_main} = Wx::SplitterWindow->new($self->{tab_main_screen}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_main}->SetMinimumPaneSize(20);
    $self->{sizer_main_tab}->Add($self->{split_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{panel_main_left} = Wx::Panel->new($self->{split_main}, wxID_ANY);
    
    $self->{sizer_main_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_left_filter} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_main_left}, wxID_ANY, "Queue / Filters"), wxHORIZONTAL);
    $self->{sizer_main_left}->Add($self->{box_left_filter}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_queue = Wx::StaticText->new($self->{box_left_filter}->GetStaticBox(), wxID_ANY, "Queue");
    $self->{box_left_filter}->Add($lbl_queue, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{choice_queue} = Wx::Choice->new($self->{box_left_filter}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Today", "Checked-In", "Inpatient", "Surgery", "Call Backs"], );
    $self->{choice_queue}->SetSelection(0);
    $self->{box_left_filter}->Add($self->{choice_queue}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_filter = Wx::StaticText->new($self->{box_left_filter}->GetStaticBox(), wxID_ANY, "Filter");
    $self->{box_left_filter}->Add($lbl_filter, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{txt_left_filter} = Wx::TextCtrl->new($self->{box_left_filter}->GetStaticBox(), wxID_ANY, "");
    $self->{box_left_filter}->Add($self->{txt_left_filter}, 1, wxEXPAND|wxLEFT, 6);
    
    $self->{btn_left_clear} = Wx::Button->new($self->{box_left_filter}->GetStaticBox(), wxID_ANY, "Clear");
    $self->{box_left_filter}->Add($self->{btn_left_clear}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_patients} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_main_left}, wxID_ANY, "Patients / Queue"), wxVERTICAL);
    $self->{sizer_main_left}->Add($self->{box_patients}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{list_patients} = Wx::ListCtrl->new($self->{box_patients}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_patients}->Add($self->{list_patients}, 1, wxALL|wxEXPAND, 6);
    
    $self->{box_visits} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_main_left}, wxID_ANY, "Visits / Encounters"), wxVERTICAL);
    $self->{sizer_main_left}->Add($self->{box_visits}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{list_visits} = Wx::ListCtrl->new($self->{box_visits}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_visits}->Add($self->{list_visits}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_main_right} = Wx::Panel->new($self->{split_main}, wxID_ANY);
    
    $self->{sizer_main_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_patient_workspace} = Wx::Notebook->new($self->{panel_main_right}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM);
    $self->{sizer_main_right}->Add($self->{nb_patient_workspace}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_overview} = Wx::Panel->new($self->{nb_patient_workspace}, wxID_ANY);
    $self->{nb_patient_workspace}->AddPage($self->{page_overview}, "Overview");
    
    $self->{sizer_overview} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_overview_1} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_overview}, wxID_ANY, "Vitals / Flags / Billing"), wxVERTICAL);
    $self->{sizer_overview}->Add($self->{box_overview_1}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_vitals} = Wx::FlexGridSizer->new(0, 8, 6, 8);
    $self->{box_overview_1}->Add($self->{grid_vitals}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_wt = Wx::StaticText->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "Wt");
    $self->{grid_vitals}->Add($lbl_wt, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_wt} = Wx::TextCtrl->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_wt}->SetMinSize(Wx::Size->new(70,-1));
    $self->{grid_vitals}->Add($self->{txt_wt}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_temp = Wx::StaticText->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "Temp");
    $self->{grid_vitals}->Add($lbl_temp, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_temp} = Wx::TextCtrl->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_temp}->SetMinSize(Wx::Size->new(70,-1));
    $self->{grid_vitals}->Add($self->{txt_temp}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_hr = Wx::StaticText->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "HR");
    $self->{grid_vitals}->Add($lbl_hr, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_hr} = Wx::TextCtrl->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_hr}->SetMinSize(Wx::Size->new(70,-1));
    $self->{grid_vitals}->Add($self->{txt_hr}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_rr = Wx::StaticText->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "RR");
    $self->{grid_vitals}->Add($lbl_rr, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rr} = Wx::TextCtrl->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_rr}->SetMinSize(Wx::Size->new(70,-1));
    $self->{grid_vitals}->Add($self->{txt_rr}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_paid} = Wx::CheckBox->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "Paid");
    $self->{grid_vitals}->Add($self->{chk_paid}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_estimate_signed} = Wx::CheckBox->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "Estimate Signed");
    $self->{grid_vitals}->Add($self->{chk_estimate_signed}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_iso} = Wx::CheckBox->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "Isolation");
    $self->{grid_vitals}->Add($self->{chk_iso}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_dnr} = Wx::CheckBox->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "DNR");
    $self->{grid_vitals}->Add($self->{chk_dnr}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_triage = Wx::StaticText->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, "Triage");
    $self->{grid_vitals}->Add($lbl_triage, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_triage} = Wx::Choice->new($self->{box_overview_1}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Routine", "Urgent", "Critical", "Post-Op"], );
    $self->{choice_triage}->SetSelection(0);
    $self->{grid_vitals}->Add($self->{choice_triage}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_overview_2} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_overview}, wxID_ANY, "Summary"), wxVERTICAL);
    $self->{sizer_overview}->Add($self->{box_overview_2}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{txt_summary} = Wx::TextCtrl->new($self->{box_overview_2}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_overview_2}->Add($self->{txt_summary}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_notes} = Wx::Panel->new($self->{nb_patient_workspace}, wxID_ANY);
    $self->{nb_patient_workspace}->AddPage($self->{page_notes}, "SOAP / Notes");
    
    $self->{sizer_notes} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_soap_hdr} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_notes}, wxID_ANY, "SOAP"), wxHORIZONTAL);
    $self->{sizer_notes}->Add($self->{box_soap_hdr}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_note_new} = Wx::Button->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, "New Note");
    $self->{box_soap_hdr}->Add($self->{btn_note_new}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_note_sign} = Wx::Button->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, "Sign");
    $self->{box_soap_hdr}->Add($self->{btn_note_sign}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_note_print} = Wx::Button->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, "Print");
    $self->{box_soap_hdr}->Add($self->{btn_note_print}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_soap_hdr}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_note_client_visible} = Wx::CheckBox->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, "Client Visible");
    $self->{box_soap_hdr}->Add($self->{chk_note_client_visible}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_note_locked} = Wx::CheckBox->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, "Lock");
    $self->{box_soap_hdr}->Add($self->{chk_note_locked}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{nb_soap} = Wx::Notebook->new($self->{page_notes}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM);
    $self->{sizer_notes}->Add($self->{nb_soap}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{soap_s} = Wx::Panel->new($self->{nb_soap}, wxID_ANY);
    $self->{nb_soap}->AddPage($self->{soap_s}, "S");
    
    $self->{sizer_soap_s} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_soap_s} = Wx::TextCtrl->new($self->{soap_s}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_s}->Add($self->{txt_soap_s}, 1, wxALL|wxEXPAND, 6);
    
    $self->{soap_o} = Wx::Panel->new($self->{nb_soap}, wxID_ANY);
    $self->{nb_soap}->AddPage($self->{soap_o}, "O");
    
    $self->{sizer_soap_o} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_soap_o} = Wx::TextCtrl->new($self->{soap_o}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_o}->Add($self->{txt_soap_o}, 1, wxALL|wxEXPAND, 6);
    
    $self->{soap_a} = Wx::Panel->new($self->{nb_soap}, wxID_ANY);
    $self->{nb_soap}->AddPage($self->{soap_a}, "A");
    
    $self->{sizer_soap_a} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_soap_a} = Wx::TextCtrl->new($self->{soap_a}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_a}->Add($self->{txt_soap_a}, 1, wxALL|wxEXPAND, 6);
    
    $self->{soap_p} = Wx::Panel->new($self->{nb_soap}, wxID_ANY);
    $self->{nb_soap}->AddPage($self->{soap_p}, "P");
    
    $self->{sizer_soap_p} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_soap_p} = Wx::TextCtrl->new($self->{soap_p}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_p}->Add($self->{txt_soap_p}, 1, wxALL|wxEXPAND, 6);
    
    $self->{soap_dx} = Wx::Panel->new($self->{nb_soap}, wxID_ANY);
    $self->{nb_soap}->AddPage($self->{soap_dx}, "Dx/Problem List");
    
    $self->{sizer_soap_dx} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_dx} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{sizer_soap_dx}->Add($self->{grid_dx}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_dx_primary = Wx::StaticText->new($self->{soap_dx}, wxID_ANY, "Primary Dx");
    $self->{grid_dx}->Add($lbl_dx_primary, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dx_primary} = Wx::TextCtrl->new($self->{soap_dx}, wxID_ANY, "");
    $self->{grid_dx}->Add($self->{txt_dx_primary}, 1, wxEXPAND, 0);
    
    my $lbl_dx_code = Wx::StaticText->new($self->{soap_dx}, wxID_ANY, "Code");
    $self->{grid_dx}->Add($lbl_dx_code, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dx_code} = Wx::TextCtrl->new($self->{soap_dx}, wxID_ANY, "");
    $self->{txt_dx_code}->SetMinSize(Wx::Size->new(120,-1));
    $self->{grid_dx}->Add($self->{txt_dx_code}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_dx_chronic} = Wx::CheckBox->new($self->{soap_dx}, wxID_ANY, "Chronic");
    $self->{grid_dx}->Add($self->{chk_dx_chronic}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_dx_resolved} = Wx::CheckBox->new($self->{soap_dx}, wxID_ANY, "Resolved");
    $self->{grid_dx}->Add($self->{chk_dx_resolved}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_dx_notes = Wx::StaticText->new($self->{soap_dx}, wxID_ANY, "Dx Notes");
    $self->{grid_dx}->Add($lbl_dx_notes, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dx_notes} = Wx::TextCtrl->new($self->{soap_dx}, wxID_ANY, "");
    $self->{grid_dx}->Add($self->{txt_dx_notes}, 1, wxEXPAND, 0);
    
    $self->{txt_problem_list} = Wx::TextCtrl->new($self->{soap_dx}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_dx}->Add($self->{txt_problem_list}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_orders} = Wx::Panel->new($self->{nb_patient_workspace}, wxID_ANY);
    $self->{nb_patient_workspace}->AddPage($self->{page_orders}, "Orders");
    
    $self->{sizer_orders} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_orders_toolbar} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_orders}, wxID_ANY, "Orders / Charges"), wxHORIZONTAL);
    $self->{sizer_orders}->Add($self->{box_orders_toolbar}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_add_charge} = Wx::Button->new($self->{box_orders_toolbar}->GetStaticBox(), wxID_ANY, "Add Charge");
    $self->{box_orders_toolbar}->Add($self->{btn_add_charge}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_add_lab} = Wx::Button->new($self->{box_orders_toolbar}->GetStaticBox(), wxID_ANY, "Lab Order");
    $self->{box_orders_toolbar}->Add($self->{btn_add_lab}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_add_rx} = Wx::Button->new($self->{box_orders_toolbar}->GetStaticBox(), wxID_ANY, "Rx");
    $self->{box_orders_toolbar}->Add($self->{btn_add_rx}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_orders_toolbar}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_estimate_mode} = Wx::CheckBox->new($self->{box_orders_toolbar}->GetStaticBox(), wxID_ANY, "Estimate Mode");
    $self->{box_orders_toolbar}->Add($self->{chk_estimate_mode}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_bundle} = Wx::CheckBox->new($self->{box_orders_toolbar}->GetStaticBox(), wxID_ANY, "Bundle");
    $self->{box_orders_toolbar}->Add($self->{chk_bundle}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{txt_orders} = Wx::TextCtrl->new($self->{page_orders}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_orders}->Add($self->{txt_orders}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{page_tasks} = Wx::Panel->new($self->{nb_patient_workspace}, wxID_ANY);
    $self->{nb_patient_workspace}->AddPage($self->{page_tasks}, "Tasks");
    
    $self->{sizer_tasks} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_tasks_toolbar} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_tasks}, wxID_ANY, "Task Board"), wxHORIZONTAL);
    $self->{sizer_tasks}->Add($self->{box_tasks_toolbar}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_task_new} = Wx::Button->new($self->{box_tasks_toolbar}->GetStaticBox(), wxID_ANY, "New Task");
    $self->{box_tasks_toolbar}->Add($self->{btn_task_new}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_task_done} = Wx::Button->new($self->{box_tasks_toolbar}->GetStaticBox(), wxID_ANY, "Mark Done");
    $self->{box_tasks_toolbar}->Add($self->{btn_task_done}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_tasks_toolbar}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{choice_task_filter} = Wx::Choice->new($self->{box_tasks_toolbar}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["All", "My Tasks", "Nursing", "Doctor", "Pharmacy", "Lab"], );
    $self->{choice_task_filter}->SetSelection(0);
    $self->{box_tasks_toolbar}->Add($self->{choice_task_filter}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{list_tasks} = Wx::ListCtrl->new($self->{page_tasks}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_tasks}->Add($self->{list_tasks}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{tab_clinical_center} = Wx::Panel->new($self->{nb_centers}, wxID_ANY);
    $self->{nb_centers}->AddPage($self->{tab_clinical_center}, "Clinical Center");
    
    $self->{sizer_clinical} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_clinical_hdr} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{tab_clinical_center}, wxID_ANY, "Clinical Center"), wxHORIZONTAL);
    $self->{sizer_clinical}->Add($self->{box_clinical_hdr}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_clin_new_case} = Wx::Button->new($self->{box_clinical_hdr}->GetStaticBox(), wxID_ANY, "New Case");
    $self->{box_clinical_hdr}->Add($self->{btn_clin_new_case}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_clin_protocol} = Wx::Button->new($self->{box_clinical_hdr}->GetStaticBox(), wxID_ANY, "Apply Protocol");
    $self->{box_clinical_hdr}->Add($self->{btn_clin_protocol}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_clin_discharge} = Wx::Button->new($self->{box_clinical_hdr}->GetStaticBox(), wxID_ANY, "Discharge");
    $self->{box_clinical_hdr}->Add($self->{btn_clin_discharge}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_clinical_hdr}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_clin_inpatient} = Wx::CheckBox->new($self->{box_clinical_hdr}->GetStaticBox(), wxID_ANY, "Inpatient");
    $self->{box_clinical_hdr}->Add($self->{chk_clin_inpatient}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_clin_iso} = Wx::CheckBox->new($self->{box_clinical_hdr}->GetStaticBox(), wxID_ANY, "Isolation");
    $self->{box_clinical_hdr}->Add($self->{chk_clin_iso}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{nb_clinical} = Wx::Notebook->new($self->{tab_clinical_center}, wxID_ANY);
    $self->{sizer_clinical}->Add($self->{nb_clinical}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{clin_anesthesia} = Wx::Panel->new($self->{nb_clinical}, wxID_ANY);
    $self->{nb_clinical}->AddPage($self->{clin_anesthesia}, "Anesthesia/Surgery");
    
    $self->{sizer_anesthesia} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_an_risk} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{clin_anesthesia}, wxID_ANY, "Pre-Op / Risk / Plan"), wxVERTICAL);
    $self->{sizer_anesthesia}->Add($self->{box_an_risk}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_an} = Wx::FlexGridSizer->new(0, 6, 6, 8);
    $self->{box_an_risk}->Add($self->{grid_an}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_asa = Wx::StaticText->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "ASA");
    $self->{grid_an}->Add($lbl_asa, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_asa} = Wx::Choice->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["I", "II", "III", "IV", "V"], );
    $self->{choice_asa}->SetSelection(0);
    $self->{grid_an}->Add($self->{choice_asa}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_proc = Wx::StaticText->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "Procedure");
    $self->{grid_an}->Add($lbl_proc, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_proc} = Wx::TextCtrl->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_an}->Add($self->{txt_proc}, 1, wxEXPAND, 0);
    
    my $lbl_premed = Wx::StaticText->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "Premed");
    $self->{grid_an}->Add($lbl_premed, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_premed} = Wx::TextCtrl->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_an}->Add($self->{txt_premed}, 1, wxEXPAND, 0);
    
    my $lbl_induction = Wx::StaticText->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "Induction");
    $self->{grid_an}->Add($lbl_induction, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_induction} = Wx::TextCtrl->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_an}->Add($self->{txt_induction}, 1, wxEXPAND, 0);
    
    $self->{chk_et_tube} = Wx::CheckBox->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "ET Tube");
    $self->{grid_an}->Add($self->{chk_et_tube}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_iv_catheter} = Wx::CheckBox->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "IV Catheter");
    $self->{grid_an}->Add($self->{chk_iv_catheter}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_monitor = Wx::StaticText->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "Monitoring");
    $self->{grid_an}->Add($lbl_monitor, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_monitor} = Wx::TextCtrl->new($self->{box_an_risk}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_an}->Add($self->{txt_monitor}, 1, wxEXPAND, 0);
    
    $self->{box_an_log} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{clin_anesthesia}, wxID_ANY, "Anesthesia Timeline / Notes"), wxVERTICAL);
    $self->{sizer_anesthesia}->Add($self->{box_an_log}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{txt_an_log} = Wx::TextCtrl->new($self->{box_an_log}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_an_log}->Add($self->{txt_an_log}, 1, wxALL|wxEXPAND, 6);
    
    $self->{clin_prevent} = Wx::Panel->new($self->{nb_clinical}, wxID_ANY);
    $self->{nb_clinical}->AddPage($self->{clin_prevent}, "Vaccines/Preventatives");
    
    $self->{sizer_prevent} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_vax} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{clin_prevent}, wxID_ANY, "Vaccines"), wxVERTICAL);
    $self->{sizer_prevent}->Add($self->{box_vax}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_vax} = Wx::FlexGridSizer->new(0, 6, 6, 8);
    $self->{box_vax}->Add($self->{grid_vax}, 0, wxALL|wxEXPAND, 6);
    
    $self->{chk_rabies} = Wx::CheckBox->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "Rabies");
    $self->{grid_vax}->Add($self->{chk_rabies}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rabies_due} = Wx::TextCtrl->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_vax}->Add($self->{txt_rabies_due}, 1, wxEXPAND, 0);
    
    $self->{chk_dhpp} = Wx::CheckBox->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "DHPP");
    $self->{grid_vax}->Add($self->{chk_dhpp}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dhpp_due} = Wx::TextCtrl->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_vax}->Add($self->{txt_dhpp_due}, 1, wxEXPAND, 0);
    
    $self->{chk_lepto} = Wx::CheckBox->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "Lepto");
    $self->{grid_vax}->Add($self->{chk_lepto}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_lepto_due} = Wx::TextCtrl->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_vax}->Add($self->{txt_lepto_due}, 1, wxEXPAND, 0);
    
    $self->{chk_fvrcp} = Wx::CheckBox->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "FVRCP");
    $self->{grid_vax}->Add($self->{chk_fvrcp}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_fvrcp_due} = Wx::TextCtrl->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_vax}->Add($self->{txt_fvrcp_due}, 1, wxEXPAND, 0);
    
    $self->{chk_feLv} = Wx::CheckBox->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "FeLV");
    $self->{grid_vax}->Add($self->{chk_feLv}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_felv_due} = Wx::TextCtrl->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_vax}->Add($self->{txt_felv_due}, 1, wxEXPAND, 0);
    
    $self->{chk_bordetella} = Wx::CheckBox->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "Bordetella");
    $self->{grid_vax}->Add($self->{chk_bordetella}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_bord_due} = Wx::TextCtrl->new($self->{box_vax}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_vax}->Add($self->{txt_bord_due}, 1, wxEXPAND, 0);
    
    $self->{box_prev} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{clin_prevent}, wxID_ANY, "Preventatives / Reminders"), wxVERTICAL);
    $self->{sizer_prevent}->Add($self->{box_prev}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{txt_prevent_notes} = Wx::TextCtrl->new($self->{box_prev}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_prev}->Add($self->{txt_prevent_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{clin_inpatient} = Wx::Panel->new($self->{nb_clinical}, wxID_ANY);
    $self->{nb_clinical}->AddPage($self->{clin_inpatient}, "Inpatient/ICU");
    
    $self->{sizer_inpatient} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_ip_grid} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{clin_inpatient}, wxID_ANY, "ICU / Treatment Plan"), wxVERTICAL);
    $self->{sizer_inpatient}->Add($self->{box_ip_grid}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_ip} = Wx::FlexGridSizer->new(0, 6, 6, 8);
    $self->{box_ip_grid}->Add($self->{grid_ip}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_ip_loc = Wx::StaticText->new($self->{box_ip_grid}->GetStaticBox(), wxID_ANY, "Cage/Run");
    $self->{grid_ip}->Add($lbl_ip_loc, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_ip_loc} = Wx::TextCtrl->new($self->{box_ip_grid}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_ip}->Add($self->{txt_ip_loc}, 1, wxEXPAND, 0);
    
    my $lbl_ip_rate = Wx::StaticText->new($self->{box_ip_grid}->GetStaticBox(), wxID_ANY, "Fluid Rate");
    $self->{grid_ip}->Add($lbl_ip_rate, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_ip_rate} = Wx::TextCtrl->new($self->{box_ip_grid}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_ip}->Add($self->{txt_ip_rate}, 1, wxEXPAND, 0);
    
    $self->{chk_ip_pain} = Wx::CheckBox->new($self->{box_ip_grid}->GetStaticBox(), wxID_ANY, "Pain Score q4h");
    $self->{grid_ip}->Add($self->{chk_ip_pain}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_ip_tpr} = Wx::CheckBox->new($self->{box_ip_grid}->GetStaticBox(), wxID_ANY, "TPR q4h");
    $self->{grid_ip}->Add($self->{chk_ip_tpr}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_ip_i_o} = Wx::CheckBox->new($self->{box_ip_grid}->GetStaticBox(), wxID_ANY, "I/O");
    $self->{grid_ip}->Add($self->{chk_ip_i_o}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_ip_glucose} = Wx::CheckBox->new($self->{box_ip_grid}->GetStaticBox(), wxID_ANY, "Glucose");
    $self->{grid_ip}->Add($self->{chk_ip_glucose}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_ip_log} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{clin_inpatient}, wxID_ANY, "Nursing Notes / Rounds"), wxVERTICAL);
    $self->{sizer_inpatient}->Add($self->{box_ip_log}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{txt_ip_notes} = Wx::TextCtrl->new($self->{box_ip_log}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_ip_log}->Add($self->{txt_ip_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{clin_csl} = Wx::Panel->new($self->{nb_clinical}, wxID_ANY);
    $self->{nb_clinical}->AddPage($self->{clin_csl}, "Controlled Substances");
    
    $self->{sizer_csl} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_csl_hdr} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{clin_csl}, wxID_ANY, "Controlled Substances (Stub UI)"), wxVERTICAL);
    $self->{sizer_csl}->Add($self->{box_csl_hdr}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_csl} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{box_csl_hdr}->Add($self->{grid_csl}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_csl_drug = Wx::StaticText->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "Drug");
    $self->{grid_csl}->Add($lbl_csl_drug, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_csl_drug} = Wx::TextCtrl->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_csl}->Add($self->{txt_csl_drug}, 1, wxEXPAND, 0);
    
    my $lbl_csl_qty = Wx::StaticText->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "Qty");
    $self->{grid_csl}->Add($lbl_csl_qty, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_csl_qty} = Wx::TextCtrl->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_csl_qty}->SetMinSize(Wx::Size->new(90,-1));
    $self->{grid_csl}->Add($self->{txt_csl_qty}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_csl_reason = Wx::StaticText->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "Reason");
    $self->{grid_csl}->Add($lbl_csl_reason, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_csl_reason} = Wx::TextCtrl->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_csl}->Add($self->{txt_csl_reason}, 1, wxEXPAND, 0);
    
    my $lbl_csl_witness = Wx::StaticText->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "Witness");
    $self->{grid_csl}->Add($lbl_csl_witness, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_csl_witness} = Wx::TextCtrl->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_csl}->Add($self->{txt_csl_witness}, 1, wxEXPAND, 0);
    
    $self->{row_csl_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_csl_hdr}->Add($self->{row_csl_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_csl_log} = Wx::Button->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "Log Dispense");
    $self->{row_csl_btns}->Add($self->{btn_csl_log}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_csl_void} = Wx::Button->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "Void");
    $self->{row_csl_btns}->Add($self->{btn_csl_void}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{row_csl_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_csl_lock} = Wx::CheckBox->new($self->{box_csl_hdr}->GetStaticBox(), wxID_ANY, "Lock Entry");
    $self->{row_csl_btns}->Add($self->{chk_csl_lock}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_csl_audit} = Wx::TextCtrl->new($self->{clin_csl}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_csl}->Add($self->{txt_csl_audit}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{clin_discharge} = Wx::Panel->new($self->{nb_clinical}, wxID_ANY);
    $self->{nb_clinical}->AddPage($self->{clin_discharge}, "Discharge Plan");
    
    $self->{sizer_discharge} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_discharge} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{clin_discharge}, wxID_ANY, "Discharge Instructions"), wxVERTICAL);
    $self->{sizer_discharge}->Add($self->{box_discharge}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_discharge} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{box_discharge}->Add($self->{grid_discharge}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_dc_recheck = Wx::StaticText->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "Recheck");
    $self->{grid_discharge}->Add($lbl_dc_recheck, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dc_recheck} = Wx::TextCtrl->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_discharge}->Add($self->{txt_dc_recheck}, 1, wxEXPAND, 0);
    
    my $lbl_dc_meds = Wx::StaticText->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "Meds");
    $self->{grid_discharge}->Add($lbl_dc_meds, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dc_meds} = Wx::TextCtrl->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_discharge}->Add($self->{txt_dc_meds}, 1, wxEXPAND, 0);
    
    $self->{chk_dc_e_collar} = Wx::CheckBox->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "E-Collar");
    $self->{grid_discharge}->Add($self->{chk_dc_e_collar}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_dc_restrict} = Wx::CheckBox->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "Restrict Activity");
    $self->{grid_discharge}->Add($self->{chk_dc_restrict}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_dc_owner_ack = Wx::StaticText->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "Owner Ack");
    $self->{grid_discharge}->Add($lbl_dc_owner_ack, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dc_owner_ack} = Wx::TextCtrl->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_discharge}->Add($self->{txt_dc_owner_ack}, 1, wxEXPAND, 0);
    
    $self->{txt_dc_instructions} = Wx::TextCtrl->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_discharge}->Add($self->{txt_dc_instructions}, 1, wxALL|wxEXPAND, 6);
    
    $self->{row_dc_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_discharge}->Add($self->{row_dc_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_dc_print} = Wx::Button->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "Print");
    $self->{row_dc_btns}->Add($self->{btn_dc_print}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_dc_email} = Wx::Button->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "Email");
    $self->{row_dc_btns}->Add($self->{btn_dc_email}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{row_dc_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_dc_finalize} = Wx::Button->new($self->{box_discharge}->GetStaticBox(), wxID_ANY, "Finalize");
    $self->{row_dc_btns}->Add($self->{btn_dc_finalize}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{tab_operations_center} = Wx::Panel->new($self->{nb_centers}, wxID_ANY);
    $self->{nb_centers}->AddPage($self->{tab_operations_center}, "Operations Center");
    
    $self->{sizer_ops} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_ops_hdr} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{tab_operations_center}, wxID_ANY, "Operations Center"), wxHORIZONTAL);
    $self->{sizer_ops}->Add($self->{box_ops_hdr}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_ops_sync} = Wx::Button->new($self->{box_ops_hdr}->GetStaticBox(), wxID_ANY, "Sync Devices");
    $self->{box_ops_hdr}->Add($self->{btn_ops_sync}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_ops_reconcile} = Wx::Button->new($self->{box_ops_hdr}->GetStaticBox(), wxID_ANY, "Reconcile");
    $self->{box_ops_hdr}->Add($self->{btn_ops_reconcile}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_ops_hdr}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_ops_audit} = Wx::CheckBox->new($self->{box_ops_hdr}->GetStaticBox(), wxID_ANY, "Audit Mode");
    $self->{box_ops_hdr}->Add($self->{chk_ops_audit}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{nb_ops} = Wx::Notebook->new($self->{tab_operations_center}, wxID_ANY);
    $self->{sizer_ops}->Add($self->{nb_ops}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{ops_inventory} = Wx::Panel->new($self->{nb_ops}, wxID_ANY);
    $self->{nb_ops}->AddPage($self->{ops_inventory}, "Inventory/Lots");
    
    $self->{sizer_ops_inv} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_inv} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{ops_inventory}, wxID_ANY, "Inventory + Lot/Expiry Controls"), wxVERTICAL);
    $self->{sizer_ops_inv}->Add($self->{box_inv}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_inv} = Wx::FlexGridSizer->new(0, 6, 6, 8);
    $self->{box_inv}->Add($self->{grid_inv}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_item = Wx::StaticText->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Item");
    $self->{grid_inv}->Add($lbl_item, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_item} = Wx::TextCtrl->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_inv}->Add($self->{txt_inv_item}, 1, wxEXPAND, 0);
    
    my $lbl_sku = Wx::StaticText->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "SKU");
    $self->{grid_inv}->Add($lbl_sku, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_sku} = Wx::TextCtrl->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_inv_sku}->SetMinSize(Wx::Size->new(140,-1));
    $self->{grid_inv}->Add($self->{txt_inv_sku}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_lot = Wx::StaticText->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Lot");
    $self->{grid_inv}->Add($lbl_lot, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_lot} = Wx::TextCtrl->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_inv}->Add($self->{txt_inv_lot}, 1, wxEXPAND, 0);
    
    my $lbl_exp = Wx::StaticText->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Expiry");
    $self->{grid_inv}->Add($lbl_exp, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_exp} = Wx::TextCtrl->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_inv_exp}->SetMinSize(Wx::Size->new(140,-1));
    $self->{grid_inv}->Add($self->{txt_inv_exp}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_inv_controlled} = Wx::CheckBox->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Controlled");
    $self->{grid_inv}->Add($self->{chk_inv_controlled}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_inv_refrig} = Wx::CheckBox->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Refrigerate");
    $self->{grid_inv}->Add($self->{chk_inv_refrig}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_par = Wx::StaticText->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "PAR");
    $self->{grid_inv}->Add($lbl_par, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_par} = Wx::TextCtrl->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_inv_par}->SetMinSize(Wx::Size->new(90,-1));
    $self->{grid_inv}->Add($self->{txt_inv_par}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{row_inv_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_inv}->Add($self->{row_inv_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_inv_receive} = Wx::Button->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Receive");
    $self->{row_inv_btns}->Add($self->{btn_inv_receive}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_inv_adjust} = Wx::Button->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Adjust");
    $self->{row_inv_btns}->Add($self->{btn_inv_adjust}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_inv_waste} = Wx::Button->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Waste");
    $self->{row_inv_btns}->Add($self->{btn_inv_waste}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{row_inv_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_inv_export} = Wx::Button->new($self->{box_inv}->GetStaticBox(), wxID_ANY, "Export");
    $self->{row_inv_btns}->Add($self->{btn_inv_export}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_audit} = Wx::TextCtrl->new($self->{ops_inventory}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_ops_inv}->Add($self->{txt_inv_audit}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{ops_lab_devices} = Wx::Panel->new($self->{nb_ops}, wxID_ANY);
    $self->{nb_ops}->AddPage($self->{ops_lab_devices}, "Lab Devices");
    
    $self->{sizer_ops_devices} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_devices} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{ops_lab_devices}, wxID_ANY, "Devices / Integrations"), wxVERTICAL);
    $self->{sizer_ops_devices}->Add($self->{box_devices}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_devices} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{box_devices}->Add($self->{grid_devices}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_dev_idexx = Wx::StaticText->new($self->{box_devices}->GetStaticBox(), wxID_ANY, "IDEXX");
    $self->{grid_devices}->Add($lbl_dev_idexx, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dev_idexx} = Wx::TextCtrl->new($self->{box_devices}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_devices}->Add($self->{txt_dev_idexx}, 1, wxEXPAND, 0);
    
    $self->{chk_dev_idexx} = Wx::CheckBox->new($self->{box_devices}->GetStaticBox(), wxID_ANY, "Enabled");
    $self->{grid_devices}->Add($self->{chk_dev_idexx}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_dev_test_idexx} = Wx::Button->new($self->{box_devices}->GetStaticBox(), wxID_ANY, "Test");
    $self->{grid_devices}->Add($self->{btn_dev_test_idexx}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_dev_ua = Wx::StaticText->new($self->{box_devices}->GetStaticBox(), wxID_ANY, "Ultrasound");
    $self->{grid_devices}->Add($lbl_dev_ua, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dev_us} = Wx::TextCtrl->new($self->{box_devices}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_devices}->Add($self->{txt_dev_us}, 1, wxEXPAND, 0);
    
    $self->{chk_dev_us} = Wx::CheckBox->new($self->{box_devices}->GetStaticBox(), wxID_ANY, "Enabled");
    $self->{grid_devices}->Add($self->{chk_dev_us}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_dev_test_us} = Wx::Button->new($self->{box_devices}->GetStaticBox(), wxID_ANY, "Test");
    $self->{grid_devices}->Add($self->{btn_dev_test_us}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_device_log} = Wx::TextCtrl->new($self->{ops_lab_devices}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_ops_devices}->Add($self->{txt_device_log}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{ops_comms} = Wx::Panel->new($self->{nb_ops}, wxID_ANY);
    $self->{nb_ops}->AddPage($self->{ops_comms}, "Communications");
    
    $self->{sizer_ops_comms} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_comms} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{ops_comms}, wxID_ANY, "Communications (templates + delivery)"), wxVERTICAL);
    $self->{sizer_ops_comms}->Add($self->{box_comms}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_comms} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{box_comms}->Add($self->{grid_comms}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_tpl = Wx::StaticText->new($self->{box_comms}->GetStaticBox(), wxID_ANY, "Template");
    $self->{grid_comms}->Add($lbl_tpl, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_tpl} = Wx::Choice->new($self->{box_comms}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Appointment Reminder", "Lab Results Ready", "Discharge Follow-Up", "Preventative Due"], );
    $self->{choice_tpl}->SetSelection(0);
    $self->{grid_comms}->Add($self->{choice_tpl}, 1, wxEXPAND, 0);
    
    $self->{chk_sms} = Wx::CheckBox->new($self->{box_comms}->GetStaticBox(), wxID_ANY, "SMS");
    $self->{grid_comms}->Add($self->{chk_sms}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_email} = Wx::CheckBox->new($self->{box_comms}->GetStaticBox(), wxID_ANY, "Email");
    $self->{grid_comms}->Add($self->{chk_email}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_to = Wx::StaticText->new($self->{box_comms}->GetStaticBox(), wxID_ANY, "To");
    $self->{grid_comms}->Add($lbl_to, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_to} = Wx::TextCtrl->new($self->{box_comms}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_comms}->Add($self->{txt_to}, 1, wxEXPAND, 0);
    
    $self->{btn_preview} = Wx::Button->new($self->{box_comms}->GetStaticBox(), wxID_ANY, "Preview");
    $self->{grid_comms}->Add($self->{btn_preview}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_send} = Wx::Button->new($self->{box_comms}->GetStaticBox(), wxID_ANY, "Send");
    $self->{grid_comms}->Add($self->{btn_send}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_comms_body} = Wx::TextCtrl->new($self->{ops_comms}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_ops_comms}->Add($self->{txt_comms_body}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{ops_staff} = Wx::Panel->new($self->{nb_ops}, wxID_ANY);
    $self->{nb_ops}->AddPage($self->{ops_staff}, "Staff/Roles");
    
    $self->{sizer_ops_staff} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_staff} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{ops_staff}, wxID_ANY, "Staff / Roles / Permissions (stub)"), wxVERTICAL);
    $self->{sizer_ops_staff}->Add($self->{box_staff}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_staff} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{box_staff}->Add($self->{grid_staff}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_staff_user = Wx::StaticText->new($self->{box_staff}->GetStaticBox(), wxID_ANY, "Staff");
    $self->{grid_staff}->Add($lbl_staff_user, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_staff_user} = Wx::TextCtrl->new($self->{box_staff}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_staff}->Add($self->{txt_staff_user}, 1, wxEXPAND, 0);
    
    my $lbl_staff_role = Wx::StaticText->new($self->{box_staff}->GetStaticBox(), wxID_ANY, "Role");
    $self->{grid_staff}->Add($lbl_staff_role, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_staff_role} = Wx::Choice->new($self->{box_staff}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Doctor", "Technician", "Reception", "Manager", "Pharmacy"], );
    $self->{choice_staff_role}->SetSelection(0);
    $self->{grid_staff}->Add($self->{choice_staff_role}, 1, wxEXPAND, 0);
    
    $self->{chk_perm_rx} = Wx::CheckBox->new($self->{box_staff}->GetStaticBox(), wxID_ANY, "Rx");
    $self->{grid_staff}->Add($self->{chk_perm_rx}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_perm_csl} = Wx::CheckBox->new($self->{box_staff}->GetStaticBox(), wxID_ANY, "Controlled");
    $self->{grid_staff}->Add($self->{chk_perm_csl}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_perm_fin} = Wx::CheckBox->new($self->{box_staff}->GetStaticBox(), wxID_ANY, "Financial");
    $self->{grid_staff}->Add($self->{chk_perm_fin}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_perm_admin} = Wx::CheckBox->new($self->{box_staff}->GetStaticBox(), wxID_ANY, "Admin");
    $self->{grid_staff}->Add($self->{chk_perm_admin}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_staff_audit} = Wx::TextCtrl->new($self->{ops_staff}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_ops_staff}->Add($self->{txt_staff_audit}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{ops_reports} = Wx::Panel->new($self->{nb_ops}, wxID_ANY);
    $self->{nb_ops}->AddPage($self->{ops_reports}, "Reports");
    
    $self->{sizer_ops_reports} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_reports} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{ops_reports}, wxID_ANY, "Reports / Presets (stub)"), wxVERTICAL);
    $self->{sizer_ops_reports}->Add($self->{box_reports}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_reports} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{box_reports}->Add($self->{grid_reports}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_rep = Wx::StaticText->new($self->{box_reports}->GetStaticBox(), wxID_ANY, "Preset");
    $self->{grid_reports}->Add($lbl_rep, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_report} = Wx::Choice->new($self->{box_reports}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Daily Revenue", "Outstanding Balances", "Vaccine Compliance", "Inventory Below PAR", "Surgery Throughput"], );
    $self->{choice_report}->SetSelection(0);
    $self->{grid_reports}->Add($self->{choice_report}, 1, wxEXPAND, 0);
    
    $self->{btn_run_report} = Wx::Button->new($self->{box_reports}->GetStaticBox(), wxID_ANY, "Run");
    $self->{grid_reports}->Add($self->{btn_run_report}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_export_report} = Wx::Button->new($self->{box_reports}->GetStaticBox(), wxID_ANY, "Export");
    $self->{grid_reports}->Add($self->{btn_export_report}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_report_out} = Wx::TextCtrl->new($self->{ops_reports}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_ops_reports}->Add($self->{txt_report_out}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{grid_reports}->AddGrowableCol(3);
    
    $self->{ops_reports}->SetSizer($self->{sizer_ops_reports});
    
    $self->{grid_staff}->AddGrowableCol(3);
    
    $self->{ops_staff}->SetSizer($self->{sizer_ops_staff});
    
    $self->{grid_comms}->AddGrowableCol(3);
    
    $self->{ops_comms}->SetSizer($self->{sizer_ops_comms});
    
    $self->{grid_devices}->AddGrowableCol(3);
    
    $self->{ops_lab_devices}->SetSizer($self->{sizer_ops_devices});
    
    $self->{grid_inv}->AddGrowableCol(3);
    
    $self->{ops_inventory}->SetSizer($self->{sizer_ops_inv});
    
    $self->{tab_operations_center}->SetSizer($self->{sizer_ops});
    
    $self->{grid_discharge}->AddGrowableCol(3);
    
    $self->{clin_discharge}->SetSizer($self->{sizer_discharge});
    
    $self->{grid_csl}->AddGrowableCol(3);
    
    $self->{clin_csl}->SetSizer($self->{sizer_csl});
    
    $self->{grid_ip}->AddGrowableCol(3);
    
    $self->{clin_inpatient}->SetSizer($self->{sizer_inpatient});
    
    $self->{grid_vax}->AddGrowableCol(3);
    
    $self->{clin_prevent}->SetSizer($self->{sizer_prevent});
    
    $self->{grid_an}->AddGrowableCol(3);
    
    $self->{clin_anesthesia}->SetSizer($self->{sizer_anesthesia});
    
    $self->{tab_clinical_center}->SetSizer($self->{sizer_clinical});
    
    $self->{page_tasks}->SetSizer($self->{sizer_tasks});
    
    $self->{page_orders}->SetSizer($self->{sizer_orders});
    
    $self->{grid_dx}->AddGrowableCol(1);
    
    $self->{soap_dx}->SetSizer($self->{sizer_soap_dx});
    
    $self->{soap_p}->SetSizer($self->{sizer_soap_p});
    
    $self->{soap_a}->SetSizer($self->{sizer_soap_a});
    
    $self->{soap_o}->SetSizer($self->{sizer_soap_o});
    
    $self->{soap_s}->SetSizer($self->{sizer_soap_s});
    
    $self->{page_notes}->SetSizer($self->{sizer_notes});
    
    $self->{page_overview}->SetSizer($self->{sizer_overview});
    
    $self->{panel_main_right}->SetSizer($self->{sizer_main_right});
    
    $self->{panel_main_left}->SetSizer($self->{sizer_main_left});
    
    $self->{split_main}->SplitVertically($self->{panel_main_left}, $self->{panel_main_right}, );
    
    $self->{tab_main_screen}->SetSizer($self->{sizer_main_tab});
    
    $self->{panel_root}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class VetCRMDenseFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_vetcrm = VetCRMDenseFrame->new();

    $self->SetTopWindow($frame_vetcrm);
    $frame_vetcrm->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
