#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Sat Feb 14 01:33:42 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package VetCRMDenseFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: VetCRMDenseFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1360, 900));
    $self->SetTitle("Vet CRM Dense Tabs Sample (wxGlade/wxPerl)");
    
    $self->{panel_root} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_global_strip} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{sizer_global_strip}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_site = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "Site");
    $self->{sizer_global_strip}->Add($lbl_site, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_site} = Wx::Choice->new($self->{panel_root}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Main Hospital", "Satellite Clinic", "Mobile"], );
    $self->{choice_site}->SetSelection(0);
    $self->{sizer_global_strip}->Add($self->{choice_site}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    my $lbl_user = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "User");
    $self->{sizer_global_strip}->Add($lbl_user, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    my $txt_user = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "doctor1");
    $self->{sizer_global_strip}->Add($txt_user, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_global_strip}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_offline} = Wx::CheckBox->new($self->{panel_root}, wxID_ANY, "Offline");
    $self->{sizer_global_strip}->Add($self->{chk_offline}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{gauge_bg} = Wx::Gauge->new($self->{panel_root}, wxID_ANY, 100, wxDefaultPosition, wxDefaultSize, 0);
    $self->{gauge_bg}->SetMinSize(Wx::Size->new(160,16));
    $self->{sizer_global_strip}->Add($self->{gauge_bg}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{split_main} = Wx::SplitterWindow->new($self->{panel_root}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_main}->SetMinimumPaneSize(20);
    $self->{sizer_root}->Add($self->{split_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{panel_left} = Wx::Panel->new($self->{split_main}, wxID_ANY);
    
    $self->{sizer_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_find} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_left}, wxID_ANY, "Find"), wxVERTICAL);
    $self->{sizer_left}->Add($self->{box_find}, 0, wxALL|wxEXPAND, 6);
    
    $self->{txt_find} = Wx::TextCtrl->new($self->{box_find}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_find}->SetMinSize(Wx::Size->new(-1,28));
    $self->{box_find}->Add($self->{txt_find}, 0, wxALL|wxEXPAND, 6);
    
    $self->{sizer_find_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_find}->Add($self->{sizer_find_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_find} = Wx::Button->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Find");
    $self->{sizer_find_btns}->Add($self->{btn_find}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_recent} = Wx::Button->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Recent");
    $self->{sizer_find_btns}->Add($self->{btn_recent}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_find_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_new} = Wx::Button->new($self->{box_find}->GetStaticBox(), wxID_ANY, "New...");
    $self->{sizer_find_btns}->Add($self->{btn_new}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{grid_left_flags} = Wx::FlexGridSizer->new(0, 2, 4, 8);
    $self->{box_find}->Add($self->{grid_left_flags}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_left_scope = Wx::StaticText->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Scope");
    $self->{grid_left_flags}->Add($lbl_left_scope, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_scope} = Wx::Choice->new($self->{box_find}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Clients + Patients", "Clients only", "Patients only"], );
    $self->{choice_scope}->SetSelection(0);
    $self->{grid_left_flags}->Add($self->{choice_scope}, 1, wxEXPAND, 0);
    
    my $lbl_left_flags = Wx::StaticText->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Flags");
    $self->{grid_left_flags}->Add($lbl_left_flags, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_left_checks} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{grid_left_flags}->Add($self->{sizer_left_checks}, 1, wxEXPAND, 0);
    
    $self->{chk_active} = Wx::CheckBox->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Active");
    $self->{sizer_left_checks}->Add($self->{chk_active}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_balance} = Wx::CheckBox->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Balance");
    $self->{sizer_left_checks}->Add($self->{chk_balance}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{chk_alerts} = Wx::CheckBox->new($self->{box_find}->GetStaticBox(), wxID_ANY, "Alerts");
    $self->{sizer_left_checks}->Add($self->{chk_alerts}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{box_list} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_left}, wxID_ANY, "Clients / Patients"), wxVERTICAL);
    $self->{sizer_left}->Add($self->{box_list}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{list_clients_patients} = Wx::ListCtrl->new($self->{box_list}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_list}->Add($self->{list_clients_patients}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_right} = Wx::Panel->new($self->{split_main}, wxID_ANY);
    
    $self->{sizer_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_ctx} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_right}, wxID_ANY, "Current Selection"), wxVERTICAL);
    $self->{sizer_right}->Add($self->{box_ctx}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_ctx} = Wx::FlexGridSizer->new(0, 6, 4, 8);
    $self->{box_ctx}->Add($self->{grid_ctx}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_client = Wx::StaticText->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "Client");
    $self->{grid_ctx}->Add($lbl_client, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_client} = Wx::TextCtrl->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_client}->SetMinSize(Wx::Size->new(-1,26));
    $self->{grid_ctx}->Add($self->{txt_client}, 1, wxEXPAND, 0);
    
    my $lbl_patient = Wx::StaticText->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "Patient");
    $self->{grid_ctx}->Add($lbl_patient, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_patient} = Wx::TextCtrl->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_patient}->SetMinSize(Wx::Size->new(-1,26));
    $self->{grid_ctx}->Add($self->{txt_patient}, 1, wxEXPAND, 0);
    
    my $lbl_alerts = Wx::StaticText->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "Alerts");
    $self->{grid_ctx}->Add($lbl_alerts, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_alerts} = Wx::TextCtrl->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_alerts}->SetMinSize(Wx::Size->new(-1,26));
    $self->{grid_ctx}->Add($self->{txt_alerts}, 1, wxEXPAND, 0);
    
    $self->{sizer_ctx_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_ctx}->Add($self->{sizer_ctx_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_checkin} = Wx::Button->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "Check-in");
    $self->{sizer_ctx_btns}->Add($self->{btn_checkin}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_new_appt} = Wx::Button->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "New Appt");
    $self->{sizer_ctx_btns}->Add($self->{btn_new_appt}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_invoice} = Wx::Button->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "Invoice");
    $self->{sizer_ctx_btns}->Add($self->{btn_invoice}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_rx} = Wx::Button->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "Rx");
    $self->{sizer_ctx_btns}->Add($self->{btn_rx}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_ctx_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_lock_record} = Wx::CheckBox->new($self->{box_ctx}->GetStaticBox(), wxID_ANY, "Lock record");
    $self->{sizer_ctx_btns}->Add($self->{chk_lock_record}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{nb_work} = Wx::Notebook->new($self->{panel_right}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM);
    $self->{sizer_right}->Add($self->{nb_work}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{tab_dashboard} = Wx::Panel->new($self->{nb_work}, wxID_ANY);
    $self->{nb_work}->AddPage($self->{tab_dashboard}, "Dashboard");
    
    $self->{sizer_dash} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_dash_actions} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{tab_dashboard}, wxID_ANY, "Front Desk / Today"), wxVERTICAL);
    $self->{sizer_dash}->Add($self->{box_dash_actions}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_dash} = Wx::FlexGridSizer->new(0, 4, 6, 10);
    $self->{box_dash_actions}->Add($self->{grid_dash}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_room = Wx::StaticText->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "Room");
    $self->{grid_dash}->Add($lbl_room, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_room} = Wx::Choice->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["1", "2", "3", "4"], );
    $self->{choice_room}->SetSelection(0);
    $self->{grid_dash}->Add($self->{choice_room}, 1, wxEXPAND, 0);
    
    my $lbl_provider = Wx::StaticText->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "Provider");
    $self->{grid_dash}->Add($lbl_provider, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_provider} = Wx::Choice->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Doctor A", "Doctor B", "Tech"], );
    $self->{choice_provider}->SetSelection(0);
    $self->{grid_dash}->Add($self->{choice_provider}, 1, wxEXPAND, 0);
    
    my $lbl_reason = Wx::StaticText->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "Reason");
    $self->{grid_dash}->Add($lbl_reason, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_reason} = Wx::TextCtrl->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_dash}->Add($self->{txt_reason}, 1, wxEXPAND, 0);
    
    my $lbl_priority = Wx::StaticText->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "Priority");
    $self->{grid_dash}->Add($lbl_priority, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_priority} = Wx::Choice->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Normal", "Urgent", "Critical"], );
    $self->{choice_priority}->SetSelection(0);
    $self->{grid_dash}->Add($self->{choice_priority}, 1, wxEXPAND, 0);
    
    $self->{sizer_dash_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_dash_actions}->Add($self->{sizer_dash_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_dash_checkin} = Wx::Button->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "Check-in");
    $self->{sizer_dash_btns}->Add($self->{btn_dash_checkin}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_dash_task} = Wx::Button->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "Create Task");
    $self->{sizer_dash_btns}->Add($self->{btn_dash_task}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_dash_message} = Wx::Button->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "Message");
    $self->{sizer_dash_btns}->Add($self->{btn_dash_message}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_dash_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_dash_autoprint} = Wx::CheckBox->new($self->{box_dash_actions}->GetStaticBox(), wxID_ANY, "Auto-print");
    $self->{sizer_dash_btns}->Add($self->{chk_dash_autoprint}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_dash_notes} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{tab_dashboard}, wxID_ANY, "Daily Notes / Alerts Feed"), wxVERTICAL);
    $self->{sizer_dash}->Add($self->{box_dash_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{txt_dash_feed} = Wx::TextCtrl->new($self->{box_dash_notes}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{box_dash_notes}->Add($self->{txt_dash_feed}, 1, wxALL|wxEXPAND, 6);
    
    $self->{tab_patients} = Wx::Panel->new($self->{nb_work}, wxID_ANY);
    $self->{nb_work}->AddPage($self->{tab_patients}, "Patients");
    
    $self->{sizer_pat_tab} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_pat_inner} = Wx::Notebook->new($self->{tab_patients}, wxID_ANY);
    $self->{sizer_pat_tab}->Add($self->{nb_pat_inner}, 1, wxALL|wxEXPAND, 6);
    
    $self->{pat_overview} = Wx::Panel->new($self->{nb_pat_inner}, wxID_ANY);
    $self->{nb_pat_inner}->AddPage($self->{pat_overview}, "Overview");
    
    $self->{sizer_pat_overview} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_pat} = Wx::FlexGridSizer->new(0, 4, 6, 10);
    $self->{sizer_pat_overview}->Add($self->{grid_pat}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_species = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "Species");
    $self->{grid_pat}->Add($lbl_species, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_species} = Wx::Choice->new($self->{pat_overview}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Canine", "Feline", "Avian", "Exotic"], );
    $self->{choice_species}->SetSelection(0);
    $self->{grid_pat}->Add($self->{choice_species}, 1, wxEXPAND, 0);
    
    my $lbl_breed = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "Breed");
    $self->{grid_pat}->Add($lbl_breed, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_breed} = Wx::TextCtrl->new($self->{pat_overview}, wxID_ANY, "");
    $self->{grid_pat}->Add($self->{txt_breed}, 1, wxEXPAND, 0);
    
    my $lbl_dob = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "DOB");
    $self->{grid_pat}->Add($lbl_dob, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dob} = Wx::TextCtrl->new($self->{pat_overview}, wxID_ANY, "");
    $self->{grid_pat}->Add($self->{txt_dob}, 1, wxEXPAND, 0);
    
    my $lbl_weight = Wx::StaticText->new($self->{pat_overview}, wxID_ANY, "Weight");
    $self->{grid_pat}->Add($lbl_weight, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_weight} = Wx::TextCtrl->new($self->{pat_overview}, wxID_ANY, "");
    $self->{grid_pat}->Add($self->{txt_weight}, 1, wxEXPAND, 0);
    
    $self->{box_pat_notes} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{pat_overview}, wxID_ANY, "Notes"), wxVERTICAL);
    $self->{sizer_pat_overview}->Add($self->{box_pat_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{txt_pat_notes} = Wx::TextCtrl->new($self->{box_pat_notes}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_pat_notes}->Add($self->{txt_pat_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{pat_contacts} = Wx::Panel->new($self->{nb_pat_inner}, wxID_ANY);
    $self->{nb_pat_inner}->AddPage($self->{pat_contacts}, "Contacts");
    
    $self->{sizer_contacts} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_contacts} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{pat_contacts}, wxID_ANY, "Contact Methods"), wxVERTICAL);
    $self->{sizer_contacts}->Add($self->{box_contacts}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_contacts} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{box_contacts}->Add($self->{grid_contacts}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_phone = Wx::StaticText->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "Phone");
    $self->{grid_contacts}->Add($lbl_phone, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_phone} = Wx::TextCtrl->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_contacts}->Add($self->{txt_phone}, 1, wxEXPAND, 0);
    
    my $lbl_email = Wx::StaticText->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "Email");
    $self->{grid_contacts}->Add($lbl_email, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_email} = Wx::TextCtrl->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_contacts}->Add($self->{txt_email}, 1, wxEXPAND, 0);
    
    my $lbl_pref = Wx::StaticText->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "Preference");
    $self->{grid_contacts}->Add($lbl_pref, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_contact_pref} = Wx::Choice->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Phone", "Email", "SMS", "Mail"], );
    $self->{choice_contact_pref}->SetSelection(0);
    $self->{grid_contacts}->Add($self->{choice_contact_pref}, 1, wxEXPAND, 0);
    
    $self->{sizer_contact_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_contacts}->Add($self->{sizer_contact_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_call} = Wx::Button->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "Call");
    $self->{sizer_contact_btns}->Add($self->{btn_call}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_email} = Wx::Button->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "Email");
    $self->{sizer_contact_btns}->Add($self->{btn_email}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_sms} = Wx::Button->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "SMS");
    $self->{sizer_contact_btns}->Add($self->{btn_sms}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_contact_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_contact_save} = Wx::Button->new($self->{box_contacts}->GetStaticBox(), wxID_ANY, "Save");
    $self->{sizer_contact_btns}->Add($self->{btn_contact_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_contact_log} = Wx::TextCtrl->new($self->{pat_contacts}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_contacts}->Add($self->{txt_contact_log}, 1, wxALL|wxEXPAND, 6);
    
    $self->{pat_reminders} = Wx::Panel->new($self->{nb_pat_inner}, wxID_ANY);
    $self->{nb_pat_inner}->AddPage($self->{pat_reminders}, "Reminders");
    
    $self->{sizer_rem} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_rem} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{pat_reminders}, wxID_ANY, "Reminders"), wxVERTICAL);
    $self->{sizer_rem}->Add($self->{box_rem}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_rem} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{box_rem}->Add($self->{grid_rem}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_rabies = Wx::StaticText->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Rabies due");
    $self->{grid_rem}->Add($lbl_rabies, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rabies} = Wx::TextCtrl->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rem}->Add($self->{txt_rabies}, 1, wxEXPAND, 0);
    
    my $lbl_wellness = Wx::StaticText->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Wellness due");
    $self->{grid_rem}->Add($lbl_wellness, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_wellness} = Wx::TextCtrl->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rem}->Add($self->{txt_wellness}, 1, wxEXPAND, 0);
    
    my $lbl_hw = Wx::StaticText->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Heartworm test");
    $self->{grid_rem}->Add($lbl_hw, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_hw} = Wx::TextCtrl->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rem}->Add($self->{txt_hw}, 1, wxEXPAND, 0);
    
    $self->{sizer_rem_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_rem}->Add($self->{sizer_rem_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_rem_postcard} = Wx::Button->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Postcard");
    $self->{sizer_rem_btns}->Add($self->{btn_rem_postcard}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_rem_email} = Wx::Button->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Email");
    $self->{sizer_rem_btns}->Add($self->{btn_rem_email}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_rem_sms} = Wx::Button->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "SMS");
    $self->{sizer_rem_btns}->Add($self->{btn_rem_sms}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_rem_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_rem_save} = Wx::Button->new($self->{box_rem}->GetStaticBox(), wxID_ANY, "Save");
    $self->{sizer_rem_btns}->Add($self->{btn_rem_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rem_log} = Wx::TextCtrl->new($self->{pat_reminders}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_rem}->Add($self->{txt_rem_log}, 1, wxALL|wxEXPAND, 6);
    
    $self->{pat_tags} = Wx::Panel->new($self->{nb_pat_inner}, wxID_ANY);
    $self->{nb_pat_inner}->AddPage($self->{pat_tags}, "Tags/Flags");
    
    $self->{sizer_tags} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_tags} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{pat_tags}, wxID_ANY, "Flags / Compliance"), wxVERTICAL);
    $self->{sizer_tags}->Add($self->{box_tags}, 0, wxALL|wxEXPAND, 6);
    
    $self->{sizer_tag_checks} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_tags}->Add($self->{sizer_tag_checks}, 0, wxALL|wxEXPAND, 6);
    
    $self->{chk_aggressive} = Wx::CheckBox->new($self->{box_tags}->GetStaticBox(), wxID_ANY, "Aggressive");
    $self->{sizer_tag_checks}->Add($self->{chk_aggressive}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_microchip} = Wx::CheckBox->new($self->{box_tags}->GetStaticBox(), wxID_ANY, "Microchip");
    $self->{sizer_tag_checks}->Add($self->{chk_microchip}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{chk_vip} = Wx::CheckBox->new($self->{box_tags}->GetStaticBox(), wxID_ANY, "VIP");
    $self->{sizer_tag_checks}->Add($self->{chk_vip}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{chk_do_not_call} = Wx::CheckBox->new($self->{box_tags}->GetStaticBox(), wxID_ANY, "Do not call");
    $self->{sizer_tag_checks}->Add($self->{chk_do_not_call}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{txt_tags_notes} = Wx::TextCtrl->new($self->{box_tags}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_tags}->Add($self->{txt_tags_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{tab_medical} = Wx::Panel->new($self->{nb_work}, wxID_ANY);
    $self->{nb_work}->AddPage($self->{tab_medical}, "Medical");
    
    $self->{sizer_med_tab} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_med_inner} = Wx::Notebook->new($self->{tab_medical}, wxID_ANY);
    $self->{sizer_med_tab}->Add($self->{nb_med_inner}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_soap} = Wx::Panel->new($self->{nb_med_inner}, wxID_ANY);
    $self->{nb_med_inner}->AddPage($self->{med_soap}, "SOAP");
    
    $self->{sizer_soap} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_soap_hdr} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{med_soap}, wxID_ANY, "Visit"), wxHORIZONTAL);
    $self->{sizer_soap}->Add($self->{box_soap_hdr}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_visit_type = Wx::StaticText->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, "Type");
    $self->{box_soap_hdr}->Add($lbl_visit_type, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{choice_visit} = Wx::Choice->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Exam", "Recheck", "Surgery", "Dental", "Drop-off"], );
    $self->{choice_visit}->SetSelection(0);
    $self->{box_soap_hdr}->Add($self->{choice_visit}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_consent} = Wx::CheckBox->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, "Consent signed");
    $self->{box_soap_hdr}->Add($self->{chk_consent}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{box_soap_hdr}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_soap_save} = Wx::Button->new($self->{box_soap_hdr}->GetStaticBox(), wxID_ANY, "Save");
    $self->{box_soap_hdr}->Add($self->{btn_soap_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_soap} = Wx::TextCtrl->new($self->{med_soap}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap}->Add($self->{txt_soap}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_rx} = Wx::Panel->new($self->{nb_med_inner}, wxID_ANY);
    $self->{nb_med_inner}->AddPage($self->{med_rx}, "Prescriptions");
    
    $self->{sizer_rx} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_rx} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{med_rx}, wxID_ANY, "Prescription Entry"), wxVERTICAL);
    $self->{sizer_rx}->Add($self->{box_rx}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_rx} = Wx::FlexGridSizer->new(0, 4, 6, 10);
    $self->{box_rx}->Add($self->{grid_rx}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_drug = Wx::StaticText->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "Drug");
    $self->{grid_rx}->Add($lbl_drug, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_drug} = Wx::TextCtrl->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rx}->Add($self->{txt_drug}, 1, wxEXPAND, 0);
    
    my $lbl_sig = Wx::StaticText->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "Sig");
    $self->{grid_rx}->Add($lbl_sig, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_sig} = Wx::TextCtrl->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rx}->Add($self->{txt_sig}, 1, wxEXPAND, 0);
    
    my $lbl_refills = Wx::StaticText->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "Refills");
    $self->{grid_rx}->Add($lbl_refills, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_refills} = Wx::TextCtrl->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rx}->Add($self->{txt_refills}, 1, wxEXPAND, 0);
    
    my $lbl_disp = Wx::StaticText->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "Dispense");
    $self->{grid_rx}->Add($lbl_disp, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_dispense} = Wx::TextCtrl->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_rx}->Add($self->{txt_dispense}, 1, wxEXPAND, 0);
    
    $self->{sizer_rx_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_rx}->Add($self->{sizer_rx_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_rx_add} = Wx::Button->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "Add");
    $self->{sizer_rx_btns}->Add($self->{btn_rx_add}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_rx_print} = Wx::Button->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "Print");
    $self->{sizer_rx_btns}->Add($self->{btn_rx_print}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_rx_label} = Wx::Button->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "Label");
    $self->{sizer_rx_btns}->Add($self->{btn_rx_label}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_rx_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_rx_controlled} = Wx::CheckBox->new($self->{box_rx}->GetStaticBox(), wxID_ANY, "Controlled");
    $self->{sizer_rx_btns}->Add($self->{chk_rx_controlled}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rx_history} = Wx::TextCtrl->new($self->{med_rx}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_rx}->Add($self->{txt_rx_history}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_labs} = Wx::Panel->new($self->{nb_med_inner}, wxID_ANY);
    $self->{nb_med_inner}->AddPage($self->{med_labs}, "Labs");
    
    $self->{sizer_labs} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_labs} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{med_labs}, wxID_ANY, "Lab Requests (no table)"), wxVERTICAL);
    $self->{sizer_labs}->Add($self->{box_labs}, 0, wxALL|wxEXPAND, 6);
    
    $self->{sizer_labs_chk} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_labs}->Add($self->{sizer_labs_chk}, 0, wxALL|wxEXPAND, 6);
    
    $self->{chk_cbc} = Wx::CheckBox->new($self->{box_labs}->GetStaticBox(), wxID_ANY, "CBC");
    $self->{sizer_labs_chk}->Add($self->{chk_cbc}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_chem} = Wx::CheckBox->new($self->{box_labs}->GetStaticBox(), wxID_ANY, "Chemistry");
    $self->{sizer_labs_chk}->Add($self->{chk_chem}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{chk_ua} = Wx::CheckBox->new($self->{box_labs}->GetStaticBox(), wxID_ANY, "Urinalysis");
    $self->{sizer_labs_chk}->Add($self->{chk_ua}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{chk_hwtest} = Wx::CheckBox->new($self->{box_labs}->GetStaticBox(), wxID_ANY, "HW Test");
    $self->{sizer_labs_chk}->Add($self->{chk_hwtest}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{txt_labs_notes} = Wx::TextCtrl->new($self->{box_labs}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_labs}->Add($self->{txt_labs_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_imaging} = Wx::Panel->new($self->{nb_med_inner}, wxID_ANY);
    $self->{nb_med_inner}->AddPage($self->{med_imaging}, "Imaging");
    
    $self->{sizer_img} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_img} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{med_imaging}, wxID_ANY, "Imaging Orders (no table)"), wxVERTICAL);
    $self->{sizer_img}->Add($self->{box_img}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_img} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{box_img}->Add($self->{grid_img}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_img_type = Wx::StaticText->new($self->{box_img}->GetStaticBox(), wxID_ANY, "Type");
    $self->{grid_img}->Add($lbl_img_type, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_img} = Wx::Choice->new($self->{box_img}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Radiographs", "Ultrasound", "Dental"], );
    $self->{choice_img}->SetSelection(0);
    $self->{grid_img}->Add($self->{choice_img}, 1, wxEXPAND, 0);
    
    my $lbl_img_area = Wx::StaticText->new($self->{box_img}->GetStaticBox(), wxID_ANY, "Area");
    $self->{grid_img}->Add($lbl_img_area, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_img_area} = Wx::TextCtrl->new($self->{box_img}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_img}->Add($self->{txt_img_area}, 1, wxEXPAND, 0);
    
    $self->{txt_img_notes} = Wx::TextCtrl->new($self->{box_img}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_img}->Add($self->{txt_img_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{tab_schedule} = Wx::Panel->new($self->{nb_work}, wxID_ANY);
    $self->{nb_work}->AddPage($self->{tab_schedule}, "Schedule");
    
    $self->{sizer_sched_tab} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_sched_controls} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{tab_schedule}, wxID_ANY, "Schedule"), wxHORIZONTAL);
    $self->{sizer_sched_tab}->Add($self->{box_sched_controls}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_sched_date = Wx::StaticText->new($self->{box_sched_controls}->GetStaticBox(), wxID_ANY, "Date");
    $self->{box_sched_controls}->Add($lbl_sched_date, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{txt_sched_date} = Wx::TextCtrl->new($self->{box_sched_controls}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_sched_date}->SetMinSize(Wx::Size->new(120,26));
    $self->{box_sched_controls}->Add($self->{txt_sched_date}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_sched_pick} = Wx::Button->new($self->{box_sched_controls}->GetStaticBox(), wxID_ANY, "...");
    $self->{btn_sched_pick}->SetMinSize(Wx::Size->new(28,22));
    $self->{box_sched_controls}->Add($self->{btn_sched_pick}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{chk_show_canceled} = Wx::CheckBox->new($self->{box_sched_controls}->GetStaticBox(), wxID_ANY, "Show canceled");
    $self->{box_sched_controls}->Add($self->{chk_show_canceled}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{box_sched_controls}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_sched_new} = Wx::Button->new($self->{box_sched_controls}->GetStaticBox(), wxID_ANY, "New Appt");
    $self->{box_sched_controls}->Add($self->{btn_sched_new}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{nb_sched_inner} = Wx::Notebook->new($self->{tab_schedule}, wxID_ANY);
    $self->{sizer_sched_tab}->Add($self->{nb_sched_inner}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sched_grid} = Wx::Panel->new($self->{nb_sched_inner}, wxID_ANY);
    $self->{nb_sched_inner}->AddPage($self->{sched_grid}, "Grid");
    
    $self->{sizer_sched_grid} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_schedule} = Wx::ListCtrl->new($self->{sched_grid}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_sched_grid}->Add($self->{list_schedule}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sizer_sched_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_sched_grid}->Add($self->{sizer_sched_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_sched_checkin} = Wx::Button->new($self->{sched_grid}, wxID_ANY, "Check-in");
    $self->{sizer_sched_btns}->Add($self->{btn_sched_checkin}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_sched_checkout} = Wx::Button->new($self->{sched_grid}, wxID_ANY, "Checkout");
    $self->{sizer_sched_btns}->Add($self->{btn_sched_checkout}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_sched_cancel} = Wx::Button->new($self->{sched_grid}, wxID_ANY, "Cancel");
    $self->{sizer_sched_btns}->Add($self->{btn_sched_cancel}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_sched_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    my $lbl_sched_status = Wx::StaticText->new($self->{sched_grid}, wxID_ANY, "0 conflicts");
    $self->{sizer_sched_btns}->Add($lbl_sched_status, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sched_details} = Wx::Panel->new($self->{nb_sched_inner}, wxID_ANY);
    $self->{nb_sched_inner}->AddPage($self->{sched_details}, "Details");
    
    $self->{sizer_sched_details} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_sched_details} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{sizer_sched_details}->Add($self->{grid_sched_details}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_appt_reason = Wx::StaticText->new($self->{sched_details}, wxID_ANY, "Reason");
    $self->{grid_sched_details}->Add($lbl_appt_reason, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_appt_reason} = Wx::TextCtrl->new($self->{sched_details}, wxID_ANY, "");
    $self->{grid_sched_details}->Add($self->{txt_appt_reason}, 1, wxEXPAND, 0);
    
    my $lbl_appt_room = Wx::StaticText->new($self->{sched_details}, wxID_ANY, "Room");
    $self->{grid_sched_details}->Add($lbl_appt_room, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_appt_room} = Wx::Choice->new($self->{sched_details}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["1", "2", "3", "4"], );
    $self->{choice_appt_room}->SetSelection(0);
    $self->{grid_sched_details}->Add($self->{choice_appt_room}, 1, wxEXPAND, 0);
    
    $self->{txt_appt_notes} = Wx::TextCtrl->new($self->{sched_details}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_sched_details}->Add($self->{txt_appt_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{tab_billing} = Wx::Panel->new($self->{nb_work}, wxID_ANY);
    $self->{nb_work}->AddPage($self->{tab_billing}, "Billing");
    
    $self->{sizer_bill_tab} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_bill_inner} = Wx::Notebook->new($self->{tab_billing}, wxID_ANY);
    $self->{sizer_bill_tab}->Add($self->{nb_bill_inner}, 1, wxALL|wxEXPAND, 6);
    
    $self->{bill_invoice} = Wx::Panel->new($self->{nb_bill_inner}, wxID_ANY);
    $self->{nb_bill_inner}->AddPage($self->{bill_invoice}, "Invoice");
    
    $self->{sizer_invoice} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_post} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{bill_invoice}, wxID_ANY, "Post Charges"), wxVERTICAL);
    $self->{sizer_invoice}->Add($self->{box_post}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_post} = Wx::FlexGridSizer->new(0, 4, 6, 10);
    $self->{box_post}->Add($self->{grid_post}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_code = Wx::StaticText->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Code");
    $self->{grid_post}->Add($lbl_code, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_code} = Wx::TextCtrl->new($self->{box_post}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_post}->Add($self->{txt_code}, 1, wxEXPAND, 0);
    
    my $lbl_qty = Wx::StaticText->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Qty");
    $self->{grid_post}->Add($lbl_qty, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_qty} = Wx::TextCtrl->new($self->{box_post}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_post}->Add($self->{txt_qty}, 1, wxEXPAND, 0);
    
    my $lbl_price = Wx::StaticText->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Price");
    $self->{grid_post}->Add($lbl_price, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_price} = Wx::TextCtrl->new($self->{box_post}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_post}->Add($self->{txt_price}, 1, wxEXPAND, 0);
    
    my $lbl_tax = Wx::StaticText->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Tax");
    $self->{grid_post}->Add($lbl_tax, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_tax} = Wx::CheckBox->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Taxable");
    $self->{grid_post}->Add($self->{chk_tax}, 1, wxEXPAND, 0);
    
    $self->{sizer_post_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_post}->Add($self->{sizer_post_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_post} = Wx::Button->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Post");
    $self->{sizer_post_btns}->Add($self->{btn_post}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_payment} = Wx::Button->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Payment");
    $self->{sizer_post_btns}->Add($self->{btn_payment}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_refund} = Wx::Button->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Refund");
    $self->{sizer_post_btns}->Add($self->{btn_refund}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_post_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    my $lbl_total = Wx::StaticText->new($self->{box_post}->GetStaticBox(), wxID_ANY, "Total: \$0.00");
    $self->{sizer_post_btns}->Add($lbl_total, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_invoice_notes} = Wx::TextCtrl->new($self->{bill_invoice}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_invoice}->Add($self->{txt_invoice_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{bill_ledger} = Wx::Panel->new($self->{nb_bill_inner}, wxID_ANY);
    $self->{nb_bill_inner}->AddPage($self->{bill_ledger}, "Ledger");
    
    $self->{sizer_ledger} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_ledger} = Wx::ListCtrl->new($self->{bill_ledger}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_ledger}->Add($self->{list_ledger}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sizer_ledger_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_ledger}->Add($self->{sizer_ledger_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_ledger_print} = Wx::Button->new($self->{bill_ledger}, wxID_ANY, "Print");
    $self->{sizer_ledger_btns}->Add($self->{btn_ledger_print}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_ledger_export} = Wx::Button->new($self->{bill_ledger}, wxID_ANY, "Export");
    $self->{sizer_ledger_btns}->Add($self->{btn_ledger_export}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_ledger_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{chk_show_voids} = Wx::CheckBox->new($self->{bill_ledger}, wxID_ANY, "Show voids");
    $self->{sizer_ledger_btns}->Add($self->{chk_show_voids}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{bill_estimate} = Wx::Panel->new($self->{nb_bill_inner}, wxID_ANY);
    $self->{nb_bill_inner}->AddPage($self->{bill_estimate}, "Estimate");
    
    $self->{sizer_est} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_est} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{bill_estimate}, wxID_ANY, "Estimate Builder (no table)"), wxVERTICAL);
    $self->{sizer_est}->Add($self->{box_est}, 0, wxALL|wxEXPAND, 6);
    
    $self->{txt_est} = Wx::TextCtrl->new($self->{box_est}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{box_est}->Add($self->{txt_est}, 1, wxALL|wxEXPAND, 6);
    
    $self->{tab_admin} = Wx::Panel->new($self->{nb_work}, wxID_ANY);
    $self->{nb_work}->AddPage($self->{tab_admin}, "Admin");
    
    $self->{sizer_admin} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_admin} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{tab_admin}, wxID_ANY, "Configuration"), wxVERTICAL);
    $self->{sizer_admin}->Add($self->{box_admin}, 0, wxALL|wxEXPAND, 6);
    
    $self->{nb_admin_inner} = Wx::Notebook->new($self->{tab_admin}, wxID_ANY);
    $self->{box_admin}->Add($self->{nb_admin_inner}, 0, wxALL|wxEXPAND, 6);
    
    $self->{adm_users} = Wx::Panel->new($self->{nb_admin_inner}, wxID_ANY);
    $self->{nb_admin_inner}->AddPage($self->{adm_users}, "Users");
    
    $self->{sizer_adm_users} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_users} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{sizer_adm_users}->Add($self->{grid_users}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_role = Wx::StaticText->new($self->{adm_users}, wxID_ANY, "Role");
    $self->{grid_users}->Add($lbl_role, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_role} = Wx::Choice->new($self->{adm_users}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Doctor", "Tech", "Front Desk", "Admin"], );
    $self->{choice_role}->SetSelection(0);
    $self->{grid_users}->Add($self->{choice_role}, 1, wxEXPAND, 0);
    
    my $lbl_perm = Wx::StaticText->new($self->{adm_users}, wxID_ANY, "Permissions");
    $self->{grid_users}->Add($lbl_perm, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_perm} = Wx::TextCtrl->new($self->{adm_users}, wxID_ANY, "");
    $self->{grid_users}->Add($self->{txt_perm}, 1, wxEXPAND, 0);
    
    $self->{txt_user_notes} = Wx::TextCtrl->new($self->{adm_users}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_adm_users}->Add($self->{txt_user_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{adm_codes} = Wx::Panel->new($self->{nb_admin_inner}, wxID_ANY);
    $self->{nb_admin_inner}->AddPage($self->{adm_codes}, "Codes");
    
    $self->{sizer_adm_codes} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_codes} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{sizer_adm_codes}->Add($self->{grid_codes}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_code_set = Wx::StaticText->new($self->{adm_codes}, wxID_ANY, "Code Set");
    $self->{grid_codes}->Add($lbl_code_set, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_codeset} = Wx::Choice->new($self->{adm_codes}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Services", "Inventory", "Reminders", "Labs"], );
    $self->{choice_codeset}->SetSelection(0);
    $self->{grid_codes}->Add($self->{choice_codeset}, 1, wxEXPAND, 0);
    
    $self->{txt_codes_blob} = Wx::TextCtrl->new($self->{adm_codes}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_adm_codes}->Add($self->{txt_codes_blob}, 1, wxALL|wxEXPAND, 6);
    
    $self->{adm_integrations} = Wx::Panel->new($self->{nb_admin_inner}, wxID_ANY);
    $self->{nb_admin_inner}->AddPage($self->{adm_integrations}, "Integrations");
    
    $self->{sizer_adm_int} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_int} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{sizer_adm_int}->Add($self->{grid_int}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_api = Wx::StaticText->new($self->{adm_integrations}, wxID_ANY, "API Endpoint");
    $self->{grid_int}->Add($lbl_api, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_api} = Wx::TextCtrl->new($self->{adm_integrations}, wxID_ANY, "");
    $self->{grid_int}->Add($self->{txt_api}, 1, wxEXPAND, 0);
    
    my $lbl_token = Wx::StaticText->new($self->{adm_integrations}, wxID_ANY, "Token");
    $self->{grid_int}->Add($lbl_token, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_token} = Wx::TextCtrl->new($self->{adm_integrations}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    $self->{grid_int}->Add($self->{txt_token}, 1, wxEXPAND, 0);
    
    $self->{sizer_int_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_adm_int}->Add($self->{sizer_int_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_test_api} = Wx::Button->new($self->{adm_integrations}, wxID_ANY, "Test");
    $self->{sizer_int_btns}->Add($self->{btn_test_api}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_int_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_save_api} = Wx::Button->new($self->{adm_integrations}, wxID_ANY, "Save");
    $self->{sizer_int_btns}->Add($self->{btn_save_api}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_int_log} = Wx::TextCtrl->new($self->{adm_integrations}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_adm_int}->Add($self->{txt_int_log}, 1, wxALL|wxEXPAND, 6);
    
    my $lbl_status = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "F2 Find \N{U+2022} F3 New \N{U+2022} F6 Schedule \N{U+2022} F9 Billing \N{U+2022} Esc Close");
    $self->{sizer_root}->Add($lbl_status, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{grid_int}->AddGrowableCol(1);
    
    $self->{adm_integrations}->SetSizer($self->{sizer_adm_int});
    
    $self->{grid_codes}->AddGrowableCol(1);
    
    $self->{adm_codes}->SetSizer($self->{sizer_adm_codes});
    
    $self->{grid_users}->AddGrowableCol(1);
    
    $self->{adm_users}->SetSizer($self->{sizer_adm_users});
    
    $self->{tab_admin}->SetSizer($self->{sizer_admin});
    
    $self->{bill_estimate}->SetSizer($self->{sizer_est});
    
    $self->{bill_ledger}->SetSizer($self->{sizer_ledger});
    
    $self->{grid_post}->AddGrowableCol(3);
    
    $self->{bill_invoice}->SetSizer($self->{sizer_invoice});
    
    $self->{tab_billing}->SetSizer($self->{sizer_bill_tab});
    
    $self->{grid_sched_details}->AddGrowableCol(1);
    
    $self->{sched_details}->SetSizer($self->{sizer_sched_details});
    
    $self->{sched_grid}->SetSizer($self->{sizer_sched_grid});
    
    $self->{tab_schedule}->SetSizer($self->{sizer_sched_tab});
    
    $self->{grid_img}->AddGrowableCol(1);
    
    $self->{med_imaging}->SetSizer($self->{sizer_img});
    
    $self->{med_labs}->SetSizer($self->{sizer_labs});
    
    $self->{grid_rx}->AddGrowableCol(3);
    
    $self->{med_rx}->SetSizer($self->{sizer_rx});
    
    $self->{med_soap}->SetSizer($self->{sizer_soap});
    
    $self->{tab_medical}->SetSizer($self->{sizer_med_tab});
    
    $self->{pat_tags}->SetSizer($self->{sizer_tags});
    
    $self->{grid_rem}->AddGrowableCol(1);
    
    $self->{pat_reminders}->SetSizer($self->{sizer_rem});
    
    $self->{grid_contacts}->AddGrowableCol(1);
    
    $self->{pat_contacts}->SetSizer($self->{sizer_contacts});
    
    $self->{grid_pat}->AddGrowableCol(3);
    
    $self->{pat_overview}->SetSizer($self->{sizer_pat_overview});
    
    $self->{tab_patients}->SetSizer($self->{sizer_pat_tab});
    
    $self->{grid_dash}->AddGrowableCol(3);
    
    $self->{tab_dashboard}->SetSizer($self->{sizer_dash});
    
    $self->{grid_ctx}->AddGrowableCol(5);
    
    $self->{panel_right}->SetSizer($self->{sizer_right});
    
    $self->{grid_left_flags}->AddGrowableCol(1);
    
    $self->{panel_left}->SetSizer($self->{sizer_left});
    
    $self->{split_main}->SplitVertically($self->{panel_left}, $self->{panel_right}, );
    
    $self->{panel_root}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class VetCRMDenseFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_vetcrm = VetCRMDenseFrame->new();

    $self->SetTopWindow($frame_vetcrm);
    $frame_vetcrm->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
