#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Fri Feb 13 21:39:23 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package AvimarkMainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: AvimarkMainFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1400, 900));
    $self->SetTitle("AVImark-ish Vet CRM - Prototype");
    
    

    # Menu Bar

    $self->{frame_avimark_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $self->{menu_file} = Wx::Menu->new();
    $self->{mnu_file_open} = $self->{menu_file}->Append(wxID_ANY, "Open...", "");
    $self->{mnu_file_backup} = $self->{menu_file}->Append(wxID_ANY, "Backup / Export...", "");
    $self->{mnu_file_sep1} = $self->{menu_file}->Append(wxID_ANY, "---", "");
    $self->{mnu_file_exit} = $self->{menu_file}->Append(wxID_ANY, "Exit", "");
    $self->{frame_avimark_menubar}->Append($self->{menu_file}, "File");
    $self->{menu_clients} = Wx::Menu->new();
    $self->{mnu_clients_find} = $self->{menu_clients}->Append(wxID_ANY, "Find Client...", "");
    $self->{mnu_clients_new} = $self->{menu_clients}->Append(wxID_ANY, "New Client", "");
    $self->{mnu_clients_edit} = $self->{menu_clients}->Append(wxID_ANY, "Edit Client", "");
    $self->{frame_avimark_menubar}->Append($self->{menu_clients}, "Clients");
    $self->{menu_patients} = Wx::Menu->new();
    $self->{mnu_patients_find} = $self->{menu_patients}->Append(wxID_ANY, "Find Patient...", "");
    $self->{mnu_patients_new} = $self->{menu_patients}->Append(wxID_ANY, "New Patient", "");
    $self->{mnu_patients_edit} = $self->{menu_patients}->Append(wxID_ANY, "Edit Patient", "");
    $self->{frame_avimark_menubar}->Append($self->{menu_patients}, "Patients");
    $self->{menu_medical} = Wx::Menu->new();
    $self->{mnu_med_new_visit} = $self->{menu_medical}->Append(wxID_ANY, "New Visit", "");
    $self->{mnu_med_open} = $self->{menu_medical}->Append(wxID_ANY, "Open Medical Record", "");
    $self->{mnu_med_sep1} = $self->{menu_medical}->Append(wxID_ANY, "---", "");
    $self->{mnu_med_rx} = $self->{menu_medical}->Append(wxID_ANY, "Prescriptions", "");
    $self->{mnu_med_labs} = $self->{menu_medical}->Append(wxID_ANY, "Labs / Diagnostics", "");
    $self->{frame_avimark_menubar}->Append($self->{menu_medical}, "Medical");
    $self->{menu_billing} = Wx::Menu->new();
    $self->{mnu_bill_new} = $self->{menu_billing}->Append(wxID_ANY, "New Invoice", "");
    $self->{mnu_bill_pay} = $self->{menu_billing}->Append(wxID_ANY, "Take Payment", "");
    $self->{mnu_bill_statements} = $self->{menu_billing}->Append(wxID_ANY, "Statements", "");
    $self->{frame_avimark_menubar}->Append($self->{menu_billing}, "Billing");
    $self->{menu_reports} = Wx::Menu->new();
    $self->{mnu_reports_run} = $self->{menu_reports}->Append(wxID_ANY, "Run Report...", "");
    $self->{mnu_reports_export} = $self->{menu_reports}->Append(wxID_ANY, "Export...", "");
    $self->{frame_avimark_menubar}->Append($self->{menu_reports}, "Reports");
    $self->{menu_settings} = Wx::Menu->new();
    $self->{mnu_settings_practice} = $self->{menu_settings}->Append(wxID_ANY, "Practice Setup...", "");
    $self->{mnu_settings_users} = $self->{menu_settings}->Append(wxID_ANY, "Users / Roles...", "");
    $self->{mnu_settings_integrations} = $self->{menu_settings}->Append(wxID_ANY, "Integrations...", "");
    $self->{mnu_settings_sep1} = $self->{menu_settings}->Append(wxID_ANY, "---", "");
    $self->{mnu_settings_advanced} = $self->{menu_settings}->Append(wxID_ANY, "Advanced...", "");
    $self->{frame_avimark_menubar}->Append($self->{menu_settings}, "Settings");
    $self->{menu_help} = Wx::Menu->new();
    $self->{mnu_help_quickstart} = $self->{menu_help}->Append(wxID_ANY, "Quick Start", "");
    $self->{mnu_help_about} = $self->{menu_help}->Append(wxID_ANY, "About", "");
    $self->{frame_avimark_menubar}->Append($self->{menu_help}, "Help");
    $self->SetMenuBar($self->{frame_avimark_menubar});
    
    # Menu Bar end

    
    $self->{panel_root} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_context} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_root}, wxID_ANY, "Active Context"), wxHORIZONTAL);
    $self->{sizer_root}->Add($self->{box_context}, 0, wxALL|wxEXPAND, 8);
    
    my $lbl_active_client = Wx::StaticText->new($self->{box_context}->GetStaticBox(), wxID_ANY, "Client");
    $self->{box_context}->Add($lbl_active_client, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{txt_active_client} = Wx::TextCtrl->new($self->{box_context}->GetStaticBox(), wxID_ANY, "Smith, Jane (C# 10482)");
    $self->{txt_active_client}->SetMinSize(Wx::Size->new(-1,30));
    $self->{box_context}->Add($self->{txt_active_client}, 1, wxALL|wxEXPAND, 6);
    
    my $lbl_active_patient = Wx::StaticText->new($self->{box_context}->GetStaticBox(), wxID_ANY, "Patient");
    $self->{box_context}->Add($lbl_active_patient, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{txt_active_patient} = Wx::TextCtrl->new($self->{box_context}->GetStaticBox(), wxID_ANY, "Buddy (Canine, M, 6y)");
    $self->{txt_active_patient}->SetMinSize(Wx::Size->new(-1,30));
    $self->{box_context}->Add($self->{txt_active_patient}, 1, wxALL|wxEXPAND, 6);
    
    $self->{btn_refine} = Wx::Button->new($self->{box_context}->GetStaticBox(), wxID_ANY, "refine");
    $self->{box_context}->Add($self->{btn_refine}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_reset} = Wx::Button->new($self->{box_context}->GetStaticBox(), wxID_ANY, "reset");
    $self->{box_context}->Add($self->{btn_reset}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{nb_main} = Wx::Notebook->new($self->{panel_root}, wxID_ANY);
    $self->{sizer_root}->Add($self->{nb_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{page_dashboard} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_dashboard}, "Dashboard");
    
    $self->{sizer_dash} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_dash = Wx::StaticText->new($self->{page_dashboard}, wxID_ANY, "Dashboard (today, tasks, alerts, quick actions)");
    $self->{sizer_dash}->Add($lbl_dash, 0, wxALL|wxEXPAND, 8);
    
    $self->{split_dash} = Wx::SplitterWindow->new($self->{page_dashboard}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_dash}->SetMinimumPaneSize(20);
    $self->{sizer_dash}->Add($self->{split_dash}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{panel_dash_left} = Wx::Panel->new($self->{split_dash}, wxID_ANY);
    
    $self->{sizer_dash_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_today} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_dash_left}, wxID_ANY, "Today"), wxVERTICAL);
    $self->{sizer_dash_left}->Add($self->{box_today}, 0, wxALL|wxEXPAND, 6);
    
    $self->{list_today} = Wx::ListCtrl->new($self->{box_today}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_today}->Add($self->{list_today}, 1, wxALL|wxEXPAND, 6);
    
    $self->{box_alerts} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_dash_left}, wxID_ANY, "Alerts"), wxVERTICAL);
    $self->{sizer_dash_left}->Add($self->{box_alerts}, 0, wxALL|wxEXPAND, 6);
    
    $self->{list_alerts} = Wx::ListCtrl->new($self->{box_alerts}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_alerts}->Add($self->{list_alerts}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_dash_right} = Wx::Panel->new($self->{split_dash}, wxID_ANY);
    
    $self->{sizer_dash_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_tasks} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_dash_right}, wxID_ANY, "Tasks / Follow-ups"), wxVERTICAL);
    $self->{sizer_dash_right}->Add($self->{box_tasks}, 0, wxALL|wxEXPAND, 6);
    
    $self->{list_tasks} = Wx::ListCtrl->new($self->{box_tasks}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_tasks}->Add($self->{list_tasks}, 1, wxALL|wxEXPAND, 6);
    
    $self->{box_quick_actions} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_dash_right}, wxID_ANY, "Quick"), wxHORIZONTAL);
    $self->{sizer_dash_right}->Add($self->{box_quick_actions}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_q_new_appt} = Wx::Button->new($self->{box_quick_actions}->GetStaticBox(), wxID_ANY, "New Appt");
    $self->{box_quick_actions}->Add($self->{btn_q_new_appt}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_q_new_visit} = Wx::Button->new($self->{box_quick_actions}->GetStaticBox(), wxID_ANY, "New Visit");
    $self->{box_quick_actions}->Add($self->{btn_q_new_visit}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_q_invoice} = Wx::Button->new($self->{box_quick_actions}->GetStaticBox(), wxID_ANY, "Invoice");
    $self->{box_quick_actions}->Add($self->{btn_q_invoice}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_quick_actions}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_q_refresh} = Wx::Button->new($self->{box_quick_actions}->GetStaticBox(), wxID_ANY, "Refresh");
    $self->{box_quick_actions}->Add($self->{btn_q_refresh}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{page_scheduler} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_scheduler}, "Scheduler");
    
    $self->{sizer_sched_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{split_sched} = Wx::SplitterWindow->new($self->{page_scheduler}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_sched}->SetMinimumPaneSize(20);
    $self->{sizer_sched_root}->Add($self->{split_sched}, 1, wxEXPAND, 0);
    
    $self->{panel_sched_left} = Wx::Panel->new($self->{split_sched}, wxID_ANY);
    
    $self->{sizer_sched_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_sched_filters} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_sched_left}, wxID_ANY, "Schedule Filters"), wxVERTICAL);
    $self->{sizer_sched_left}->Add($self->{box_sched_filters}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_sched_filters} = Wx::FlexGridSizer->new(0, 4, 6, 8);
    $self->{box_sched_filters}->Add($self->{grid_sched_filters}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_sched_date = Wx::StaticText->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Date");
    $self->{grid_sched_filters}->Add($lbl_sched_date, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_sched_date} = Wx::TextCtrl->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_sched_date}->SetMinSize(Wx::Size->new(110,-1));
    $self->{grid_sched_filters}->Add($self->{txt_sched_date}, 1, wxEXPAND, 0);
    
    my $lbl_sched_provider = Wx::StaticText->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Provider");
    $self->{grid_sched_filters}->Add($lbl_sched_provider, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_sched_provider} = Wx::Choice->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["All", "Dr A", "Dr B", "Tech 1", "Tech 2"], );
    $self->{choice_sched_provider}->SetSelection(0);
    $self->{grid_sched_filters}->Add($self->{choice_sched_provider}, 1, wxEXPAND, 0);
    
    my $lbl_sched_type = Wx::StaticText->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Type");
    $self->{grid_sched_filters}->Add($lbl_sched_type, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_sched_type} = Wx::Choice->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["All", "Wellness", "Sick", "Recheck", "Surgery", "Tech Visit"], );
    $self->{choice_sched_type}->SetSelection(0);
    $self->{grid_sched_filters}->Add($self->{choice_sched_type}, 1, wxEXPAND, 0);
    
    my $lbl_sched_status = Wx::StaticText->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Status");
    $self->{grid_sched_filters}->Add($lbl_sched_status, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_sched_status} = Wx::Choice->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["All", "Scheduled", "Checked-In", "In Room", "Completed", "No Show"], );
    $self->{choice_sched_status}->SetSelection(0);
    $self->{grid_sched_filters}->Add($self->{choice_sched_status}, 1, wxEXPAND, 0);
    
    $self->{sizer_sched_actions} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_sched_filters}->Add($self->{sizer_sched_actions}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_sched_search} = Wx::Button->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Search");
    $self->{sizer_sched_actions}->Add($self->{btn_sched_search}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_sched_new} = Wx::Button->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "New Appt...");
    $self->{sizer_sched_actions}->Add($self->{btn_sched_new}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_sched_checkin} = Wx::Button->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Check-In");
    $self->{sizer_sched_actions}->Add($self->{btn_sched_checkin}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_sched_checkout} = Wx::Button->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Check-Out");
    $self->{sizer_sched_actions}->Add($self->{btn_sched_checkout}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_sched_actions}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_sched_print} = Wx::Button->new($self->{box_sched_filters}->GetStaticBox(), wxID_ANY, "Print");
    $self->{sizer_sched_actions}->Add($self->{btn_sched_print}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_sched_results} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_sched_left}, wxID_ANY, "Appointments"), wxVERTICAL);
    $self->{sizer_sched_left}->Add($self->{box_sched_results}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{list_sched} = Wx::ListCtrl->new($self->{box_sched_results}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_sched_results}->Add($self->{list_sched}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_sched_right} = Wx::Panel->new($self->{split_sched}, wxID_ANY);
    
    $self->{sizer_sched_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_appt_detail} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_sched_right}, wxID_ANY, "Appointment Detail"), wxVERTICAL);
    $self->{sizer_sched_right}->Add($self->{box_appt_detail}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_appt_detail} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_appt_detail}->Add($self->{grid_appt_detail}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_appt_time = Wx::StaticText->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "Time");
    $self->{grid_appt_detail}->Add($lbl_appt_time, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_appt_time} = Wx::TextCtrl->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_appt_detail}->Add($self->{txt_appt_time}, 1, wxEXPAND, 0);
    
    my $lbl_appt_room = Wx::StaticText->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "Room");
    $self->{grid_appt_detail}->Add($lbl_appt_room, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_appt_room} = Wx::TextCtrl->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_appt_detail}->Add($self->{txt_appt_room}, 1, wxEXPAND, 0);
    
    my $lbl_appt_reason = Wx::StaticText->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "Reason");
    $self->{grid_appt_detail}->Add($lbl_appt_reason, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_appt_reason} = Wx::TextCtrl->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_appt_detail}->Add($self->{txt_appt_reason}, 1, wxEXPAND, 0);
    
    $self->{sizer_appt_flags} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_appt_detail}->Add($self->{sizer_appt_flags}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{chk_appt_confirmed} = Wx::CheckBox->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "Confirmed");
    $self->{sizer_appt_flags}->Add($self->{chk_appt_confirmed}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_appt_dropoff} = Wx::CheckBox->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "Drop-off");
    $self->{sizer_appt_flags}->Add($self->{chk_appt_dropoff}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{chk_appt_emergency} = Wx::CheckBox->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "Emergency");
    $self->{sizer_appt_flags}->Add($self->{chk_appt_emergency}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{sizer_appt_flags}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_appt_save} = Wx::Button->new($self->{box_appt_detail}->GetStaticBox(), wxID_ANY, "Save");
    $self->{sizer_appt_flags}->Add($self->{btn_appt_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{nb_sched_bottom} = Wx::Notebook->new($self->{panel_sched_right}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM);
    $self->{sizer_sched_right}->Add($self->{nb_sched_bottom}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{sched_tab_notes} = Wx::Panel->new($self->{nb_sched_bottom}, wxID_ANY);
    $self->{nb_sched_bottom}->AddPage($self->{sched_tab_notes}, "Notes");
    
    $self->{sizer_sched_notes} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_sched_notes} = Wx::TextCtrl->new($self->{sched_tab_notes}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_sched_notes}->Add($self->{txt_sched_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sched_tab_tasks} = Wx::Panel->new($self->{nb_sched_bottom}, wxID_ANY);
    $self->{nb_sched_bottom}->AddPage($self->{sched_tab_tasks}, "Tasks");
    
    $self->{sizer_sched_tasks} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_sched_tasks} = Wx::ListCtrl->new($self->{sched_tab_tasks}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_sched_tasks}->Add($self->{list_sched_tasks}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sched_tab_alerts} = Wx::Panel->new($self->{nb_sched_bottom}, wxID_ANY);
    $self->{nb_sched_bottom}->AddPage($self->{sched_tab_alerts}, "Alerts");
    
    $self->{sizer_sched_alerts} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_sched_alerts} = Wx::ListCtrl->new($self->{sched_tab_alerts}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_sched_alerts}->Add($self->{list_sched_alerts}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sched_tab_charges} = Wx::Panel->new($self->{nb_sched_bottom}, wxID_ANY);
    $self->{nb_sched_bottom}->AddPage($self->{sched_tab_charges}, "Charges");
    
    $self->{sizer_sched_charges} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_sched_charges} = Wx::ListCtrl->new($self->{sched_tab_charges}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_sched_charges}->Add($self->{list_sched_charges}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sizer_sched_charge_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_sched_charges}->Add($self->{sizer_sched_charge_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_charge_add} = Wx::Button->new($self->{sched_tab_charges}, wxID_ANY, "Add");
    $self->{sizer_sched_charge_btns}->Add($self->{btn_charge_add}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_charge_remove} = Wx::Button->new($self->{sched_tab_charges}, wxID_ANY, "Remove");
    $self->{sizer_sched_charge_btns}->Add($self->{btn_charge_remove}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_sched_charge_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_charge_post} = Wx::Button->new($self->{sched_tab_charges}, wxID_ANY, "Post");
    $self->{sizer_sched_charge_btns}->Add($self->{btn_charge_post}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{page_clients} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_clients}, "Clients");
    
    $self->{sizer_clients_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{split_clients} = Wx::SplitterWindow->new($self->{page_clients}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_clients}->SetMinimumPaneSize(20);
    $self->{sizer_clients_root}->Add($self->{split_clients}, 1, wxEXPAND, 0);
    
    $self->{panel_clients_left} = Wx::Panel->new($self->{split_clients}, wxID_ANY);
    
    $self->{sizer_clients_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_client_find} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_clients_left}, wxID_ANY, "Find Client"), wxVERTICAL);
    $self->{sizer_clients_left}->Add($self->{box_client_find}, 0, wxALL|wxEXPAND, 8);
    
    $self->{sizer_client_find_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_client_find}->Add($self->{sizer_client_find_row}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_client_query = Wx::StaticText->new($self->{box_client_find}->GetStaticBox(), wxID_ANY, "Query");
    $self->{sizer_client_find_row}->Add($lbl_client_query, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_client_query} = Wx::TextCtrl->new($self->{box_client_find}->GetStaticBox(), wxID_ANY, "");
    $self->{sizer_client_find_row}->Add($self->{txt_client_query}, 1, wxEXPAND|wxLEFT, 6);
    
    $self->{btn_client_search} = Wx::Button->new($self->{box_client_find}->GetStaticBox(), wxID_ANY, "Search");
    $self->{sizer_client_find_row}->Add($self->{btn_client_search}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_client_find_opts} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_client_find}->Add($self->{sizer_client_find_opts}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{chk_client_active} = Wx::CheckBox->new($self->{box_client_find}->GetStaticBox(), wxID_ANY, "Active only");
    $self->{sizer_client_find_opts}->Add($self->{chk_client_active}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_client_exact} = Wx::CheckBox->new($self->{box_client_find}->GetStaticBox(), wxID_ANY, "Exact");
    $self->{sizer_client_find_opts}->Add($self->{chk_client_exact}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{chk_client_soundex} = Wx::CheckBox->new($self->{box_client_find}->GetStaticBox(), wxID_ANY, "Soundex");
    $self->{sizer_client_find_opts}->Add($self->{chk_client_soundex}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{sizer_client_find_opts}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_client_new} = Wx::Button->new($self->{box_client_find}->GetStaticBox(), wxID_ANY, "New");
    $self->{sizer_client_find_opts}->Add($self->{btn_client_new}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_client_results} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_clients_left}, wxID_ANY, "Clients"), wxVERTICAL);
    $self->{sizer_clients_left}->Add($self->{box_client_results}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{list_clients} = Wx::ListCtrl->new($self->{box_client_results}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_client_results}->Add($self->{list_clients}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_clients_right} = Wx::Panel->new($self->{split_clients}, wxID_ANY);
    
    $self->{sizer_clients_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_client_summary} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_clients_right}, wxID_ANY, "Client Summary"), wxVERTICAL);
    $self->{sizer_clients_right}->Add($self->{box_client_summary}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_client_summary} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_client_summary}->Add($self->{grid_client_summary}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_client_name = Wx::StaticText->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "Name");
    $self->{grid_client_summary}->Add($lbl_client_name, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_client_name} = Wx::TextCtrl->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_client_summary}->Add($self->{txt_client_name}, 1, wxEXPAND, 0);
    
    my $lbl_client_phone = Wx::StaticText->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "Phone");
    $self->{grid_client_summary}->Add($lbl_client_phone, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_client_phone} = Wx::TextCtrl->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_client_summary}->Add($self->{txt_client_phone}, 1, wxEXPAND, 0);
    
    my $lbl_client_email = Wx::StaticText->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "Email");
    $self->{grid_client_summary}->Add($lbl_client_email, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_client_email} = Wx::TextCtrl->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_client_summary}->Add($self->{txt_client_email}, 1, wxEXPAND, 0);
    
    $self->{sizer_client_flags} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_client_summary}->Add($self->{sizer_client_flags}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{chk_client_vip} = Wx::CheckBox->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "VIP");
    $self->{sizer_client_flags}->Add($self->{chk_client_vip}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_client_hold} = Wx::CheckBox->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "Account Hold");
    $self->{sizer_client_flags}->Add($self->{chk_client_hold}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{sizer_client_flags}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_client_save} = Wx::Button->new($self->{box_client_summary}->GetStaticBox(), wxID_ANY, "Save");
    $self->{sizer_client_flags}->Add($self->{btn_client_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{nb_client_bottom} = Wx::Notebook->new($self->{panel_clients_right}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM);
    $self->{sizer_clients_right}->Add($self->{nb_client_bottom}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{client_tab_patients} = Wx::Panel->new($self->{nb_client_bottom}, wxID_ANY);
    $self->{nb_client_bottom}->AddPage($self->{client_tab_patients}, "Patients");
    
    $self->{sizer_client_patients} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_client_patients} = Wx::ListCtrl->new($self->{client_tab_patients}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_client_patients}->Add($self->{list_client_patients}, 1, wxALL|wxEXPAND, 6);
    
    $self->{client_tab_alerts} = Wx::Panel->new($self->{nb_client_bottom}, wxID_ANY);
    $self->{nb_client_bottom}->AddPage($self->{client_tab_alerts}, "Alerts");
    
    $self->{sizer_client_alerts} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_client_alerts} = Wx::ListCtrl->new($self->{client_tab_alerts}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_client_alerts}->Add($self->{list_client_alerts}, 1, wxALL|wxEXPAND, 6);
    
    $self->{client_tab_notes} = Wx::Panel->new($self->{nb_client_bottom}, wxID_ANY);
    $self->{nb_client_bottom}->AddPage($self->{client_tab_notes}, "Notes");
    
    $self->{sizer_client_notes} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_client_notes} = Wx::TextCtrl->new($self->{client_tab_notes}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_client_notes}->Add($self->{txt_client_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{client_tab_docs} = Wx::Panel->new($self->{nb_client_bottom}, wxID_ANY);
    $self->{nb_client_bottom}->AddPage($self->{client_tab_docs}, "Documents");
    
    $self->{sizer_client_docs} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_client_docs} = Wx::ListCtrl->new($self->{client_tab_docs}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_client_docs}->Add($self->{list_client_docs}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_patient} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_patient}, "Patient");
    
    $self->{sizer_patient_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_patient} = Wx::Notebook->new($self->{page_patient}, wxID_ANY);
    $self->{sizer_patient_root}->Add($self->{nb_patient}, 1, wxEXPAND, 0);
    
    $self->{patient_tab_demo} = Wx::Panel->new($self->{nb_patient}, wxID_ANY);
    $self->{nb_patient}->AddPage($self->{patient_tab_demo}, "Demographics");
    
    $self->{sizer_patient_demo} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_patient_demo} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{patient_tab_demo}, wxID_ANY, "Patient"), wxVERTICAL);
    $self->{sizer_patient_demo}->Add($self->{box_patient_demo}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_patient_demo} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_patient_demo}->Add($self->{grid_patient_demo}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_pet_name = Wx::StaticText->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "Name");
    $self->{grid_patient_demo}->Add($lbl_pet_name, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_pet_name} = Wx::TextCtrl->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_patient_demo}->Add($self->{txt_pet_name}, 1, wxEXPAND, 0);
    
    my $lbl_pet_species = Wx::StaticText->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "Species");
    $self->{grid_patient_demo}->Add($lbl_pet_species, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_pet_species} = Wx::Choice->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Canine", "Feline", "Avian", "Exotic"], );
    $self->{choice_pet_species}->SetSelection(0);
    $self->{grid_patient_demo}->Add($self->{choice_pet_species}, 1, wxEXPAND, 0);
    
    my $lbl_pet_dob = Wx::StaticText->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "DOB");
    $self->{grid_patient_demo}->Add($lbl_pet_dob, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_pet_dob} = Wx::TextCtrl->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_patient_demo}->Add($self->{txt_pet_dob}, 1, wxEXPAND, 0);
    
    my $lbl_pet_weight = Wx::StaticText->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "Weight");
    $self->{grid_patient_demo}->Add($lbl_pet_weight, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_pet_weight} = Wx::TextCtrl->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_patient_demo}->Add($self->{txt_pet_weight}, 1, wxEXPAND, 0);
    
    $self->{sizer_pet_flags} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_patient_demo}->Add($self->{sizer_pet_flags}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{chk_pet_deceased} = Wx::CheckBox->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "Deceased");
    $self->{sizer_pet_flags}->Add($self->{chk_pet_deceased}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_pet_aggressive} = Wx::CheckBox->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "Aggressive");
    $self->{sizer_pet_flags}->Add($self->{chk_pet_aggressive}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{sizer_pet_flags}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_pet_save} = Wx::Button->new($self->{box_patient_demo}->GetStaticBox(), wxID_ANY, "Save");
    $self->{sizer_pet_flags}->Add($self->{btn_pet_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{patient_tab_vax} = Wx::Panel->new($self->{nb_patient}, wxID_ANY);
    $self->{nb_patient}->AddPage($self->{patient_tab_vax}, "Vaccines");
    
    $self->{sizer_patient_vax} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_vax} = Wx::ListCtrl->new($self->{patient_tab_vax}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_patient_vax}->Add($self->{list_vax}, 1, wxALL|wxEXPAND, 6);
    
    $self->{patient_tab_allergy} = Wx::Panel->new($self->{nb_patient}, wxID_ANY);
    $self->{nb_patient}->AddPage($self->{patient_tab_allergy}, "Allergies");
    
    $self->{sizer_patient_allergy} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_allergy} = Wx::TextCtrl->new($self->{patient_tab_allergy}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_patient_allergy}->Add($self->{txt_allergy}, 1, wxALL|wxEXPAND, 6);
    
    $self->{patient_tab_history} = Wx::Panel->new($self->{nb_patient}, wxID_ANY);
    $self->{nb_patient}->AddPage($self->{patient_tab_history}, "History");
    
    $self->{sizer_patient_history} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_history} = Wx::ListCtrl->new($self->{patient_tab_history}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_patient_history}->Add($self->{list_history}, 1, wxALL|wxEXPAND, 6);
    
    $self->{patient_tab_contacts} = Wx::Panel->new($self->{nb_patient}, wxID_ANY);
    $self->{nb_patient}->AddPage($self->{patient_tab_contacts}, "Contacts");
    
    $self->{sizer_patient_contacts} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_contacts} = Wx::ListCtrl->new($self->{patient_tab_contacts}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_patient_contacts}->Add($self->{list_contacts}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_medical} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_medical}, "Medical");
    
    $self->{sizer_med_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{split_med} = Wx::SplitterWindow->new($self->{page_medical}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_med}->SetMinimumPaneSize(20);
    $self->{sizer_med_root}->Add($self->{split_med}, 1, wxEXPAND, 0);
    
    $self->{panel_med_left} = Wx::Panel->new($self->{split_med}, wxID_ANY);
    
    $self->{sizer_med_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_visits} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_med_left}, wxID_ANY, "Visits"), wxVERTICAL);
    $self->{sizer_med_left}->Add($self->{box_visits}, 0, wxALL|wxEXPAND, 8);
    
    $self->{list_visits} = Wx::ListCtrl->new($self->{box_visits}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_visits}->Add($self->{list_visits}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sizer_visit_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_med_left}->Add($self->{sizer_visit_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{btn_visit_new} = Wx::Button->new($self->{panel_med_left}, wxID_ANY, "New Visit");
    $self->{sizer_visit_btns}->Add($self->{btn_visit_new}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_visit_open} = Wx::Button->new($self->{panel_med_left}, wxID_ANY, "Open");
    $self->{sizer_visit_btns}->Add($self->{btn_visit_open}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_visit_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_visit_sign} = Wx::Button->new($self->{panel_med_left}, wxID_ANY, "Sign");
    $self->{sizer_visit_btns}->Add($self->{btn_visit_sign}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{panel_med_right} = Wx::Panel->new($self->{split_med}, wxID_ANY);
    
    $self->{sizer_med_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_med} = Wx::Notebook->new($self->{panel_med_right}, wxID_ANY);
    $self->{sizer_med_right}->Add($self->{nb_med}, 1, wxALL|wxEXPAND, 8);
    
    $self->{med_tab_soap} = Wx::Panel->new($self->{nb_med}, wxID_ANY);
    $self->{nb_med}->AddPage($self->{med_tab_soap}, "SOAP");
    
    $self->{sizer_med_soap} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_soap_bottom} = Wx::Notebook->new($self->{med_tab_soap}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM);
    $self->{sizer_med_soap}->Add($self->{nb_soap_bottom}, 1, wxALL|wxEXPAND, 6);
    
    $self->{soap_tab_s} = Wx::Panel->new($self->{nb_soap_bottom}, wxID_ANY);
    $self->{nb_soap_bottom}->AddPage($self->{soap_tab_s}, "Subjective");
    
    $self->{sizer_soap_s} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_soap_s} = Wx::TextCtrl->new($self->{soap_tab_s}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_s}->Add($self->{txt_soap_s}, 1, wxALL|wxEXPAND, 6);
    
    $self->{soap_tab_o} = Wx::Panel->new($self->{nb_soap_bottom}, wxID_ANY);
    $self->{nb_soap_bottom}->AddPage($self->{soap_tab_o}, "Objective");
    
    $self->{sizer_soap_o} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_soap_o} = Wx::TextCtrl->new($self->{soap_tab_o}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_o}->Add($self->{txt_soap_o}, 1, wxALL|wxEXPAND, 6);
    
    $self->{soap_tab_a} = Wx::Panel->new($self->{nb_soap_bottom}, wxID_ANY);
    $self->{nb_soap_bottom}->AddPage($self->{soap_tab_a}, "Assessment");
    
    $self->{sizer_soap_a} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_soap_a} = Wx::TextCtrl->new($self->{soap_tab_a}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_a}->Add($self->{txt_soap_a}, 1, wxALL|wxEXPAND, 6);
    
    $self->{soap_tab_p} = Wx::Panel->new($self->{nb_soap_bottom}, wxID_ANY);
    $self->{nb_soap_bottom}->AddPage($self->{soap_tab_p}, "Plan");
    
    $self->{sizer_soap_p} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_soap_p} = Wx::TextCtrl->new($self->{soap_tab_p}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_soap_p}->Add($self->{txt_soap_p}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_tab_dx} = Wx::Panel->new($self->{nb_med}, wxID_ANY);
    $self->{nb_med}->AddPage($self->{med_tab_dx}, "Diagnostics");
    
    $self->{sizer_med_dx} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_dx} = Wx::ListCtrl->new($self->{med_tab_dx}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_med_dx}->Add($self->{list_dx}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_tab_rx} = Wx::Panel->new($self->{nb_med}, wxID_ANY);
    $self->{nb_med}->AddPage($self->{med_tab_rx}, "Meds");
    
    $self->{sizer_med_rx} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_rx} = Wx::ListCtrl->new($self->{med_tab_rx}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_med_rx}->Add($self->{list_rx}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_tab_tx} = Wx::Panel->new($self->{nb_med}, wxID_ANY);
    $self->{nb_med}->AddPage($self->{med_tab_tx}, "Treatments");
    
    $self->{sizer_med_tx} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_tx} = Wx::ListCtrl->new($self->{med_tab_tx}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_med_tx}->Add($self->{list_tx}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_tab_attach} = Wx::Panel->new($self->{nb_med}, wxID_ANY);
    $self->{nb_med}->AddPage($self->{med_tab_attach}, "Attachments");
    
    $self->{sizer_med_attach} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_attach} = Wx::ListCtrl->new($self->{med_tab_attach}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_med_attach}->Add($self->{list_attach}, 1, wxALL|wxEXPAND, 6);
    
    $self->{med_tab_charges} = Wx::Panel->new($self->{nb_med}, wxID_ANY);
    $self->{nb_med}->AddPage($self->{med_tab_charges}, "Charges");
    
    $self->{sizer_med_charges} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_med_charges} = Wx::ListCtrl->new($self->{med_tab_charges}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_med_charges}->Add($self->{list_med_charges}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_billing} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_billing}, "Billing");
    
    $self->{sizer_bill_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{split_bill} = Wx::SplitterWindow->new($self->{page_billing}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_bill}->SetMinimumPaneSize(20);
    $self->{sizer_bill_root}->Add($self->{split_bill}, 1, wxEXPAND, 0);
    
    $self->{panel_bill_left} = Wx::Panel->new($self->{split_bill}, wxID_ANY);
    
    $self->{sizer_bill_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_invoices} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_bill_left}, wxID_ANY, "Invoices"), wxVERTICAL);
    $self->{sizer_bill_left}->Add($self->{box_invoices}, 0, wxALL|wxEXPAND, 8);
    
    $self->{list_invoices} = Wx::ListCtrl->new($self->{box_invoices}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_invoices}->Add($self->{list_invoices}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_bill_right} = Wx::Panel->new($self->{split_bill}, wxID_ANY);
    
    $self->{sizer_bill_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_totals} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_bill_right}, wxID_ANY, "Totals"), wxVERTICAL);
    $self->{sizer_bill_right}->Add($self->{box_totals}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_totals} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_totals}->Add($self->{grid_totals}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_subtotal = Wx::StaticText->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "Subtotal");
    $self->{grid_totals}->Add($lbl_subtotal, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_subtotal} = Wx::TextCtrl->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_totals}->Add($self->{txt_subtotal}, 1, wxEXPAND, 0);
    
    my $lbl_tax = Wx::StaticText->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "Tax");
    $self->{grid_totals}->Add($lbl_tax, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_tax} = Wx::TextCtrl->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_totals}->Add($self->{txt_tax}, 1, wxEXPAND, 0);
    
    my $lbl_total = Wx::StaticText->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "Total");
    $self->{grid_totals}->Add($lbl_total, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_total} = Wx::TextCtrl->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_totals}->Add($self->{txt_total}, 1, wxEXPAND, 0);
    
    $self->{sizer_bill_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_totals}->Add($self->{sizer_bill_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_take_payment} = Wx::Button->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "Take Payment");
    $self->{sizer_bill_btns}->Add($self->{btn_take_payment}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_print_invoice} = Wx::Button->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "Print");
    $self->{sizer_bill_btns}->Add($self->{btn_print_invoice}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_bill_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_close_invoice} = Wx::Button->new($self->{box_totals}->GetStaticBox(), wxID_ANY, "Close");
    $self->{sizer_bill_btns}->Add($self->{btn_close_invoice}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{nb_bill_bottom} = Wx::Notebook->new($self->{panel_bill_right}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM);
    $self->{sizer_bill_right}->Add($self->{nb_bill_bottom}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{bill_tab_items} = Wx::Panel->new($self->{nb_bill_bottom}, wxID_ANY);
    $self->{nb_bill_bottom}->AddPage($self->{bill_tab_items}, "Line Items");
    
    $self->{sizer_bill_items} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_bill_items} = Wx::ListCtrl->new($self->{bill_tab_items}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_bill_items}->Add($self->{list_bill_items}, 1, wxALL|wxEXPAND, 6);
    
    $self->{bill_tab_payments} = Wx::Panel->new($self->{nb_bill_bottom}, wxID_ANY);
    $self->{nb_bill_bottom}->AddPage($self->{bill_tab_payments}, "Payments");
    
    $self->{sizer_bill_payments} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_bill_payments} = Wx::ListCtrl->new($self->{bill_tab_payments}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_bill_payments}->Add($self->{list_bill_payments}, 1, wxALL|wxEXPAND, 6);
    
    $self->{bill_tab_ar} = Wx::Panel->new($self->{nb_bill_bottom}, wxID_ANY);
    $self->{nb_bill_bottom}->AddPage($self->{bill_tab_ar}, "A/R");
    
    $self->{sizer_bill_ar} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_bill_ar} = Wx::ListCtrl->new($self->{bill_tab_ar}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_bill_ar}->Add($self->{list_bill_ar}, 1, wxALL|wxEXPAND, 6);
    
    $self->{bill_tab_notes} = Wx::Panel->new($self->{nb_bill_bottom}, wxID_ANY);
    $self->{nb_bill_bottom}->AddPage($self->{bill_tab_notes}, "Notes");
    
    $self->{sizer_bill_notes} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_bill_notes} = Wx::TextCtrl->new($self->{bill_tab_notes}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_bill_notes}->Add($self->{txt_bill_notes}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_inventory} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_inventory}, "Inventory");
    
    $self->{sizer_inv_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{split_inv} = Wx::SplitterWindow->new($self->{page_inventory}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_inv}->SetMinimumPaneSize(20);
    $self->{sizer_inv_root}->Add($self->{split_inv}, 1, wxEXPAND, 0);
    
    $self->{panel_inv_left} = Wx::Panel->new($self->{split_inv}, wxID_ANY);
    
    $self->{sizer_inv_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_inv_search} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_inv_left}->Add($self->{sizer_inv_search}, 0, wxALL|wxEXPAND, 8);
    
    my $lbl_inv_find = Wx::StaticText->new($self->{panel_inv_left}, wxID_ANY, "Find");
    $self->{sizer_inv_search}->Add($lbl_inv_find, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_find} = Wx::TextCtrl->new($self->{panel_inv_left}, wxID_ANY, "");
    $self->{sizer_inv_search}->Add($self->{txt_inv_find}, 1, wxEXPAND|wxLEFT, 6);
    
    $self->{btn_inv_search} = Wx::Button->new($self->{panel_inv_left}, wxID_ANY, "Search");
    $self->{sizer_inv_search}->Add($self->{btn_inv_search}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{list_inv_items} = Wx::ListCtrl->new($self->{panel_inv_left}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_inv_left}->Add($self->{list_inv_items}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{panel_inv_right} = Wx::Panel->new($self->{split_inv}, wxID_ANY);
    
    $self->{sizer_inv_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_inv} = Wx::Notebook->new($self->{panel_inv_right}, wxID_ANY);
    $self->{sizer_inv_right}->Add($self->{nb_inv}, 1, wxALL|wxEXPAND, 8);
    
    $self->{inv_tab_general} = Wx::Panel->new($self->{nb_inv}, wxID_ANY);
    $self->{nb_inv}->AddPage($self->{inv_tab_general}, "General");
    
    $self->{sizer_inv_general} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_inv_general} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{sizer_inv_general}->Add($self->{grid_inv_general}, 0, wxALL|wxEXPAND, 8);
    
    my $lbl_inv_sku = Wx::StaticText->new($self->{inv_tab_general}, wxID_ANY, "SKU");
    $self->{grid_inv_general}->Add($lbl_inv_sku, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_sku} = Wx::TextCtrl->new($self->{inv_tab_general}, wxID_ANY, "");
    $self->{grid_inv_general}->Add($self->{txt_inv_sku}, 1, wxEXPAND, 0);
    
    my $lbl_inv_desc = Wx::StaticText->new($self->{inv_tab_general}, wxID_ANY, "Description");
    $self->{grid_inv_general}->Add($lbl_inv_desc, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_desc} = Wx::TextCtrl->new($self->{inv_tab_general}, wxID_ANY, "");
    $self->{grid_inv_general}->Add($self->{txt_inv_desc}, 1, wxEXPAND, 0);
    
    $self->{inv_tab_pricing} = Wx::Panel->new($self->{nb_inv}, wxID_ANY);
    $self->{nb_inv}->AddPage($self->{inv_tab_pricing}, "Pricing");
    
    $self->{sizer_inv_pricing} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_inv_pricing} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{sizer_inv_pricing}->Add($self->{grid_inv_pricing}, 0, wxALL|wxEXPAND, 8);
    
    my $lbl_inv_cost = Wx::StaticText->new($self->{inv_tab_pricing}, wxID_ANY, "Cost");
    $self->{grid_inv_pricing}->Add($lbl_inv_cost, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_cost} = Wx::TextCtrl->new($self->{inv_tab_pricing}, wxID_ANY, "");
    $self->{grid_inv_pricing}->Add($self->{txt_inv_cost}, 1, wxEXPAND, 0);
    
    my $lbl_inv_price = Wx::StaticText->new($self->{inv_tab_pricing}, wxID_ANY, "Price");
    $self->{grid_inv_pricing}->Add($lbl_inv_price, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_inv_price} = Wx::TextCtrl->new($self->{inv_tab_pricing}, wxID_ANY, "");
    $self->{grid_inv_pricing}->Add($self->{txt_inv_price}, 1, wxEXPAND, 0);
    
    $self->{inv_tab_usage} = Wx::Panel->new($self->{nb_inv}, wxID_ANY);
    $self->{nb_inv}->AddPage($self->{inv_tab_usage}, "Usage");
    
    $self->{sizer_inv_usage} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_inv_usage} = Wx::ListCtrl->new($self->{inv_tab_usage}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_inv_usage}->Add($self->{list_inv_usage}, 1, wxALL|wxEXPAND, 6);
    
    $self->{inv_tab_vendor} = Wx::Panel->new($self->{nb_inv}, wxID_ANY);
    $self->{nb_inv}->AddPage($self->{inv_tab_vendor}, "Vendor");
    
    $self->{sizer_inv_vendor} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_inv_vendor} = Wx::TextCtrl->new($self->{inv_tab_vendor}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{sizer_inv_vendor}->Add($self->{txt_inv_vendor}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_reports} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_reports}, "Reports");
    
    $self->{sizer_reports_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{split_reports} = Wx::SplitterWindow->new($self->{page_reports}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_reports}->SetMinimumPaneSize(20);
    $self->{sizer_reports_root}->Add($self->{split_reports}, 1, wxEXPAND, 0);
    
    $self->{panel_reports_left} = Wx::Panel->new($self->{split_reports}, wxID_ANY);
    
    $self->{sizer_reports_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_report_library} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_reports_left}, wxID_ANY, "Report Library"), wxVERTICAL);
    $self->{sizer_reports_left}->Add($self->{box_report_library}, 0, wxALL|wxEXPAND, 8);
    
    $self->{list_reports} = Wx::ListCtrl->new($self->{box_report_library}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_report_library}->Add($self->{list_reports}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_reports_right} = Wx::Panel->new($self->{split_reports}, wxID_ANY);
    
    $self->{sizer_reports_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_report_params} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_reports_right}, wxID_ANY, "Parameters"), wxVERTICAL);
    $self->{sizer_reports_right}->Add($self->{box_report_params}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_report_params} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_report_params}->Add($self->{grid_report_params}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_rpt_from = Wx::StaticText->new($self->{box_report_params}->GetStaticBox(), wxID_ANY, "Date from");
    $self->{grid_report_params}->Add($lbl_rpt_from, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rpt_from} = Wx::TextCtrl->new($self->{box_report_params}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_rpt_from}->SetMinSize(Wx::Size->new(110,-1));
    $self->{grid_report_params}->Add($self->{txt_rpt_from}, 1, wxEXPAND, 0);
    
    my $lbl_rpt_to = Wx::StaticText->new($self->{box_report_params}->GetStaticBox(), wxID_ANY, "to");
    $self->{grid_report_params}->Add($lbl_rpt_to, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_rpt_to} = Wx::TextCtrl->new($self->{box_report_params}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_rpt_to}->SetMinSize(Wx::Size->new(110,-1));
    $self->{grid_report_params}->Add($self->{txt_rpt_to}, 1, wxEXPAND, 0);
    
    $self->{sizer_rpt_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_report_params}->Add($self->{sizer_rpt_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_rpt_run} = Wx::Button->new($self->{box_report_params}->GetStaticBox(), wxID_ANY, "Run");
    $self->{sizer_rpt_btns}->Add($self->{btn_rpt_run}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_rpt_export} = Wx::Button->new($self->{box_report_params}->GetStaticBox(), wxID_ANY, "Export...");
    $self->{sizer_rpt_btns}->Add($self->{btn_rpt_export}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_rpt_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_rpt_print} = Wx::Button->new($self->{box_report_params}->GetStaticBox(), wxID_ANY, "Print");
    $self->{sizer_rpt_btns}->Add($self->{btn_rpt_print}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_rpt_output} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_reports_right}, wxID_ANY, "Output"), wxVERTICAL);
    $self->{sizer_reports_right}->Add($self->{box_rpt_output}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{txt_rpt_output} = Wx::TextCtrl->new($self->{box_rpt_output}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{box_rpt_output}->Add($self->{txt_rpt_output}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_admin} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_admin}, "Admin/Setup");
    
    $self->{sizer_admin_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{split_admin} = Wx::SplitterWindow->new($self->{page_admin}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_admin}->SetMinimumPaneSize(20);
    $self->{sizer_admin_root}->Add($self->{split_admin}, 1, wxEXPAND, 0);
    
    $self->{panel_admin_left} = Wx::Panel->new($self->{split_admin}, wxID_ANY);
    
    $self->{sizer_admin_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_admin_nav} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_admin_left}, wxID_ANY, "Setup Areas"), wxVERTICAL);
    $self->{sizer_admin_left}->Add($self->{box_admin_nav}, 0, wxALL|wxEXPAND, 8);
    
    $self->{list_admin_nav} = Wx::ListCtrl->new($self->{box_admin_nav}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_admin_nav}->Add($self->{list_admin_nav}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_admin_right} = Wx::Panel->new($self->{split_admin}, wxID_ANY);
    
    $self->{sizer_admin_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{nb_admin} = Wx::Notebook->new($self->{panel_admin_right}, wxID_ANY);
    $self->{sizer_admin_right}->Add($self->{nb_admin}, 1, wxALL|wxEXPAND, 8);
    
    $self->{admin_tab_practice} = Wx::Panel->new($self->{nb_admin}, wxID_ANY);
    $self->{nb_admin}->AddPage($self->{admin_tab_practice}, "Practice");
    
    $self->{sizer_admin_practice} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{grid_practice} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{sizer_admin_practice}->Add($self->{grid_practice}, 0, wxALL|wxEXPAND, 8);
    
    my $lbl_practice_name = Wx::StaticText->new($self->{admin_tab_practice}, wxID_ANY, "Practice name");
    $self->{grid_practice}->Add($lbl_practice_name, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_practice_name} = Wx::TextCtrl->new($self->{admin_tab_practice}, wxID_ANY, "");
    $self->{grid_practice}->Add($self->{txt_practice_name}, 1, wxEXPAND, 0);
    
    my $lbl_timezone = Wx::StaticText->new($self->{admin_tab_practice}, wxID_ANY, "Timezone");
    $self->{grid_practice}->Add($lbl_timezone, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_timezone} = Wx::Choice->new($self->{admin_tab_practice}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Local", "UTC"], );
    $self->{choice_timezone}->SetSelection(0);
    $self->{grid_practice}->Add($self->{choice_timezone}, 1, wxEXPAND, 0);
    
    $self->{admin_tab_users} = Wx::Panel->new($self->{nb_admin}, wxID_ANY);
    $self->{nb_admin}->AddPage($self->{admin_tab_users}, "Users/Roles");
    
    $self->{sizer_admin_users} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{list_users} = Wx::ListCtrl->new($self->{admin_tab_users}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_admin_users}->Add($self->{list_users}, 1, wxALL|wxEXPAND, 6);
    
    $self->{admin_tab_integrations} = Wx::Panel->new($self->{nb_admin}, wxID_ANY);
    $self->{nb_admin}->AddPage($self->{admin_tab_integrations}, "Integrations");
    
    $self->{sizer_admin_integrations} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_api} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{admin_tab_integrations}, wxID_ANY, "API Credentials"), wxVERTICAL);
    $self->{sizer_admin_integrations}->Add($self->{box_api}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_api} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_api}->Add($self->{grid_api}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_api_key = Wx::StaticText->new($self->{box_api}->GetStaticBox(), wxID_ANY, "API key");
    $self->{grid_api}->Add($lbl_api_key, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_api_key} = Wx::TextCtrl->new($self->{box_api}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_api}->Add($self->{txt_api_key}, 1, wxEXPAND, 0);
    
    my $lbl_api_secret = Wx::StaticText->new($self->{box_api}->GetStaticBox(), wxID_ANY, "API secret");
    $self->{grid_api}->Add($lbl_api_secret, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_api_secret} = Wx::TextCtrl->new($self->{box_api}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    $self->{grid_api}->Add($self->{txt_api_secret}, 1, wxEXPAND, 0);
    
    $self->{sizer_api_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_api}->Add($self->{sizer_api_btns}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{btn_api_test} = Wx::Button->new($self->{box_api}->GetStaticBox(), wxID_ANY, "Test");
    $self->{sizer_api_btns}->Add($self->{btn_api_test}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_api_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_api_save} = Wx::Button->new($self->{box_api}->GetStaticBox(), wxID_ANY, "Save");
    $self->{sizer_api_btns}->Add($self->{btn_api_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_integrations} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{admin_tab_integrations}, wxID_ANY, "Integrations"), wxVERTICAL);
    $self->{sizer_admin_integrations}->Add($self->{box_integrations}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{list_integrations} = Wx::ListCtrl->new($self->{box_integrations}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_integrations}->Add($self->{list_integrations}, 1, wxALL|wxEXPAND, 6);
    
    $self->{admin_tab_advanced} = Wx::Panel->new($self->{nb_admin}, wxID_ANY);
    $self->{nb_admin}->AddPage($self->{admin_tab_advanced}, "Advanced");
    
    $self->{sizer_admin_advanced} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{chk_adv_enable_debug} = Wx::CheckBox->new($self->{admin_tab_advanced}, wxID_ANY, "Enable debug logging");
    $self->{sizer_admin_advanced}->Add($self->{chk_adv_enable_debug}, 0, wxALL|wxEXPAND, 8);
    
    $self->{chk_adv_offline_mode} = Wx::CheckBox->new($self->{admin_tab_advanced}, wxID_ANY, "Offline mode (read-only)");
    $self->{sizer_admin_advanced}->Add($self->{chk_adv_offline_mode}, 0, wxALL|wxEXPAND, 8);
    
    $self->{admin_tab_logs} = Wx::Panel->new($self->{nb_admin}, wxID_ANY);
    $self->{nb_admin}->AddPage($self->{admin_tab_logs}, "Logs");
    
    $self->{sizer_admin_logs} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{gauge_sync} = Wx::Gauge->new($self->{admin_tab_logs}, wxID_ANY, 100, wxDefaultPosition, wxDefaultSize, 0);
    $self->{sizer_admin_logs}->Add($self->{gauge_sync}, 0, wxALL|wxEXPAND, 8);
    
    $self->{txt_logs} = Wx::TextCtrl->new($self->{admin_tab_logs}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_admin_logs}->Add($self->{txt_logs}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    my $lbl_status = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "Ready.");
    $self->{sizer_root}->Add($lbl_status, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{admin_tab_logs}->SetSizer($self->{sizer_admin_logs});
    
    $self->{admin_tab_advanced}->SetSizer($self->{sizer_admin_advanced});
    
    $self->{grid_api}->AddGrowableCol(1);
    
    $self->{admin_tab_integrations}->SetSizer($self->{sizer_admin_integrations});
    
    $self->{admin_tab_users}->SetSizer($self->{sizer_admin_users});
    
    $self->{grid_practice}->AddGrowableCol(1);
    
    $self->{admin_tab_practice}->SetSizer($self->{sizer_admin_practice});
    
    $self->{panel_admin_right}->SetSizer($self->{sizer_admin_right});
    
    $self->{panel_admin_left}->SetSizer($self->{sizer_admin_left});
    
    $self->{split_admin}->SplitVertically($self->{panel_admin_left}, $self->{panel_admin_right}, );
    
    $self->{page_admin}->SetSizer($self->{sizer_admin_root});
    
    $self->{grid_report_params}->AddGrowableCol(1);
    
    $self->{panel_reports_right}->SetSizer($self->{sizer_reports_right});
    
    $self->{panel_reports_left}->SetSizer($self->{sizer_reports_left});
    
    $self->{split_reports}->SplitVertically($self->{panel_reports_left}, $self->{panel_reports_right}, );
    
    $self->{page_reports}->SetSizer($self->{sizer_reports_root});
    
    $self->{inv_tab_vendor}->SetSizer($self->{sizer_inv_vendor});
    
    $self->{inv_tab_usage}->SetSizer($self->{sizer_inv_usage});
    
    $self->{grid_inv_pricing}->AddGrowableCol(1);
    
    $self->{inv_tab_pricing}->SetSizer($self->{sizer_inv_pricing});
    
    $self->{grid_inv_general}->AddGrowableCol(1);
    
    $self->{inv_tab_general}->SetSizer($self->{sizer_inv_general});
    
    $self->{panel_inv_right}->SetSizer($self->{sizer_inv_right});
    
    $self->{panel_inv_left}->SetSizer($self->{sizer_inv_left});
    
    $self->{split_inv}->SplitVertically($self->{panel_inv_left}, $self->{panel_inv_right}, );
    
    $self->{page_inventory}->SetSizer($self->{sizer_inv_root});
    
    $self->{bill_tab_notes}->SetSizer($self->{sizer_bill_notes});
    
    $self->{bill_tab_ar}->SetSizer($self->{sizer_bill_ar});
    
    $self->{bill_tab_payments}->SetSizer($self->{sizer_bill_payments});
    
    $self->{bill_tab_items}->SetSizer($self->{sizer_bill_items});
    
    $self->{grid_totals}->AddGrowableCol(1);
    
    $self->{panel_bill_right}->SetSizer($self->{sizer_bill_right});
    
    $self->{panel_bill_left}->SetSizer($self->{sizer_bill_left});
    
    $self->{split_bill}->SplitVertically($self->{panel_bill_left}, $self->{panel_bill_right}, );
    
    $self->{page_billing}->SetSizer($self->{sizer_bill_root});
    
    $self->{med_tab_charges}->SetSizer($self->{sizer_med_charges});
    
    $self->{med_tab_attach}->SetSizer($self->{sizer_med_attach});
    
    $self->{med_tab_tx}->SetSizer($self->{sizer_med_tx});
    
    $self->{med_tab_rx}->SetSizer($self->{sizer_med_rx});
    
    $self->{med_tab_dx}->SetSizer($self->{sizer_med_dx});
    
    $self->{soap_tab_p}->SetSizer($self->{sizer_soap_p});
    
    $self->{soap_tab_a}->SetSizer($self->{sizer_soap_a});
    
    $self->{soap_tab_o}->SetSizer($self->{sizer_soap_o});
    
    $self->{soap_tab_s}->SetSizer($self->{sizer_soap_s});
    
    $self->{med_tab_soap}->SetSizer($self->{sizer_med_soap});
    
    $self->{panel_med_right}->SetSizer($self->{sizer_med_right});
    
    $self->{panel_med_left}->SetSizer($self->{sizer_med_left});
    
    $self->{split_med}->SplitVertically($self->{panel_med_left}, $self->{panel_med_right}, );
    
    $self->{page_medical}->SetSizer($self->{sizer_med_root});
    
    $self->{patient_tab_contacts}->SetSizer($self->{sizer_patient_contacts});
    
    $self->{patient_tab_history}->SetSizer($self->{sizer_patient_history});
    
    $self->{patient_tab_allergy}->SetSizer($self->{sizer_patient_allergy});
    
    $self->{patient_tab_vax}->SetSizer($self->{sizer_patient_vax});
    
    $self->{grid_patient_demo}->AddGrowableCol(1);
    
    $self->{patient_tab_demo}->SetSizer($self->{sizer_patient_demo});
    
    $self->{page_patient}->SetSizer($self->{sizer_patient_root});
    
    $self->{client_tab_docs}->SetSizer($self->{sizer_client_docs});
    
    $self->{client_tab_notes}->SetSizer($self->{sizer_client_notes});
    
    $self->{client_tab_alerts}->SetSizer($self->{sizer_client_alerts});
    
    $self->{client_tab_patients}->SetSizer($self->{sizer_client_patients});
    
    $self->{grid_client_summary}->AddGrowableCol(1);
    
    $self->{panel_clients_right}->SetSizer($self->{sizer_clients_right});
    
    $self->{panel_clients_left}->SetSizer($self->{sizer_clients_left});
    
    $self->{split_clients}->SplitVertically($self->{panel_clients_left}, $self->{panel_clients_right}, );
    
    $self->{page_clients}->SetSizer($self->{sizer_clients_root});
    
    $self->{sched_tab_charges}->SetSizer($self->{sizer_sched_charges});
    
    $self->{sched_tab_alerts}->SetSizer($self->{sizer_sched_alerts});
    
    $self->{sched_tab_tasks}->SetSizer($self->{sizer_sched_tasks});
    
    $self->{sched_tab_notes}->SetSizer($self->{sizer_sched_notes});
    
    $self->{grid_appt_detail}->AddGrowableCol(1);
    
    $self->{panel_sched_right}->SetSizer($self->{sizer_sched_right});
    
    $self->{grid_sched_filters}->AddGrowableCol(1);
    $self->{grid_sched_filters}->AddGrowableCol(3);
    
    $self->{panel_sched_left}->SetSizer($self->{sizer_sched_left});
    
    $self->{split_sched}->SplitVertically($self->{panel_sched_left}, $self->{panel_sched_right}, );
    
    $self->{page_scheduler}->SetSizer($self->{sizer_sched_root});
    
    $self->{panel_dash_right}->SetSizer($self->{sizer_dash_right});
    
    $self->{panel_dash_left}->SetSizer($self->{sizer_dash_left});
    
    $self->{split_dash}->SplitVertically($self->{panel_dash_left}, $self->{panel_dash_right}, );
    
    $self->{page_dashboard}->SetSizer($self->{sizer_dash});
    
    $self->{panel_root}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class AvimarkMainFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_avimark = AvimarkMainFrame->new();

    $self->SetTopWindow($frame_avimark);
    $frame_avimark->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
