#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Fri Feb 13 01:59:56 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package BSPIMainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: BSPIMainFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1200, 900));
    $self->SetTitle("BoyScoutPatch.info - Desktop Client");
    
    $self->{panel_root} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_query} = Wx::TextCtrl->new($self->{panel_root}, wxID_ANY, "");
    $self->{txt_query}->SetMinSize(Wx::Size->new(-1,30));
    $self->{sizer_root}->Add($self->{txt_query}, 0, wxALL|wxEXPAND, 8);
    
    $self->{nb_main} = Wx::Notebook->new($self->{panel_root}, wxID_ANY);
    $self->{sizer_root}->Add($self->{nb_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{page_search} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_search}, "");
    
    $self->{sizer_search_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_query} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_search}, wxID_ANY, "Query"), wxVERTICAL);
    $self->{sizer_search_root}->Add($self->{box_query}, 0, wxALL|wxEXPAND, 8);
    
    $self->{sizer_date_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_query}->Add($self->{sizer_date_row}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_date_from = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Date from");
    $self->{sizer_date_row}->Add($lbl_date_from, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_date_from} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_date_from}->SetMinSize(Wx::Size->new(90,-1));
    $self->{sizer_date_row}->Add($self->{txt_date_from}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_pick_from} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "...");
    $self->{btn_pick_from}->SetMinSize(Wx::Size->new(28,22));
    $self->{sizer_date_row}->Add($self->{btn_pick_from}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    my $lbl_date_to = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "to");
    $self->{sizer_date_row}->Add($lbl_date_to, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{txt_date_to} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_date_to}->SetMinSize(Wx::Size->new(90,-1));
    $self->{sizer_date_row}->Add($self->{txt_date_to}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_pick_to} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "...");
    $self->{btn_pick_to}->SetMinSize(Wx::Size->new(28,22));
    $self->{sizer_date_row}->Add($self->{btn_pick_to}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_date_row}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{sizer_controls_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_query}->Add($self->{sizer_controls_row}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_show = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Show");
    $self->{sizer_controls_row}->Add($lbl_show, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_show} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["10 Results", "50 Results", "100 Results", "500 Results"], );
    $self->{choice_show}->SetSelection(0);
    $self->{sizer_controls_row}->Add($self->{choice_show}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    my $lbl_order = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Order by");
    $self->{sizer_controls_row}->Add($lbl_order, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{choice_order} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Date", "Price", "Bids", "Seller"], );
    $self->{choice_order}->SetSelection(0);
    $self->{sizer_controls_row}->Add($self->{choice_order}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_controls_row}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_refine} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "refine");
    $self->{sizer_controls_row}->Add($self->{btn_refine}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_reset} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "reset");
    $self->{sizer_controls_row}->Add($self->{btn_reset}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_search} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "search");
    $self->{sizer_controls_row}->Add($self->{btn_search}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{box_results} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_search}, wxID_ANY, "Results"), wxVERTICAL);
    $self->{sizer_search_root}->Add($self->{box_results}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{list_results} = Wx::ListCtrl->new($self->{box_results}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_results}->Add($self->{list_results}, 1, wxALL|wxEXPAND, 6);
    
    my $lbl_status = Wx::StaticText->new($self->{page_search}, wxID_ANY, "Ready.");
    $self->{sizer_search_root}->Add($lbl_status, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{page_saved} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_saved}, "");
    
    $self->{sizer_saved} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_saved_placeholder = Wx::StaticText->new($self->{page_saved}, wxID_ANY, "[ Saved Lists placeholder ]");
    $self->{sizer_saved}->Add($lbl_saved_placeholder, 1, wxALL|wxEXPAND, 12);
    
    $self->{page_price} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_price}, "");
    
    $self->{sizer_price} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_price_placeholder = Wx::StaticText->new($self->{page_price}, wxID_ANY, "[ Price Lists placeholder ]");
    $self->{sizer_price}->Add($lbl_price_placeholder, 1, wxALL|wxEXPAND, 12);
    
    $self->{page_item} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_item}, "");
    
    $self->{sizer_item} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_item_placeholder = Wx::StaticText->new($self->{page_item}, wxID_ANY, "[ Item Details placeholder ]");
    $self->{sizer_item}->Add($lbl_item_placeholder, 1, wxALL|wxEXPAND, 12);
    
    $self->{page_admin} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_admin}, "");
    
    $self->{sizer_admin} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{btn_admin_sync} = Wx::Button->new($self->{page_admin}, wxID_ANY, "Sync / Refresh");
    $self->{sizer_admin}->Add($self->{btn_admin_sync}, 0, wxALL, 12);
    
    $self->{txt_admin_log} = Wx::TextCtrl->new($self->{page_admin}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_admin}->Add($self->{txt_admin_log}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 12);
    
    $self->{page_admin}->SetSizer($self->{sizer_admin});
    
    $self->{page_item}->SetSizer($self->{sizer_item});
    
    $self->{page_price}->SetSizer($self->{sizer_price});
    
    $self->{page_saved}->SetSizer($self->{sizer_saved});
    
    $self->{page_search}->SetSizer($self->{sizer_search_root});
    
    $self->{panel_root}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class BSPIMainFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_bspi = BSPIMainFrame->new();

    $self->SetTopWindow($frame_bspi);
    $frame_bspi->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
