#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Fri Feb 13 01:22:05 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package BSPIMainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: BSPIMainFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1200, 900));
    $self->SetTitle("BoyScoutPatch.info - Desktop Client");
    
    

    # Menu Bar

    $self->{menubar_main} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $self->{menu_file} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_file}, "File");
    $self->{menu_view} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_view}, "View");
    $self->{menu_tools} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_tools}, "Tools");
    $self->{menu_help} = Wx::Menu->new();
    $self->{menubar_main}->Append($self->{menu_help}, "Help");
    $self->SetMenuBar($self->{menubar_main});
    
    # Menu Bar end

    
    $self->{panel_root} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_title = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "BoyScoutPatch.info");
    $self->{sizer_root}->Add($lbl_title, 0, wxALL|wxEXPAND, 8);
    
    my $lbl_subtitle = Wx::StaticText->new($self->{panel_root}, wxID_ANY, "Desktop client (layout first; logic later)");
    $self->{sizer_root}->Add($lbl_subtitle, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 0);
    
    $self->{nb_main} = Wx::Notebook->new($self->{panel_root}, wxID_ANY);
    $self->{sizer_root}->Add($self->{nb_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{page_search} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_search}, "");
    
    $self->{sizer_search_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_query} = Wx::TextCtrl->new($self->{page_search}, wxID_ANY, "");
    $self->{txt_query}->SetMinSize(Wx::Size->new(-1,28));
    $self->{sizer_search_root}->Add($self->{txt_query}, 0, wxALL|wxEXPAND, 8);
    
    $self->{sizer_top_actions} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_search_root}->Add($self->{sizer_top_actions}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{btn_search} = Wx::Button->new($self->{page_search}, wxID_ANY, "Search");
    $self->{sizer_top_actions}->Add($self->{btn_search}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_search_hide} = Wx::Button->new($self->{page_search}, wxID_ANY, "Search & Hide");
    $self->{sizer_top_actions}->Add($self->{btn_search_hide}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_reset} = Wx::Button->new($self->{page_search}, wxID_ANY, "Reset");
    $self->{sizer_top_actions}->Add($self->{btn_reset}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_top_actions}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_advanced} = Wx::Button->new($self->{page_search}, wxID_ANY, "Advanced...");
    $self->{sizer_top_actions}->Add($self->{btn_advanced}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_query} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_search}, wxID_ANY, "Query"), wxVERTICAL);
    $self->{sizer_search_root}->Add($self->{box_query}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{sizer_dates} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_query}->Add($self->{sizer_dates}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_date_from = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Date from");
    $self->{sizer_dates}->Add($lbl_date_from, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_date_from} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_date_from}->SetMinSize(Wx::Size->new(90,-1));
    $self->{sizer_dates}->Add($self->{txt_date_from}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_pick_from} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "...");
    $self->{btn_pick_from}->SetMinSize(Wx::Size->new(28,22));
    $self->{sizer_dates}->Add($self->{btn_pick_from}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    my $lbl_date_to = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "to");
    $self->{sizer_dates}->Add($lbl_date_to, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{txt_date_to} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_date_to}->SetMinSize(Wx::Size->new(90,-1));
    $self->{sizer_dates}->Add($self->{txt_date_to}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_pick_to} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "...");
    $self->{btn_pick_to}->SetMinSize(Wx::Size->new(28,22));
    $self->{sizer_dates}->Add($self->{btn_pick_to}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_dates}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{grid_query} = Wx::FlexGridSizer->new(0, 2, 6, 10);
    $self->{box_query}->Add($self->{grid_query}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_mode = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Search Mode");
    $self->{grid_query}->Add($lbl_mode, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_mode} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["All Words", "Any Words", "Exact Phrase"], );
    $self->{choice_mode}->SetSelection(0);
    $self->{grid_query}->Add($self->{choice_mode}, 1, wxEXPAND, 0);
    
    my $lbl_listed_as = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Listed as");
    $self->{grid_query}->Add($lbl_listed_as, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_listed_as} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Any", "Auction Only", "Buy It Now"], );
    $self->{choice_listed_as}->SetSelection(0);
    $self->{grid_query}->Add($self->{choice_listed_as}, 1, wxEXPAND, 0);
    
    my $lbl_sold = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Sold Status");
    $self->{grid_query}->Add($lbl_sold, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_sold} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Any", "Sold Only", "Unsold Only"], );
    $self->{choice_sold}->SetSelection(0);
    $self->{grid_query}->Add($self->{choice_sold}, 1, wxEXPAND, 0);
    
    my $lbl_sellers = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Seller(s)");
    $self->{grid_query}->Add($lbl_sellers, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_sellers} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_query}->Add($self->{txt_sellers}, 1, wxEXPAND, 0);
    
    my $lbl_item_ids = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Item Id(s)");
    $self->{grid_query}->Add($lbl_item_ids, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_item_ids} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_query}->Add($self->{txt_item_ids}, 1, wxEXPAND, 0);
    
    my $lbl_index = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Search Index");
    $self->{grid_query}->Add($lbl_index, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_index} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Scouting Memorabilia", "OA Lodge Flaps", "Council CSP", "All"], );
    $self->{choice_index}->SetSelection(0);
    $self->{grid_query}->Add($self->{choice_index}, 1, wxEXPAND, 0);
    
    $self->{sizer_query_footer} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_query}->Add($self->{sizer_query_footer}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_show = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Show");
    $self->{sizer_query_footer}->Add($lbl_show, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_show} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["100", "250", "500", "1000"], );
    $self->{choice_show}->SetSelection(0);
    $self->{sizer_query_footer}->Add($self->{choice_show}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    my $lbl_order = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Order by");
    $self->{sizer_query_footer}->Add($lbl_order, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{choice_order} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Date", "Price", "Bids", "Seller"], );
    $self->{choice_order}->SetSelection(0);
    $self->{sizer_query_footer}->Add($self->{choice_order}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_query_footer}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{txt_refine} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_refine}->SetMinSize(Wx::Size->new(220,-1));
    $self->{sizer_query_footer}->Add($self->{txt_refine}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $lbl_refine = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Refine");
    $self->{sizer_query_footer}->Add($lbl_refine, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_selection} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_search_root}->Add($self->{sizer_selection}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{btn_show_selected} = Wx::Button->new($self->{page_search}, wxID_ANY, "Show Selected");
    $self->{sizer_selection}->Add($self->{btn_show_selected}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_hide_selected} = Wx::Button->new($self->{page_search}, wxID_ANY, "Hide Selected");
    $self->{sizer_selection}->Add($self->{btn_hide_selected}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{choice_save_to} = Wx::Choice->new($self->{page_search}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["-- Select Item List --"], );
    $self->{choice_save_to}->SetSelection(0);
    $self->{sizer_selection}->Add($self->{choice_save_to}, 1, wxEXPAND|wxLEFT, 12);
    
    $self->{btn_my_price_lists} = Wx::Button->new($self->{page_search}, wxID_ANY, "My Price Lists");
    $self->{sizer_selection}->Add($self->{btn_my_price_lists}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_results} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_search}, wxID_ANY, "Results"), wxVERTICAL);
    $self->{sizer_search_root}->Add($self->{box_results}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    my $lbl_results_summary = Wx::StaticText->new($self->{box_results}->GetStaticBox(), wxID_ANY, "Showing 0 items");
    $self->{box_results}->Add($lbl_results_summary, 0, wxALL|wxEXPAND, 4);
    
    $self->{list_results} = Wx::ListCtrl->new($self->{box_results}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_results}->Add($self->{list_results}, 1, wxALL|wxEXPAND, 4);
    
    my $lbl_status = Wx::StaticText->new($self->{page_search}, wxID_ANY, "Ready.");
    $self->{sizer_search_root}->Add($lbl_status, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{page_saved} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_saved}, "");
    
    $self->{sizer_saved} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_saved_placeholder = Wx::StaticText->new($self->{page_saved}, wxID_ANY, "[ Saved Lists placeholder ]");
    $self->{sizer_saved}->Add($lbl_saved_placeholder, 1, wxALL|wxEXPAND, 12);
    
    $self->{page_price} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_price}, "");
    
    $self->{sizer_price} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_price_placeholder = Wx::StaticText->new($self->{page_price}, wxID_ANY, "[ Price Lists placeholder ]");
    $self->{sizer_price}->Add($lbl_price_placeholder, 1, wxALL|wxEXPAND, 12);
    
    $self->{page_item} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_item}, "");
    
    $self->{sizer_item} = Wx::BoxSizer->new(wxVERTICAL);
    
    my $lbl_item_placeholder = Wx::StaticText->new($self->{page_item}, wxID_ANY, "[ Item Details placeholder ]");
    $self->{sizer_item}->Add($lbl_item_placeholder, 1, wxALL|wxEXPAND, 12);
    
    $self->{page_admin} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_admin}, "");
    
    $self->{sizer_admin} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{btn_admin_sync} = Wx::Button->new($self->{page_admin}, wxID_ANY, "Sync / Refresh");
    $self->{sizer_admin}->Add($self->{btn_admin_sync}, 0, wxALL, 12);
    
    $self->{txt_admin_log} = Wx::TextCtrl->new($self->{page_admin}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sizer_admin}->Add($self->{txt_admin_log}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 12);
    
    $self->{page_admin}->SetSizer($self->{sizer_admin});
    
    $self->{page_item}->SetSizer($self->{sizer_item});
    
    $self->{page_price}->SetSizer($self->{sizer_price});
    
    $self->{page_saved}->SetSizer($self->{sizer_saved});
    
    $self->{grid_query}->AddGrowableCol(1);
    
    $self->{page_search}->SetSizer($self->{sizer_search_root});
    
    $self->{panel_root}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class BSPIMainFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_bspi = BSPIMainFrame->new();

    $self->SetTopWindow($frame_bspi);
    $frame_bspi->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
