#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Fri Feb 13 02:24:45 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package BSPIMainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: BSPIMainFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1200, 900));
    $self->SetTitle("BoyScoutPatch.info - Desktop Client");
    
    

    # Menu Bar

    $self->{frame_bspi_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $self->{menu_file} = Wx::Menu->new();
    $self->{mnu_file_import} = $self->{menu_file}->Append(wxID_ANY, "Import...", "");
    $self->{mnu_file_export} = $self->{menu_file}->Append(wxID_ANY, "Export...", "");
    $self->{mnu_file_export_current} = $self->{menu_file}->Append(wxID_ANY, "Export Current Tab...", "");
    $self->{mnu_file_sep1} = $self->{menu_file}->Append(wxID_ANY, "---", "");
    $self->{mnu_file_open_data_dir} = $self->{menu_file}->Append(wxID_ANY, "Open Data Folder", "");
    $self->{mnu_file_sep2} = $self->{menu_file}->Append(wxID_ANY, "---", "");
    $self->{mnu_file_exit} = $self->{menu_file}->Append(wxID_ANY, "Exit", "");
    $self->{frame_bspi_menubar}->Append($self->{menu_file}, "File");
    $self->{menu_tools} = Wx::Menu->new();
    $self->{mnu_tools_validate_api} = $self->{menu_tools}->Append(wxID_ANY, "Validate API Credentials", "");
    $self->{mnu_tools_reconnect} = $self->{menu_tools}->Append(wxID_ANY, "Reconnect / Refresh Session", "");
    $self->{mnu_tools_sep1} = $self->{menu_tools}->Append(wxID_ANY, "---", "");
    $self->{mnu_tools_show_log} = $self->{menu_tools}->Append(wxID_ANY, "Show Log Window", "");
    $self->{mnu_tools_clear_log} = $self->{menu_tools}->Append(wxID_ANY, "Clear Log", "");
    $self->{frame_bspi_menubar}->Append($self->{menu_tools}, "Tools");
    $self->{menu_data} = Wx::Menu->new();
    $self->{mnu_data_sync_now} = $self->{menu_data}->Append(wxID_ANY, "Sync Now", "");
    $self->{mnu_data_download_year} = $self->{menu_data}->Append(wxID_ANY, "Download Year Data...", "");
    $self->{mnu_data_download_guides} = $self->{menu_data}->Append(wxID_ANY, "Download Price Guides...", "");
    $self->{mnu_data_sep1} = $self->{menu_data}->Append(wxID_ANY, "---", "");
    $self->{mnu_data_rebuild_index} = $self->{menu_data}->Append(wxID_ANY, "Rebuild Local Index", "");
    $self->{mnu_data_clear_cache} = $self->{menu_data}->Append(wxID_ANY, "Clear Local Cache...", "");
    $self->{frame_bspi_menubar}->Append($self->{menu_data}, "Data");
    $self->{menu_settings} = Wx::Menu->new();
    $self->{mnu_settings_api} = $self->{menu_settings}->Append(wxID_ANY, "API Credentials...", "");
    $self->{mnu_settings_storage} = $self->{menu_settings}->Append(wxID_ANY, "Offline Storage...", "");
    $self->{mnu_settings_export_defaults} = $self->{menu_settings}->Append(wxID_ANY, "Export Defaults...", "");
    $self->{mnu_settings_sep1} = $self->{menu_settings}->Append(wxID_ANY, "---", "");
    $self->{mnu_settings_advanced} = $self->{menu_settings}->Append(wxID_ANY, "Advanced...", "");
    $self->{frame_bspi_menubar}->Append($self->{menu_settings}, "Settings");
    $self->{menu_help} = Wx::Menu->new();
    $self->{mnu_help_quickstart} = $self->{menu_help}->Append(wxID_ANY, "Quick Start", "");
    $self->{mnu_help_docs} = $self->{menu_help}->Append(wxID_ANY, "Documentation", "");
    $self->{mnu_help_report} = $self->{menu_help}->Append(wxID_ANY, "Report a Problem...", "");
    $self->{frame_bspi_menubar}->Append($self->{menu_help}, "Help");
    $self->{menu_about} = Wx::Menu->new();
    $self->{mnu_about} = $self->{menu_about}->Append(wxID_ANY, "About BSPI Desktop Client", "");
    $self->{frame_bspi_menubar}->Append($self->{menu_about}, "About");
    $self->SetMenuBar($self->{frame_bspi_menubar});
    
    # Menu Bar end

    
    $self->{panel_root} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{txt_query} = Wx::TextCtrl->new($self->{panel_root}, wxID_ANY, "");
    $self->{txt_query}->SetMinSize(Wx::Size->new(-1,30));
    $self->{sizer_root}->Add($self->{txt_query}, 0, wxALL|wxEXPAND, 8);
    
    $self->{nb_main} = Wx::Notebook->new($self->{panel_root}, wxID_ANY);
    $self->{sizer_root}->Add($self->{nb_main}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{page_search} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_search}, "Main Search");
    
    $self->{sizer_search_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_query} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_search}, wxID_ANY, "Query"), wxVERTICAL);
    $self->{sizer_search_root}->Add($self->{box_query}, 0, wxALL|wxEXPAND, 8);
    
    $self->{sizer_date_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_query}->Add($self->{sizer_date_row}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_date_from = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Date from");
    $self->{sizer_date_row}->Add($lbl_date_from, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_date_from} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_date_from}->SetMinSize(Wx::Size->new(90,-1));
    $self->{sizer_date_row}->Add($self->{txt_date_from}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_pick_from} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "...");
    $self->{btn_pick_from}->SetMinSize(Wx::Size->new(28,22));
    $self->{sizer_date_row}->Add($self->{btn_pick_from}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    my $lbl_date_to = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "to");
    $self->{sizer_date_row}->Add($lbl_date_to, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10);
    
    $self->{txt_date_to} = Wx::TextCtrl->new($self->{box_query}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_date_to}->SetMinSize(Wx::Size->new(90,-1));
    $self->{sizer_date_row}->Add($self->{txt_date_to}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_pick_to} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "...");
    $self->{btn_pick_to}->SetMinSize(Wx::Size->new(28,22));
    $self->{sizer_date_row}->Add($self->{btn_pick_to}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_date_row}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{sizer_controls_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_query}->Add($self->{sizer_controls_row}, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    my $lbl_show = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Show");
    $self->{sizer_controls_row}->Add($lbl_show, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_show} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["10 Results", "50 Results", "100 Results", "500 Results"], );
    $self->{choice_show}->SetSelection(0);
    $self->{sizer_controls_row}->Add($self->{choice_show}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    my $lbl_order = Wx::StaticText->new($self->{box_query}->GetStaticBox(), wxID_ANY, "Order by");
    $self->{sizer_controls_row}->Add($lbl_order, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 12);
    
    $self->{choice_order} = Wx::Choice->new($self->{box_query}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Date", "Price", "Bids", "Seller"], );
    $self->{choice_order}->SetSelection(0);
    $self->{sizer_controls_row}->Add($self->{choice_order}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_controls_row}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_refine} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "refine");
    $self->{sizer_controls_row}->Add($self->{btn_refine}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_reset} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "reset");
    $self->{sizer_controls_row}->Add($self->{btn_reset}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_search} = Wx::Button->new($self->{box_query}->GetStaticBox(), wxID_ANY, "search");
    $self->{sizer_controls_row}->Add($self->{btn_search}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{box_results} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_search}, wxID_ANY, "Results"), wxVERTICAL);
    $self->{sizer_search_root}->Add($self->{box_results}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{list_results} = Wx::ListCtrl->new($self->{box_results}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_results}->Add($self->{list_results}, 1, wxALL|wxEXPAND, 6);
    
    my $lbl_status = Wx::StaticText->new($self->{page_search}, wxID_ANY, "Ready.");
    $self->{sizer_search_root}->Add($lbl_status, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{page_saved} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_saved}, "Items");
    
    $self->{sizer_items_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_items_toolbar} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_saved}, wxID_ANY, "Items"), wxHORIZONTAL);
    $self->{sizer_items_root}->Add($self->{box_items_toolbar}, 0, wxALL|wxEXPAND, 8);
    
    $self->{btn_item_new} = Wx::Button->new($self->{box_items_toolbar}->GetStaticBox(), wxID_ANY, "New");
    $self->{box_items_toolbar}->Add($self->{btn_item_new}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_item_edit} = Wx::Button->new($self->{box_items_toolbar}->GetStaticBox(), wxID_ANY, "Edit");
    $self->{box_items_toolbar}->Add($self->{btn_item_edit}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_item_merge} = Wx::Button->new($self->{box_items_toolbar}->GetStaticBox(), wxID_ANY, "Merge");
    $self->{box_items_toolbar}->Add($self->{btn_item_merge}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_item_delete} = Wx::Button->new($self->{box_items_toolbar}->GetStaticBox(), wxID_ANY, "Delete");
    $self->{box_items_toolbar}->Add($self->{btn_item_delete}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_items_toolbar}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_item_add_from_results} = Wx::Button->new($self->{box_items_toolbar}->GetStaticBox(), wxID_ANY, "Add From Search Selection");
    $self->{box_items_toolbar}->Add($self->{btn_item_add_from_results}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_item_export} = Wx::Button->new($self->{box_items_toolbar}->GetStaticBox(), wxID_ANY, "Export...");
    $self->{box_items_toolbar}->Add($self->{btn_item_export}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{split_items} = Wx::SplitterWindow->new($self->{page_saved}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_items}->SetMinimumPaneSize(20);
    $self->{sizer_items_root}->Add($self->{split_items}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{panel_items_left} = Wx::Panel->new($self->{split_items}, wxID_ANY);
    
    $self->{sizer_items_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_items_filter} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_items_left}->Add($self->{sizer_items_filter}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_items_filter = Wx::StaticText->new($self->{panel_items_left}, wxID_ANY, "Filter");
    $self->{sizer_items_filter}->Add($lbl_items_filter, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_items_filter} = Wx::TextCtrl->new($self->{panel_items_left}, wxID_ANY, "");
    $self->{sizer_items_filter}->Add($self->{txt_items_filter}, 1, wxEXPAND|wxLEFT, 6);
    
    $self->{btn_items_filter_clear} = Wx::Button->new($self->{panel_items_left}, wxID_ANY, "clear");
    $self->{sizer_items_filter}->Add($self->{btn_items_filter_clear}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{list_items} = Wx::ListCtrl->new($self->{panel_items_left}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_items_left}->Add($self->{list_items}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_items_right} = Wx::Panel->new($self->{split_items}, wxID_ANY);
    
    $self->{sizer_items_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_item_details} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_items_right}, wxID_ANY, "Selected Item"), wxVERTICAL);
    $self->{sizer_items_right}->Add($self->{box_item_details}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_item_meta} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_item_details}->Add($self->{grid_item_meta}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_item_name = Wx::StaticText->new($self->{box_item_details}->GetStaticBox(), wxID_ANY, "Name");
    $self->{grid_item_meta}->Add($lbl_item_name, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_item_name} = Wx::TextCtrl->new($self->{box_item_details}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_item_meta}->Add($self->{txt_item_name}, 1, wxEXPAND, 0);
    
    my $lbl_item_tags = Wx::StaticText->new($self->{box_item_details}->GetStaticBox(), wxID_ANY, "Tags");
    $self->{grid_item_meta}->Add($lbl_item_tags, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_item_tags} = Wx::TextCtrl->new($self->{box_item_details}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_item_meta}->Add($self->{txt_item_tags}, 1, wxEXPAND, 0);
    
    my $lbl_item_notes = Wx::StaticText->new($self->{box_item_details}->GetStaticBox(), wxID_ANY, "Notes");
    $self->{grid_item_meta}->Add($lbl_item_notes, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_item_notes} = Wx::TextCtrl->new($self->{box_item_details}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{grid_item_meta}->Add($self->{txt_item_notes}, 1, wxEXPAND, 0);
    
    $self->{box_item_records} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_items_right}, wxID_ANY, "Related Auction Records"), wxVERTICAL);
    $self->{sizer_items_right}->Add($self->{box_item_records}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_item_records} = Wx::ListCtrl->new($self->{box_item_records}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_item_records}->Add($self->{list_item_records}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sizer_item_actions_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_items_right}->Add($self->{sizer_item_actions_row}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_item_remove_record} = Wx::Button->new($self->{panel_items_right}, wxID_ANY, "Remove Selected Record");
    $self->{sizer_item_actions_row}->Add($self->{btn_item_remove_record}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_item_open_record} = Wx::Button->new($self->{panel_items_right}, wxID_ANY, "Open");
    $self->{sizer_item_actions_row}->Add($self->{btn_item_open_record}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_item_actions_row}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_item_save} = Wx::Button->new($self->{panel_items_right}, wxID_ANY, "Save Changes");
    $self->{sizer_item_actions_row}->Add($self->{btn_item_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{page_price} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_price}, "Price Guides");
    
    $self->{sizer_guides_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_guides_toolbar} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_price}, wxID_ANY, "Price Guides"), wxHORIZONTAL);
    $self->{sizer_guides_root}->Add($self->{box_guides_toolbar}, 0, wxALL|wxEXPAND, 8);
    
    $self->{btn_guide_new} = Wx::Button->new($self->{box_guides_toolbar}->GetStaticBox(), wxID_ANY, "New");
    $self->{box_guides_toolbar}->Add($self->{btn_guide_new}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_guide_edit} = Wx::Button->new($self->{box_guides_toolbar}->GetStaticBox(), wxID_ANY, "Edit");
    $self->{box_guides_toolbar}->Add($self->{btn_guide_edit}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_guide_delete} = Wx::Button->new($self->{box_guides_toolbar}->GetStaticBox(), wxID_ANY, "Delete");
    $self->{box_guides_toolbar}->Add($self->{btn_guide_delete}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{box_guides_toolbar}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_guide_export} = Wx::Button->new($self->{box_guides_toolbar}->GetStaticBox(), wxID_ANY, "Export Guide...");
    $self->{box_guides_toolbar}->Add($self->{btn_guide_export}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{btn_guide_export_all} = Wx::Button->new($self->{box_guides_toolbar}->GetStaticBox(), wxID_ANY, "Export All...");
    $self->{box_guides_toolbar}->Add($self->{btn_guide_export_all}, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    
    $self->{split_guides} = Wx::SplitterWindow->new($self->{page_price}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_LIVE_UPDATE);
    $self->{split_guides}->SetMinimumPaneSize(20);
    $self->{sizer_guides_root}->Add($self->{split_guides}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{panel_guides_left} = Wx::Panel->new($self->{split_guides}, wxID_ANY);
    
    $self->{sizer_guides_left} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_guides_filter} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_guides_left}->Add($self->{sizer_guides_filter}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_guides_filter = Wx::StaticText->new($self->{panel_guides_left}, wxID_ANY, "Filter");
    $self->{sizer_guides_filter}->Add($lbl_guides_filter, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_guides_filter} = Wx::TextCtrl->new($self->{panel_guides_left}, wxID_ANY, "");
    $self->{sizer_guides_filter}->Add($self->{txt_guides_filter}, 1, wxEXPAND|wxLEFT, 6);
    
    $self->{btn_guides_filter_clear} = Wx::Button->new($self->{panel_guides_left}, wxID_ANY, "clear");
    $self->{sizer_guides_filter}->Add($self->{btn_guides_filter_clear}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{list_guides} = Wx::ListCtrl->new($self->{panel_guides_left}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{sizer_guides_left}->Add($self->{list_guides}, 1, wxALL|wxEXPAND, 6);
    
    $self->{panel_guides_right} = Wx::Panel->new($self->{split_guides}, wxID_ANY);
    
    $self->{sizer_guides_right} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_guide_details} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_guides_right}, wxID_ANY, "Selected Guide"), wxVERTICAL);
    $self->{sizer_guides_right}->Add($self->{box_guide_details}, 0, wxALL|wxEXPAND, 6);
    
    $self->{grid_guide_meta} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_guide_details}->Add($self->{grid_guide_meta}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_guide_name = Wx::StaticText->new($self->{box_guide_details}->GetStaticBox(), wxID_ANY, "Name");
    $self->{grid_guide_meta}->Add($lbl_guide_name, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_guide_name} = Wx::TextCtrl->new($self->{box_guide_details}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_guide_meta}->Add($self->{txt_guide_name}, 1, wxEXPAND, 0);
    
    my $lbl_guide_scope = Wx::StaticText->new($self->{box_guide_details}->GetStaticBox(), wxID_ANY, "Scope");
    $self->{grid_guide_meta}->Add($lbl_guide_scope, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_guide_scope} = Wx::Choice->new($self->{box_guide_details}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["My Guides (local)", "Synced Guides (server)", "Mixed (local + server)"], );
    $self->{choice_guide_scope}->SetSelection(0);
    $self->{grid_guide_meta}->Add($self->{choice_guide_scope}, 1, wxEXPAND, 0);
    
    my $lbl_guide_notes = Wx::StaticText->new($self->{box_guide_details}->GetStaticBox(), wxID_ANY, "Notes");
    $self->{grid_guide_meta}->Add($lbl_guide_notes, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_guide_notes} = Wx::TextCtrl->new($self->{box_guide_details}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{grid_guide_meta}->Add($self->{txt_guide_notes}, 1, wxEXPAND, 0);
    
    $self->{box_guide_items} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{panel_guides_right}, wxID_ANY, "Items in Guide"), wxVERTICAL);
    $self->{sizer_guides_right}->Add($self->{box_guide_items}, 1, wxALL|wxEXPAND, 6);
    
    $self->{list_guide_items} = Wx::ListCtrl->new($self->{box_guide_items}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_guide_items}->Add($self->{list_guide_items}, 1, wxALL|wxEXPAND, 6);
    
    $self->{sizer_guide_actions} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_guides_right}->Add($self->{sizer_guide_actions}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_guide_add_item} = Wx::Button->new($self->{panel_guides_right}, wxID_ANY, "Add Item...");
    $self->{sizer_guide_actions}->Add($self->{btn_guide_add_item}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_guide_remove_item} = Wx::Button->new($self->{panel_guides_right}, wxID_ANY, "Remove Item");
    $self->{sizer_guide_actions}->Add($self->{btn_guide_remove_item}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_guide_actions}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_guide_save} = Wx::Button->new($self->{panel_guides_right}, wxID_ANY, "Save Changes");
    $self->{sizer_guide_actions}->Add($self->{btn_guide_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{page_offline} = Wx::Panel->new($self->{nb_main}, wxID_ANY);
    $self->{nb_main}->AddPage($self->{page_offline}, "Offline / Export");
    
    $self->{sizer_offline_root} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_offline_top} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_offline}, wxID_ANY, "Offline / Export"), wxVERTICAL);
    $self->{sizer_offline_root}->Add($self->{box_offline_top}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_offline_summary} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_offline_top}->Add($self->{grid_offline_summary}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_offline_cache_dir = Wx::StaticText->new($self->{box_offline_top}->GetStaticBox(), wxID_ANY, "Local data folder");
    $self->{grid_offline_summary}->Add($lbl_offline_cache_dir, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_offline_cache_dir} = Wx::TextCtrl->new($self->{box_offline_top}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_offline_summary}->Add($self->{txt_offline_cache_dir}, 1, wxEXPAND, 0);
    
    my $lbl_offline_mode = Wx::StaticText->new($self->{box_offline_top}->GetStaticBox(), wxID_ANY, "Mode");
    $self->{grid_offline_summary}->Add($lbl_offline_mode, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_offline_mode} = Wx::Choice->new($self->{box_offline_top}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Online (use API + cache)", "Offline (read-only, local cache)"], );
    $self->{choice_offline_mode}->SetSelection(0);
    $self->{grid_offline_summary}->Add($self->{choice_offline_mode}, 1, wxEXPAND, 0);
    
    $self->{sizer_offline_quick_actions} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_offline_top}->Add($self->{sizer_offline_quick_actions}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_offline_pick_dir} = Wx::Button->new($self->{box_offline_top}->GetStaticBox(), wxID_ANY, "Choose Folder...");
    $self->{sizer_offline_quick_actions}->Add($self->{btn_offline_pick_dir}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_offline_sync_now} = Wx::Button->new($self->{box_offline_top}->GetStaticBox(), wxID_ANY, "Sync Now");
    $self->{sizer_offline_quick_actions}->Add($self->{btn_offline_sync_now}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{btn_offline_pause} = Wx::Button->new($self->{box_offline_top}->GetStaticBox(), wxID_ANY, "Pause");
    $self->{sizer_offline_quick_actions}->Add($self->{btn_offline_pause}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_offline_quick_actions}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_offline_clear_cache} = Wx::Button->new($self->{box_offline_top}->GetStaticBox(), wxID_ANY, "Clear Cache...");
    $self->{sizer_offline_quick_actions}->Add($self->{btn_offline_clear_cache}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{nb_offline} = Wx::Notebook->new($self->{page_offline}, wxID_ANY);
    $self->{sizer_offline_root}->Add($self->{nb_offline}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{page_export_guides} = Wx::Panel->new($self->{nb_offline}, wxID_ANY);
    $self->{nb_offline}->AddPage($self->{page_export_guides}, "Export Guides");
    
    $self->{sizer_export_guides} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_export_guides} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_export_guides}, wxID_ANY, "Export Price Guides"), wxVERTICAL);
    $self->{sizer_export_guides}->Add($self->{box_export_guides}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_export_guides} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_export_guides}->Add($self->{grid_export_guides}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_export_guides_format = Wx::StaticText->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, "Format");
    $self->{grid_export_guides}->Add($lbl_export_guides_format, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_export_guides_format} = Wx::Choice->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["CSV", "TSV", "XLSX (via exporter)"], );
    $self->{choice_export_guides_format}->SetSelection(0);
    $self->{grid_export_guides}->Add($self->{choice_export_guides_format}, 1, wxEXPAND, 0);
    
    my $lbl_export_guides_scope = Wx::StaticText->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, "What to export");
    $self->{grid_export_guides}->Add($lbl_export_guides_scope, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_export_guides_scope} = Wx::Choice->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Selected guide", "All guides", "Selected guides"], );
    $self->{choice_export_guides_scope}->SetSelection(0);
    $self->{grid_export_guides}->Add($self->{choice_export_guides_scope}, 1, wxEXPAND, 0);
    
    my $lbl_export_guides_options = Wx::StaticText->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, "Options");
    $self->{grid_export_guides}->Add($lbl_export_guides_options, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_export_guides_include_items} = Wx::CheckBox->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, "Include guide items + rollups");
    $self->{grid_export_guides}->Add($self->{chk_export_guides_include_items}, 1, wxEXPAND, 0);
    
    my $lbl_export_guides_out = Wx::StaticText->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, "Output file");
    $self->{grid_export_guides}->Add($lbl_export_guides_out, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_export_guides_out} = Wx::TextCtrl->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_export_guides}->Add($self->{txt_export_guides_out}, 1, wxEXPAND, 0);
    
    $self->{sizer_export_guides_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_export_guides}->Add($self->{sizer_export_guides_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_export_guides_pick} = Wx::Button->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, "Choose...");
    $self->{sizer_export_guides_btns}->Add($self->{btn_export_guides_pick}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_export_guides_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_export_guides_run} = Wx::Button->new($self->{box_export_guides}->GetStaticBox(), wxID_ANY, "Export");
    $self->{sizer_export_guides_btns}->Add($self->{btn_export_guides_run}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_export_guides_preview} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_export_guides}, wxID_ANY, "Preview"), wxVERTICAL);
    $self->{sizer_export_guides}->Add($self->{box_export_guides_preview}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{list_export_guides_preview} = Wx::ListCtrl->new($self->{box_export_guides_preview}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_export_guides_preview}->Add($self->{list_export_guides_preview}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_export_raw} = Wx::Panel->new($self->{nb_offline}, wxID_ANY);
    $self->{nb_offline}->AddPage($self->{page_export_raw}, "Raw Data Export");
    
    $self->{sizer_export_raw} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_export_raw} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_export_raw}, wxID_ANY, "Raw Export (Premium)"), wxVERTICAL);
    $self->{sizer_export_raw}->Add($self->{box_export_raw}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_export_raw} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_export_raw}->Add($self->{grid_export_raw}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_raw_year = Wx::StaticText->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "Year");
    $self->{grid_export_raw}->Add($lbl_raw_year, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_raw_year} = Wx::TextCtrl->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_raw_year}->SetMinSize(Wx::Size->new(80,-1));
    $self->{grid_export_raw}->Add($self->{txt_raw_year}, 1, wxEXPAND, 0);
    
    my $lbl_raw_criteria = Wx::StaticText->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "Criteria");
    $self->{grid_export_raw}->Add($lbl_raw_criteria, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_raw_criteria} = Wx::TextCtrl->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_export_raw}->Add($self->{txt_raw_criteria}, 1, wxEXPAND, 0);
    
    my $lbl_raw_format = Wx::StaticText->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "Format");
    $self->{grid_export_raw}->Add($lbl_raw_format, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_raw_format} = Wx::Choice->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["CSV", "TSV", "XLSX (via exporter)"], );
    $self->{choice_raw_format}->SetSelection(0);
    $self->{grid_export_raw}->Add($self->{choice_raw_format}, 1, wxEXPAND, 0);
    
    my $lbl_raw_fields = Wx::StaticText->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "Fields");
    $self->{grid_export_raw}->Add($lbl_raw_fields, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_raw_fields} = Wx::Choice->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Default (recommended)", "Extended", "Full (all fields)"], );
    $self->{choice_raw_fields}->SetSelection(0);
    $self->{grid_export_raw}->Add($self->{choice_raw_fields}, 1, wxEXPAND, 0);
    
    my $lbl_raw_out = Wx::StaticText->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "Output file");
    $self->{grid_export_raw}->Add($lbl_raw_out, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_raw_out} = Wx::TextCtrl->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_export_raw}->Add($self->{txt_raw_out}, 1, wxEXPAND, 0);
    
    $self->{sizer_raw_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_export_raw}->Add($self->{sizer_raw_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_raw_pick} = Wx::Button->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "Choose...");
    $self->{sizer_raw_btns}->Add($self->{btn_raw_pick}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_raw_preview} = Wx::Button->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "Preview");
    $self->{sizer_raw_btns}->Add($self->{btn_raw_preview}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_raw_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_raw_export} = Wx::Button->new($self->{box_export_raw}->GetStaticBox(), wxID_ANY, "Export");
    $self->{sizer_raw_btns}->Add($self->{btn_raw_export}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_raw_preview} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_export_raw}, wxID_ANY, "Preview"), wxVERTICAL);
    $self->{sizer_export_raw}->Add($self->{box_raw_preview}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{list_raw_preview} = Wx::ListCtrl->new($self->{box_raw_preview}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_raw_preview}->Add($self->{list_raw_preview}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_year_downloads} = Wx::Panel->new($self->{nb_offline}, wxID_ANY);
    $self->{nb_offline}->AddPage($self->{page_year_downloads}, "Year Downloads");
    
    $self->{sizer_year_downloads} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_year_downloads} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_year_downloads}, wxID_ANY, "Year Downloads (Offline Packs)"), wxVERTICAL);
    $self->{sizer_year_downloads}->Add($self->{box_year_downloads}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_year_downloads} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_year_downloads}->Add($self->{grid_year_downloads}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_year_pack_year = Wx::StaticText->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, "Year");
    $self->{grid_year_downloads}->Add($lbl_year_pack_year, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_year_pack_year} = Wx::TextCtrl->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, "");
    $self->{txt_year_pack_year}->SetMinSize(Wx::Size->new(80,-1));
    $self->{grid_year_downloads}->Add($self->{txt_year_pack_year}, 1, wxEXPAND, 0);
    
    my $lbl_year_pack_type = Wx::StaticText->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, "Pack contents");
    $self->{grid_year_downloads}->Add($lbl_year_pack_type, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_year_pack_type} = Wx::Choice->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Full year (all records)", "Summary (report-friendly)", "Images + metadata (if available)"], );
    $self->{choice_year_pack_type}->SetSelection(0);
    $self->{grid_year_downloads}->Add($self->{choice_year_pack_type}, 1, wxEXPAND, 0);
    
    my $lbl_year_pack_out = Wx::StaticText->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, "Destination");
    $self->{grid_year_downloads}->Add($lbl_year_pack_out, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_year_pack_out} = Wx::TextCtrl->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_year_downloads}->Add($self->{txt_year_pack_out}, 1, wxEXPAND, 0);
    
    $self->{sizer_year_pack_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_year_downloads}->Add($self->{sizer_year_pack_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_year_pack_pick} = Wx::Button->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, "Choose...");
    $self->{sizer_year_pack_btns}->Add($self->{btn_year_pack_pick}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_year_pack_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_year_pack_download} = Wx::Button->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, "Download");
    $self->{sizer_year_pack_btns}->Add($self->{btn_year_pack_download}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{gauge_year_pack} = Wx::Gauge->new($self->{box_year_downloads}->GetStaticBox(), wxID_ANY, 100, wxDefaultPosition, wxDefaultSize, 0);
    $self->{box_year_downloads}->Add($self->{gauge_year_pack}, 0, wxALL|wxEXPAND, 6);
    
    $self->{box_year_pack_history} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_year_downloads}, wxID_ANY, "Downloaded Packs"), wxVERTICAL);
    $self->{sizer_year_downloads}->Add($self->{box_year_pack_history}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{list_year_pack_history} = Wx::ListCtrl->new($self->{box_year_pack_history}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxLC_REPORT|wxLC_SINGLE_SEL);
    $self->{box_year_pack_history}->Add($self->{list_year_pack_history}, 1, wxALL|wxEXPAND, 6);
    
    $self->{page_offline_settings} = Wx::Panel->new($self->{nb_offline}, wxID_ANY);
    $self->{nb_offline}->AddPage($self->{page_offline_settings}, "Offline Settings");
    
    $self->{sizer_offline_settings} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_api_creds} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_offline_settings}, wxID_ANY, "API Credentials"), wxVERTICAL);
    $self->{sizer_offline_settings}->Add($self->{box_api_creds}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_api_creds} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_api_creds}->Add($self->{grid_api_creds}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_api_key = Wx::StaticText->new($self->{box_api_creds}->GetStaticBox(), wxID_ANY, "API key");
    $self->{grid_api_creds}->Add($lbl_api_key, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_api_key} = Wx::TextCtrl->new($self->{box_api_creds}->GetStaticBox(), wxID_ANY, "");
    $self->{grid_api_creds}->Add($self->{txt_api_key}, 1, wxEXPAND, 0);
    
    my $lbl_api_secret = Wx::StaticText->new($self->{box_api_creds}->GetStaticBox(), wxID_ANY, "API secret");
    $self->{grid_api_creds}->Add($lbl_api_secret, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_api_secret} = Wx::TextCtrl->new($self->{box_api_creds}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    $self->{grid_api_creds}->Add($self->{txt_api_secret}, 1, wxEXPAND, 0);
    
    my $lbl_api_base_url = Wx::StaticText->new($self->{box_api_creds}->GetStaticBox(), wxID_ANY, "API base URL");
    $self->{grid_api_creds}->Add($lbl_api_base_url, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{txt_api_base_url} = Wx::TextCtrl->new($self->{box_api_creds}->GetStaticBox(), wxID_ANY, "https://boyscoutpatch.info/api");
    $self->{grid_api_creds}->Add($self->{txt_api_base_url}, 1, wxEXPAND, 0);
    
    $self->{sizer_api_creds_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_api_creds}->Add($self->{sizer_api_creds_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_api_test} = Wx::Button->new($self->{box_api_creds}->GetStaticBox(), wxID_ANY, "Test Connection");
    $self->{sizer_api_creds_btns}->Add($self->{btn_api_test}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{sizer_api_creds_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_api_save} = Wx::Button->new($self->{box_api_creds}->GetStaticBox(), wxID_ANY, "Save Settings");
    $self->{sizer_api_creds_btns}->Add($self->{btn_api_save}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_export_defaults} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_offline_settings}, wxID_ANY, "Export Defaults"), wxVERTICAL);
    $self->{sizer_offline_settings}->Add($self->{box_export_defaults}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{grid_export_defaults} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_export_defaults}->Add($self->{grid_export_defaults}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_default_export_format = Wx::StaticText->new($self->{box_export_defaults}->GetStaticBox(), wxID_ANY, "Default format");
    $self->{grid_export_defaults}->Add($lbl_default_export_format, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_default_export_format} = Wx::Choice->new($self->{box_export_defaults}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["CSV", "TSV", "XLSX (via exporter)"], );
    $self->{choice_default_export_format}->SetSelection(0);
    $self->{grid_export_defaults}->Add($self->{choice_default_export_format}, 1, wxEXPAND, 0);
    
    my $lbl_default_delimiter = Wx::StaticText->new($self->{box_export_defaults}->GetStaticBox(), wxID_ANY, "Delimiter");
    $self->{grid_export_defaults}->Add($lbl_default_delimiter, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{choice_default_delimiter} = Wx::Choice->new($self->{box_export_defaults}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Comma", "Tab"], );
    $self->{choice_default_delimiter}->SetSelection(0);
    $self->{grid_export_defaults}->Add($self->{choice_default_delimiter}, 1, wxEXPAND, 0);
    
    my $lbl_default_include_images = Wx::StaticText->new($self->{box_export_defaults}->GetStaticBox(), wxID_ANY, "Images");
    $self->{grid_export_defaults}->Add($lbl_default_include_images, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{chk_default_include_images} = Wx::CheckBox->new($self->{box_export_defaults}->GetStaticBox(), wxID_ANY, "Include image URLs when available");
    $self->{grid_export_defaults}->Add($self->{chk_default_include_images}, 1, wxEXPAND, 0);
    
    $self->{page_sync_log} = Wx::Panel->new($self->{nb_offline}, wxID_ANY);
    $self->{nb_offline}->AddPage($self->{page_sync_log}, "Sync / Log");
    
    $self->{sizer_sync_log} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{box_sync_status} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_sync_log}, wxID_ANY, "Sync Status"), wxVERTICAL);
    $self->{sizer_sync_log}->Add($self->{box_sync_status}, 0, wxALL|wxEXPAND, 8);
    
    $self->{grid_sync_status} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{box_sync_status}->Add($self->{grid_sync_status}, 0, wxALL|wxEXPAND, 6);
    
    my $lbl_sync_last = Wx::StaticText->new($self->{box_sync_status}->GetStaticBox(), wxID_ANY, "Last sync");
    $self->{grid_sync_status}->Add($lbl_sync_last, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $txt_sync_last = Wx::StaticText->new($self->{box_sync_status}->GetStaticBox(), wxID_ANY, "Never");
    $self->{grid_sync_status}->Add($txt_sync_last, 1, wxEXPAND, 0);
    
    my $lbl_sync_queue = Wx::StaticText->new($self->{box_sync_status}->GetStaticBox(), wxID_ANY, "Queue");
    $self->{grid_sync_status}->Add($lbl_sync_queue, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    my $txt_sync_queue = Wx::StaticText->new($self->{box_sync_status}->GetStaticBox(), wxID_ANY, "0 pending");
    $self->{grid_sync_status}->Add($txt_sync_queue, 1, wxEXPAND, 0);
    
    $self->{gauge_sync} = Wx::Gauge->new($self->{box_sync_status}->GetStaticBox(), wxID_ANY, 100, wxDefaultPosition, wxDefaultSize, 0);
    $self->{box_sync_status}->Add($self->{gauge_sync}, 0, wxALL|wxEXPAND, 6);
    
    $self->{sizer_log_btns} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{box_sync_status}->Add($self->{sizer_log_btns}, 0, wxALL|wxEXPAND, 6);
    
    $self->{btn_log_copy} = Wx::Button->new($self->{box_sync_status}->GetStaticBox(), wxID_ANY, "Copy");
    $self->{sizer_log_btns}->Add($self->{btn_log_copy}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{btn_log_save} = Wx::Button->new($self->{box_sync_status}->GetStaticBox(), wxID_ANY, "Save...");
    $self->{sizer_log_btns}->Add($self->{btn_log_save}, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 6);
    
    $self->{sizer_log_btns}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{btn_log_clear} = Wx::Button->new($self->{box_sync_status}->GetStaticBox(), wxID_ANY, "Clear");
    $self->{sizer_log_btns}->Add($self->{btn_log_clear}, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{box_log} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{page_sync_log}, wxID_ANY, "Log"), wxVERTICAL);
    $self->{sizer_sync_log}->Add($self->{box_log}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 8);
    
    $self->{txt_log} = Wx::TextCtrl->new($self->{box_log}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{box_log}->Add($self->{txt_log}, 1, wxALL|wxEXPAND, 6);
    
    $self->{grid_sync_status}->AddGrowableCol(1);
    
    $self->{page_sync_log}->SetSizer($self->{sizer_sync_log});
    
    $self->{grid_export_defaults}->AddGrowableCol(1);
    
    $self->{grid_api_creds}->AddGrowableCol(1);
    
    $self->{page_offline_settings}->SetSizer($self->{sizer_offline_settings});
    
    $self->{grid_year_downloads}->AddGrowableCol(1);
    
    $self->{page_year_downloads}->SetSizer($self->{sizer_year_downloads});
    
    $self->{grid_export_raw}->AddGrowableCol(1);
    
    $self->{page_export_raw}->SetSizer($self->{sizer_export_raw});
    
    $self->{grid_export_guides}->AddGrowableCol(1);
    
    $self->{page_export_guides}->SetSizer($self->{sizer_export_guides});
    
    $self->{grid_offline_summary}->AddGrowableCol(1);
    
    $self->{page_offline}->SetSizer($self->{sizer_offline_root});
    
    $self->{grid_guide_meta}->AddGrowableCol(1);
    
    $self->{panel_guides_right}->SetSizer($self->{sizer_guides_right});
    
    $self->{panel_guides_left}->SetSizer($self->{sizer_guides_left});
    
    $self->{split_guides}->SplitVertically($self->{panel_guides_left}, $self->{panel_guides_right}, );
    
    $self->{page_price}->SetSizer($self->{sizer_guides_root});
    
    $self->{grid_item_meta}->AddGrowableCol(1);
    
    $self->{panel_items_right}->SetSizer($self->{sizer_items_right});
    
    $self->{panel_items_left}->SetSizer($self->{sizer_items_left});
    
    $self->{split_items}->SplitVertically($self->{panel_items_left}, $self->{panel_items_right}, );
    
    $self->{page_saved}->SetSizer($self->{sizer_items_root});
    
    $self->{page_search}->SetSizer($self->{sizer_search_root});
    
    $self->{panel_root}->SetSizer($self->{sizer_root});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class BSPIMainFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame_bspi = BSPIMainFrame->new();

    $self->SetTopWindow($frame_bspi);
    $frame_bspi->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
